// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/gov/v1beta1/gov.proto

package types

import (
	fmt "fmt"
	math "math"
	time "time"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	_ "github.com/regen-network/cosmos-proto"
	types1 "github.com/sei-protocol/sei-chain/sei-cosmos/codec/types"
	github_com_sei_protocol_sei_chain_sei_cosmos_types "github.com/sei-protocol/sei-chain/sei-cosmos/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// VoteOption enumerates the valid vote options for a given governance proposal.
type VoteOption int32

const (
	// VOTE_OPTION_UNSPECIFIED defines a no-op vote option.
	OptionEmpty VoteOption = 0
	// VOTE_OPTION_YES defines a yes vote option.
	OptionYes VoteOption = 1
	// VOTE_OPTION_ABSTAIN defines an abstain vote option.
	OptionAbstain VoteOption = 2
	// VOTE_OPTION_NO defines a no vote option.
	OptionNo VoteOption = 3
	// VOTE_OPTION_NO_WITH_VETO defines a no with veto vote option.
	OptionNoWithVeto VoteOption = 4
)

var VoteOption_name = map[int32]string{
	0: "VOTE_OPTION_UNSPECIFIED",
	1: "VOTE_OPTION_YES",
	2: "VOTE_OPTION_ABSTAIN",
	3: "VOTE_OPTION_NO",
	4: "VOTE_OPTION_NO_WITH_VETO",
}

var VoteOption_value = map[string]int32{
	"VOTE_OPTION_UNSPECIFIED":  0,
	"VOTE_OPTION_YES":          1,
	"VOTE_OPTION_ABSTAIN":      2,
	"VOTE_OPTION_NO":           3,
	"VOTE_OPTION_NO_WITH_VETO": 4,
}

func (x VoteOption) String() string { _ = "STUB: not implemented"; return "" }

func (VoteOption) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// ProposalStatus enumerates the valid statuses of a proposal.
type ProposalStatus int32

const (
	// PROPOSAL_STATUS_UNSPECIFIED defines the default propopsal status.
	StatusNil ProposalStatus = 0
	// PROPOSAL_STATUS_DEPOSIT_PERIOD defines a proposal status during the deposit
	// period.
	StatusDepositPeriod ProposalStatus = 1
	// PROPOSAL_STATUS_VOTING_PERIOD defines a proposal status during the voting
	// period.
	StatusVotingPeriod ProposalStatus = 2
	// PROPOSAL_STATUS_PASSED defines a proposal status of a proposal that has
	// passed.
	StatusPassed ProposalStatus = 3
	// PROPOSAL_STATUS_REJECTED defines a proposal status of a proposal that has
	// been rejected.
	StatusRejected ProposalStatus = 4
	// PROPOSAL_STATUS_FAILED defines a proposal status of a proposal that has
	// failed.
	StatusFailed ProposalStatus = 5
)

var ProposalStatus_name = map[int32]string{
	0: "PROPOSAL_STATUS_UNSPECIFIED",
	1: "PROPOSAL_STATUS_DEPOSIT_PERIOD",
	2: "PROPOSAL_STATUS_VOTING_PERIOD",
	3: "PROPOSAL_STATUS_PASSED",
	4: "PROPOSAL_STATUS_REJECTED",
	5: "PROPOSAL_STATUS_FAILED",
}

var ProposalStatus_value = map[string]int32{
	"PROPOSAL_STATUS_UNSPECIFIED":    0,
	"PROPOSAL_STATUS_DEPOSIT_PERIOD": 1,
	"PROPOSAL_STATUS_VOTING_PERIOD":  2,
	"PROPOSAL_STATUS_PASSED":         3,
	"PROPOSAL_STATUS_REJECTED":       4,
	"PROPOSAL_STATUS_FAILED":         5,
}

func (x ProposalStatus) String() string { _ = "STUB: not implemented"; return "" }

func (ProposalStatus) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// WeightedVoteOption defines a unit of vote for vote split.
//
// Since: cosmos-sdk 0.43
type WeightedVoteOption struct {
	Option VoteOption                                             `protobuf:"varint,1,opt,name=option,proto3,enum=cosmos.gov.v1beta1.VoteOption" json:"option,omitempty"`
	Weight github_com_sei_protocol_sei_chain_sei_cosmos_types.Dec `protobuf:"bytes,2,opt,name=weight,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Dec" json:"weight" yaml:"weight"`
}

func (m *WeightedVoteOption) Reset()                    { _ = "STUB: not implemented"; return }
func (*WeightedVoteOption) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*WeightedVoteOption) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *WeightedVoteOption) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *WeightedVoteOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *WeightedVoteOption) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *WeightedVoteOption) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *WeightedVoteOption) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_WeightedVoteOption proto.InternalMessageInfo

// TextProposal defines a standard text proposal whose changes need to be
// manually updated in case of approval.
type TextProposal struct {
	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	IsExpedited bool   `protobuf:"varint,3,opt,name=is_expedited,json=isExpedited,proto3" json:"is_expedited,omitempty"`
}

func (m *TextProposal) Reset()                    { _ = "STUB: not implemented"; return }
func (*TextProposal) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*TextProposal) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *TextProposal) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TextProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TextProposal) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *TextProposal) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *TextProposal) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_TextProposal proto.InternalMessageInfo

// Deposit defines an amount deposited by an account address to an active
// proposal.
type Deposit struct {
	ProposalId uint64                                                   `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty" yaml:"proposal_id"`
	Depositor  string                                                   `protobuf:"bytes,2,opt,name=depositor,proto3" json:"depositor,omitempty"`
	Amount     github_com_sei_protocol_sei_chain_sei_cosmos_types.Coins `protobuf:"bytes,3,rep,name=amount,proto3,castrepeated=github.com/sei-protocol/sei-chain/sei-cosmos/types.Coins" json:"amount"`
}

func (m *Deposit) Reset()                    { _ = "STUB: not implemented"; return }
func (*Deposit) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Deposit) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Deposit) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Deposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Deposit) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Deposit) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Deposit) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Deposit proto.InternalMessageInfo

// Proposal defines the core field members of a governance proposal.
type Proposal struct {
	ProposalId       uint64                                                   `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"id" yaml:"id"`
	Content          *types1.Any                                              `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Status           ProposalStatus                                           `protobuf:"varint,3,opt,name=status,proto3,enum=cosmos.gov.v1beta1.ProposalStatus" json:"status,omitempty" yaml:"proposal_status"`
	FinalTallyResult TallyResult                                              `protobuf:"bytes,4,opt,name=final_tally_result,json=finalTallyResult,proto3" json:"final_tally_result" yaml:"final_tally_result"`
	SubmitTime       time.Time                                                `protobuf:"bytes,5,opt,name=submit_time,json=submitTime,proto3,stdtime" json:"submit_time" yaml:"submit_time"`
	DepositEndTime   time.Time                                                `protobuf:"bytes,6,opt,name=deposit_end_time,json=depositEndTime,proto3,stdtime" json:"deposit_end_time" yaml:"deposit_end_time"`
	TotalDeposit     github_com_sei_protocol_sei_chain_sei_cosmos_types.Coins `protobuf:"bytes,7,rep,name=total_deposit,json=totalDeposit,proto3,castrepeated=github.com/sei-protocol/sei-chain/sei-cosmos/types.Coins" json:"total_deposit" yaml:"total_deposit"`
	VotingStartTime  time.Time                                                `protobuf:"bytes,8,opt,name=voting_start_time,json=votingStartTime,proto3,stdtime" json:"voting_start_time" yaml:"voting_start_time"`
	VotingEndTime    time.Time                                                `protobuf:"bytes,9,opt,name=voting_end_time,json=votingEndTime,proto3,stdtime" json:"voting_end_time" yaml:"voting_end_time"`
	IsExpedited      bool                                                     `protobuf:"varint,10,opt,name=is_expedited,json=isExpedited,proto3" json:"is_expedited,omitempty"`
}

func (m *Proposal) Reset()                    { _ = "STUB: not implemented"; return }
func (*Proposal) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Proposal) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Proposal) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Proposal) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Proposal) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Proposal) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Proposal proto.InternalMessageInfo

// TallyResult defines a standard tally for a governance proposal.
type TallyResult struct {
	Yes        github_com_sei_protocol_sei_chain_sei_cosmos_types.Int `protobuf:"bytes,1,opt,name=yes,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Int" json:"yes"`
	Abstain    github_com_sei_protocol_sei_chain_sei_cosmos_types.Int `protobuf:"bytes,2,opt,name=abstain,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Int" json:"abstain"`
	No         github_com_sei_protocol_sei_chain_sei_cosmos_types.Int `protobuf:"bytes,3,opt,name=no,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Int" json:"no"`
	NoWithVeto github_com_sei_protocol_sei_chain_sei_cosmos_types.Int `protobuf:"bytes,4,opt,name=no_with_veto,json=noWithVeto,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Int" json:"no_with_veto" yaml:"no_with_veto"`
}

func (m *TallyResult) Reset()                    { _ = "STUB: not implemented"; return }
func (*TallyResult) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*TallyResult) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *TallyResult) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TallyResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TallyResult) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *TallyResult) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *TallyResult) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_TallyResult proto.InternalMessageInfo

// Vote defines a vote on a governance proposal.
// A Vote consists of a proposal ID, the voter, and the vote option.
type Vote struct {
	ProposalId uint64 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty" yaml:"proposal_id"`
	Voter      string `protobuf:"bytes,2,opt,name=voter,proto3" json:"voter,omitempty"`
	// Deprecated: Prefer to use `options` instead. This field is set in queries
	// if and only if `len(options) == 1` and that option has weight 1. In all
	// other cases, this field will default to VOTE_OPTION_UNSPECIFIED.
	Option VoteOption `protobuf:"varint,3,opt,name=option,proto3,enum=cosmos.gov.v1beta1.VoteOption" json:"option,omitempty"` // Deprecated: Do not use.
	// Since: cosmos-sdk 0.43
	Options []WeightedVoteOption `protobuf:"bytes,4,rep,name=options,proto3" json:"options"`
}

func (m *Vote) Reset()                    { _ = "STUB: not implemented"; return }
func (*Vote) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Vote) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Vote) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Vote) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Vote) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Vote) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Vote proto.InternalMessageInfo

// DepositParams defines the params for deposits on governance proposals.
type DepositParams struct {
	//  Minimum deposit for a proposal to enter voting period.
	MinDeposit github_com_sei_protocol_sei_chain_sei_cosmos_types.Coins `protobuf:"bytes,1,rep,name=min_deposit,json=minDeposit,proto3,castrepeated=github.com/sei-protocol/sei-chain/sei-cosmos/types.Coins" json:"min_deposit,omitempty" yaml:"min_deposit"`
	//  Maximum period for Atom holders to deposit on a proposal. Initial value: 2
	//  months.
	MaxDepositPeriod time.Duration `protobuf:"bytes,2,opt,name=max_deposit_period,json=maxDepositPeriod,proto3,stdduration" json:"max_deposit_period,omitempty" yaml:"max_deposit_period"`
	//  Minimum deposit for a expedited proposal to enter voting period.
	MinExpeditedDeposit github_com_sei_protocol_sei_chain_sei_cosmos_types.Coins `protobuf:"bytes,3,rep,name=min_expedited_deposit,json=minExpeditedDeposit,proto3,castrepeated=github.com/sei-protocol/sei-chain/sei-cosmos/types.Coins" json:"min_expedited_deposit,omitempty" yaml:"min_expedited_deposit"`
}

func (m *DepositParams) Reset()                    { _ = "STUB: not implemented"; return }
func (*DepositParams) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*DepositParams) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *DepositParams) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *DepositParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DepositParams) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *DepositParams) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *DepositParams) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_DepositParams proto.InternalMessageInfo

// VotingParams defines the params for voting on governance proposals.
type VotingParams struct {
	//  Length of the voting period.
	VotingPeriod time.Duration `protobuf:"bytes,1,opt,name=voting_period,json=votingPeriod,proto3,stdduration" json:"voting_period,omitempty" yaml:"voting_period"`
	// Length of the expedited voting period.
	ExpeditedVotingPeriod time.Duration `protobuf:"bytes,2,opt,name=expedited_voting_period,json=expeditedVotingPeriod,proto3,stdduration" json:"expedited_voting_period,omitempty" yaml:"expedited_voting_period"`
}

func (m *VotingParams) Reset()                    { _ = "STUB: not implemented"; return }
func (*VotingParams) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*VotingParams) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *VotingParams) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *VotingParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *VotingParams) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *VotingParams) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *VotingParams) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_VotingParams proto.InternalMessageInfo

// TallyParams defines the params for tallying votes on governance proposals.
type TallyParams struct {
	//  Minimum percentage of total stake needed to vote for a result to be
	//  considered valid.
	Quorum github_com_sei_protocol_sei_chain_sei_cosmos_types.Dec `protobuf:"bytes,1,opt,name=quorum,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Dec" json:"quorum,omitempty"`
	//  Minimum proportion of Yes votes for proposal to pass. Default value: 0.5.
	Threshold github_com_sei_protocol_sei_chain_sei_cosmos_types.Dec `protobuf:"bytes,2,opt,name=threshold,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Dec" json:"threshold,omitempty"`
	//  Minimum value of Veto votes to Total votes ratio for proposal to be
	//  vetoed. Default value: 1/3.
	VetoThreshold github_com_sei_protocol_sei_chain_sei_cosmos_types.Dec `protobuf:"bytes,3,opt,name=veto_threshold,json=vetoThreshold,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Dec" json:"veto_threshold,omitempty" yaml:"veto_threshold"`
	//  Minimum percentage of total stake needed to vote for expedited proposal to be valid
	ExpeditedQuorum github_com_sei_protocol_sei_chain_sei_cosmos_types.Dec `protobuf:"bytes,4,opt,name=expedited_quorum,json=expeditedQuorum,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Dec" json:"expedited_quorum,omitempty"`
	//  Minimum proportion of Yes votes for an expedited proposal to pass. Default value: 0.67.
	ExpeditedThreshold github_com_sei_protocol_sei_chain_sei_cosmos_types.Dec `protobuf:"bytes,5,opt,name=expedited_threshold,json=expeditedThreshold,proto3,customtype=github.com/sei-protocol/sei-chain/sei-cosmos/types.Dec" json:"expedited_threshold,omitempty"`
}

func (m *TallyParams) Reset()                    { _ = "STUB: not implemented"; return }
func (*TallyParams) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*TallyParams) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *TallyParams) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TallyParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TallyParams) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *TallyParams) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *TallyParams) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_TallyParams proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("cosmos.gov.v1beta1.VoteOption", VoteOption_name, VoteOption_value)
	proto.RegisterEnum("cosmos.gov.v1beta1.ProposalStatus", ProposalStatus_name, ProposalStatus_value)
	proto.RegisterType((*WeightedVoteOption)(nil), "cosmos.gov.v1beta1.WeightedVoteOption")
	proto.RegisterType((*TextProposal)(nil), "cosmos.gov.v1beta1.TextProposal")
	proto.RegisterType((*Deposit)(nil), "cosmos.gov.v1beta1.Deposit")
	proto.RegisterType((*Proposal)(nil), "cosmos.gov.v1beta1.Proposal")
	proto.RegisterType((*TallyResult)(nil), "cosmos.gov.v1beta1.TallyResult")
	proto.RegisterType((*Vote)(nil), "cosmos.gov.v1beta1.Vote")
	proto.RegisterType((*DepositParams)(nil), "cosmos.gov.v1beta1.DepositParams")
	proto.RegisterType((*VotingParams)(nil), "cosmos.gov.v1beta1.VotingParams")
	proto.RegisterType((*TallyParams)(nil), "cosmos.gov.v1beta1.TallyParams")
}

func init() { proto.RegisterFile("cosmos/gov/v1beta1/gov.proto", fileDescriptor_6e82113c1a9a4b7c) }

var fileDescriptor_6e82113c1a9a4b7c = []byte{
	// 1621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0xcf, 0x6f, 0x1b, 0x4d,
	0x19, 0xf6, 0xda, 0xce, 0x0f, 0x8f, 0x9d, 0x64, 0x3b, 0x49, 0x13, 0xc7, 0xa4, 0xbb, 0xee, 0x82,
	0x50, 0x54, 0xb5, 0x0e, 0x0d, 0xa8, 0x40, 0x2a, 0x21, 0xec, 0x78, 0x03, 0x46, 0x95, 0x6d, 0xd6,
	0xae, 0xdb, 0x02, 0x62, 0xb5, 0xb1, 0xa7, 0xce, 0x56, 0xde, 0x1d, 0xe3, 0x1d, 0xa7, 0x09, 0x5c,
	0x90, 0x38, 0x50, 0xf9, 0x80, 0x7a, 0xac, 0x90, 0x2c, 0x55, 0xc0, 0x81, 0x1f, 0x17, 0x0e, 0xf0,
	0x3f, 0x54, 0x88, 0x43, 0x05, 0x97, 0x8a, 0x83, 0x4b, 0x13, 0xe9, 0x53, 0xd5, 0x63, 0xfe, 0x82,
	0x4f, 0x3b, 0x33, 0x6b, 0xef, 0xda, 0xa9, 0xfc, 0x7d, 0xf5, 0x6d, 0xf7, 0x9d, 0xf7, 0x7d, 0x9e,
	0x67, 0x9e, 0x99, 0x79, 0x67, 0x6d, 0xb0, 0x55, 0xc7, 0x8e, 0x85, 0x9d, 0x9d, 0x26, 0x3e, 0xde,
	0x39, 0xbe, 0x7d, 0x88, 0x88, 0x71, 0xdb, 0x7d, 0xce, 0xb4, 0x3b, 0x98, 0x60, 0x08, 0xd9, 0x68,
	0xc6, 0x8d, 0xf0, 0xd1, 0x94, 0xc4, 0x2b, 0x0e, 0x0d, 0x07, 0x0d, 0x4b, 0xea, 0xd8, 0xb4, 0x59,
	0x4d, 0x6a, 0x93, 0x8d, 0xeb, 0xf4, 0x6d, 0x87, 0x03, 0xb0, 0xa1, 0xb5, 0x26, 0x6e, 0x62, 0x16,
	0x77, 0x9f, 0xbc, 0x82, 0x26, 0xc6, 0xcd, 0x16, 0xda, 0xa1, 0x6f, 0x87, 0xdd, 0xc7, 0x3b, 0x86,
	0x7d, 0xca, 0x87, 0xa4, 0xf1, 0xa1, 0x46, 0xb7, 0x63, 0x10, 0x13, 0x7b, 0x5c, 0xf2, 0xf8, 0x38,
	0x31, 0x2d, 0xe4, 0x10, 0xc3, 0x6a, 0xb3, 0x04, 0xe5, 0x9f, 0x02, 0x80, 0x0f, 0x90, 0xd9, 0x3c,
	0x22, 0xa8, 0x51, 0xc3, 0x04, 0x95, 0xda, 0x6e, 0x35, 0xbc, 0x03, 0xe6, 0x31, 0x7d, 0x4a, 0x0a,
	0x69, 0x61, 0x7b, 0x79, 0x57, 0xca, 0x4c, 0x4e, 0x34, 0x33, 0xca, 0xd7, 0x78, 0x36, 0x6c, 0x82,
	0xf9, 0xa7, 0x14, 0x2d, 0x19, 0x4e, 0x0b, 0xdb, 0xb1, 0x5c, 0xe9, 0xd5, 0x40, 0x0e, 0xfd, 0x6f,
	0x20, 0xdf, 0x69, 0x9a, 0xe4, 0xa8, 0x7b, 0x98, 0xa9, 0x63, 0x6b, 0xc7, 0x41, 0xe6, 0x2d, 0x4a,
	0x5e, 0xc7, 0x2d, 0xfa, 0x52, 0x3f, 0x32, 0x4c, 0x9b, 0x3d, 0x31, 0xe7, 0xc8, 0x69, 0x1b, 0x39,
	0x99, 0x3c, 0xaa, 0x5f, 0x0c, 0xe4, 0xa5, 0x53, 0xc3, 0x6a, 0xed, 0x29, 0x0c, 0x55, 0xd1, 0x38,
	0xbc, 0xf2, 0x4b, 0x90, 0xa8, 0xa2, 0x13, 0x52, 0xee, 0xe0, 0x36, 0x76, 0x8c, 0x16, 0x5c, 0x03,
	0x73, 0xc4, 0x24, 0x2d, 0x44, 0xf5, 0xc6, 0x34, 0xf6, 0x02, 0xd3, 0x20, 0xde, 0x40, 0x4e, 0xbd,
	0x63, 0xb2, 0xb9, 0x50, 0x4d, 0x9a, 0x3f, 0x04, 0xaf, 0x83, 0x84, 0xe9, 0xe8, 0xe8, 0xa4, 0x8d,
	0x1a, 0x26, 0x41, 0x8d, 0x64, 0x24, 0x2d, 0x6c, 0x2f, 0x6a, 0x71, 0xd3, 0x51, 0xbd, 0xd0, 0xde,
	0xca, 0xfb, 0x97, 0xb2, 0xf0, 0x9f, 0x7f, 0xdc, 0x5a, 0xd8, 0xc7, 0x36, 0x41, 0x36, 0x51, 0xde,
	0x0a, 0x60, 0x21, 0x8f, 0xda, 0xd8, 0x31, 0x09, 0xfc, 0x36, 0x88, 0xb7, 0xb9, 0x06, 0xdd, 0x6c,
	0x50, 0xf6, 0x68, 0x6e, 0xfd, 0x62, 0x20, 0x43, 0xa6, 0xdb, 0x37, 0xa8, 0x68, 0xc0, 0x7b, 0x2b,
	0x34, 0xe0, 0x16, 0x88, 0x35, 0x18, 0x06, 0xee, 0x70, 0x61, 0xa3, 0x00, 0x74, 0xc0, 0xbc, 0x61,
	0xe1, 0xae, 0x4d, 0x92, 0x91, 0x74, 0x64, 0x3b, 0xbe, 0xbb, 0xe9, 0xf9, 0xef, 0x6e, 0xaa, 0xe1,
	0x02, 0xec, 0x63, 0xd3, 0xce, 0x7d, 0xdf, 0xb5, 0xf8, 0xaf, 0x6f, 0xe5, 0xef, 0x7c, 0x82, 0xc5,
	0x2e, 0x80, 0xa3, 0x71, 0xaa, 0xbd, 0xc5, 0x67, 0x2f, 0xe5, 0xd0, 0xfb, 0x97, 0x72, 0x48, 0xf9,
	0xcb, 0x02, 0x58, 0x1c, 0x5a, 0xfb, 0xad, 0xcb, 0xa6, 0xb8, 0xfa, 0x61, 0x20, 0x87, 0xcd, 0xc6,
	0xc5, 0x40, 0x8e, 0xb1, 0x89, 0x8e, 0xcf, 0xef, 0x2e, 0x58, 0xa8, 0x33, 0xbf, 0xe8, 0xec, 0xe2,
	0xbb, 0x6b, 0x19, 0xb6, 0x17, 0x33, 0xde, 0x5e, 0xcc, 0x64, 0xed, 0xd3, 0x5c, 0xfc, 0x5f, 0x23,
	0x63, 0x35, 0xaf, 0x02, 0xd6, 0xc0, 0xbc, 0x43, 0x0c, 0xd2, 0x75, 0xe8, 0x7a, 0x2c, 0xef, 0x2a,
	0x97, 0x6d, 0x3f, 0x4f, 0x60, 0x85, 0x66, 0xe6, 0x52, 0x17, 0x03, 0x79, 0x7d, 0xcc, 0x74, 0x06,
	0xa2, 0x68, 0x1c, 0x0d, 0xb6, 0x01, 0x7c, 0x6c, 0xda, 0x46, 0x4b, 0x27, 0x46, 0xab, 0x75, 0xaa,
	0x77, 0x90, 0xd3, 0x6d, 0x91, 0x64, 0x94, 0xea, 0x93, 0x2f, 0xe3, 0xa8, 0xba, 0x79, 0x1a, 0x4d,
	0xcb, 0x5d, 0x77, 0x8d, 0xbe, 0x18, 0xc8, 0x9b, 0x8c, 0x64, 0x12, 0x48, 0xd1, 0x44, 0x1a, 0xf4,
	0x15, 0xc1, 0x9f, 0x82, 0xb8, 0xd3, 0x3d, 0xb4, 0x4c, 0xa2, 0xbb, 0x27, 0x2f, 0x39, 0x47, 0xa9,
	0x52, 0x13, 0x56, 0x54, 0xbd, 0x63, 0x99, 0x93, 0x38, 0x0b, 0xdf, 0x3f, 0xbe, 0x62, 0xe5, 0xf9,
	0x5b, 0x59, 0xd0, 0x00, 0x8b, 0xb8, 0x05, 0xd0, 0x04, 0x22, 0xdf, 0x32, 0x3a, 0xb2, 0x1b, 0x8c,
	0x61, 0x7e, 0x2a, 0xc3, 0x57, 0x39, 0xc3, 0x06, 0x63, 0x18, 0x47, 0x60, 0x34, 0xcb, 0x3c, 0xac,
	0xda, 0x0d, 0x4a, 0xf5, 0x42, 0x00, 0x4b, 0x04, 0x13, 0xa3, 0xa5, 0xf3, 0x81, 0xe4, 0xc2, 0xb4,
	0x8d, 0xf9, 0x90, 0xf3, 0xac, 0x31, 0x9e, 0x40, 0xb5, 0x32, 0xd3, 0x86, 0x4d, 0x50, 0x2c, 0xef,
	0x08, 0xb6, 0xc0, 0x95, 0x63, 0x4c, 0x4c, 0xbb, 0xe9, 0x2e, 0x77, 0x87, 0x1b, 0xbd, 0x38, 0xd5,
	0x86, 0xaf, 0x71, 0x79, 0x49, 0x26, 0x6f, 0x02, 0x82, 0xf9, 0xb0, 0xc2, 0xe2, 0x15, 0x37, 0x4c,
	0x8d, 0x78, 0x0c, 0x78, 0x68, 0x64, 0x79, 0x6c, 0x2a, 0x97, 0xc2, 0xb9, 0xd6, 0x03, 0x5c, 0x41,
	0xc7, 0x97, 0x58, 0xd4, 0x33, 0x7c, 0xbc, 0x31, 0x81, 0xc9, 0xc6, 0x14, 0x75, 0x1b, 0x93, 0xf2,
	0x2c, 0x02, 0xe2, 0xfe, 0x1d, 0x57, 0x06, 0x91, 0x53, 0xe4, 0xb0, 0x3e, 0x98, 0xfb, 0xde, 0x0c,
	0xfd, 0xb7, 0x60, 0x13, 0xcd, 0x85, 0x82, 0x0f, 0xc1, 0x82, 0x71, 0xe8, 0x10, 0xc3, 0xe4, 0x1d,
	0x74, 0x66, 0x54, 0x0f, 0x0e, 0x16, 0x41, 0xd8, 0xc6, 0xf4, 0x8c, 0xcf, 0x0e, 0x1a, 0xb6, 0x31,
	0x7c, 0x0a, 0x12, 0x36, 0xd6, 0x9f, 0x9a, 0xe4, 0x48, 0x3f, 0x46, 0x04, 0xd3, 0x93, 0x1d, 0xcb,
	0xdd, 0x9f, 0x0d, 0xf9, 0x62, 0x20, 0xaf, 0xb2, 0x75, 0xf3, 0x63, 0x2b, 0x1a, 0xb0, 0xf1, 0x03,
	0x93, 0x1c, 0xd5, 0x10, 0xc1, 0x7c, 0x29, 0xce, 0x05, 0x10, 0x75, 0x2f, 0xc5, 0x4f, 0xbf, 0x15,
	0xd6, 0xc0, 0xdc, 0x31, 0x26, 0xc8, 0xbb, 0x11, 0xd8, 0x0b, 0xdc, 0x1b, 0xde, 0xc6, 0x91, 0x2f,
	0x72, 0x1b, 0xe7, 0xc2, 0x49, 0x61, 0x78, 0x23, 0x1f, 0x80, 0x05, 0xf6, 0xe4, 0x24, 0xa3, 0xf4,
	0xc4, 0x7e, 0xfd, 0xb2, 0xe2, 0xc9, 0x4f, 0x80, 0x5c, 0xd4, 0x75, 0x4d, 0xf3, 0x8a, 0xf7, 0x16,
	0x5f, 0x78, 0x97, 0xc3, 0x9f, 0xa2, 0x60, 0x89, 0x9f, 0xbd, 0xb2, 0xd1, 0x31, 0x2c, 0x07, 0xfe,
	0x4d, 0x00, 0x71, 0xcb, 0xb4, 0x87, 0xad, 0x41, 0x98, 0xd6, 0x1a, 0xb0, 0x8b, 0xfd, 0x61, 0x20,
	0x5f, 0xf5, 0x55, 0xdd, 0xc4, 0x96, 0x49, 0x90, 0xd5, 0x26, 0xa7, 0x23, 0x9f, 0x7c, 0xc3, 0xb3,
	0x75, 0x0c, 0x60, 0x99, 0xb6, 0xd7, 0x2f, 0x7e, 0x27, 0x00, 0x68, 0x19, 0x27, 0x1e, 0xb0, 0xde,
	0x46, 0x1d, 0x13, 0x37, 0xf8, 0x2d, 0xb5, 0x39, 0x71, 0x8a, 0xf3, 0xfc, 0x8b, 0x2a, 0xa7, 0x72,
	0xd1, 0x5b, 0x93, 0xc5, 0x01, 0xed, 0xfc, 0x7e, 0x98, 0xcc, 0x52, 0x5e, 0xb8, 0xe7, 0x5c, 0xb4,
	0x8c, 0x13, 0xcf, 0x3e, 0x1a, 0x86, 0xff, 0x15, 0x00, 0x35, 0x62, 0x78, 0xd8, 0x87, 0x46, 0x4e,
	0xbd, 0xfc, 0x7f, 0x23, 0x70, 0x51, 0xf2, 0xa5, 0x00, 0x01, 0x5d, 0x5b, 0x23, 0x4f, 0x27, 0x12,
	0x67, 0x73, 0x77, 0xd5, 0x32, 0xed, 0x61, 0x5b, 0xe2, 0x73, 0x53, 0xfe, 0x1e, 0x06, 0x89, 0x1a,
	0x6d, 0x69, 0x7c, 0x97, 0xfc, 0x0a, 0xf0, 0x16, 0xe7, 0x39, 0x2e, 0x4c, 0x73, 0xfc, 0x2e, 0x9f,
	0xdc, 0x46, 0xa0, 0x2e, 0x30, 0xa9, 0xb5, 0x40, 0x47, 0xf5, 0xfb, 0x9c, 0x60, 0x31, 0xee, 0xf1,
	0x1f, 0x04, 0xb0, 0x31, 0x9a, 0x75, 0x50, 0xc7, 0xd4, 0x95, 0x2f, 0x71, 0x1d, 0xd7, 0x3f, 0x82,
	0x10, 0x50, 0x24, 0x31, 0x45, 0x1f, 0x49, 0x65, 0xda, 0xae, 0x0e, 0x47, 0x6b, 0x3e, 0x91, 0xca,
	0x9f, 0xe7, 0x78, 0x2b, 0xe7, 0x8e, 0x3d, 0x01, 0xf3, 0xbf, 0xe8, 0xe2, 0x4e, 0xd7, 0xa2, 0x56,
	0x25, 0x72, 0xda, 0x6c, 0x5f, 0xd3, 0x1f, 0x06, 0xb2, 0xc8, 0xf0, 0x46, 0x82, 0x35, 0xce, 0x00,
	0x1d, 0x10, 0x23, 0x47, 0x1d, 0xe4, 0x1c, 0xe1, 0x16, 0x73, 0x24, 0x31, 0x53, 0xdf, 0x64, 0x74,
	0xab, 0x43, 0x48, 0x1f, 0xe3, 0x88, 0x07, 0xfe, 0x5e, 0x00, 0xcb, 0x6e, 0x33, 0xd5, 0x47, 0xd4,
	0x11, 0x4a, 0xed, 0xcc, 0x4c, 0x9d, 0x0c, 0xe2, 0x06, 0x96, 0xe8, 0x2a, 0xdf, 0x34, 0x81, 0x0c,
	0x45, 0x5b, 0x72, 0x03, 0xd5, 0xa1, 0xb8, 0xdf, 0x0a, 0x40, 0x1c, 0xad, 0x22, 0x5f, 0x88, 0x28,
	0x95, 0xf7, 0xb3, 0x99, 0xe5, 0xa5, 0xc6, 0x91, 0x7d, 0x06, 0xad, 0x0c, 0xc7, 0x7e, 0xcc, 0xd6,
	0xe6, 0xb9, 0x00, 0x56, 0x47, 0xf9, 0x23, 0xaf, 0xe6, 0xa8, 0x18, 0x7d, 0x66, 0x31, 0xd7, 0x2e,
	0x01, 0xf7, 0xe9, 0x81, 0xc3, 0xe1, 0xa1, 0x39, 0x37, 0x3e, 0x13, 0x00, 0xf0, 0xfd, 0x5e, 0xbc,
	0x09, 0x36, 0x6a, 0xa5, 0xaa, 0xaa, 0x97, 0xca, 0xd5, 0x42, 0xa9, 0xa8, 0xdf, 0x2f, 0x56, 0xca,
	0xea, 0x7e, 0xe1, 0xa0, 0xa0, 0xe6, 0xc5, 0x50, 0x6a, 0xa5, 0xd7, 0x4f, 0xc7, 0x59, 0xa2, 0xea,
	0x02, 0x42, 0x05, 0xac, 0xf8, 0xb3, 0x1f, 0xa9, 0x15, 0x51, 0x48, 0x2d, 0xf5, 0xfa, 0xe9, 0x18,
	0xcb, 0x7a, 0x84, 0x1c, 0x78, 0x03, 0xac, 0xfa, 0x73, 0xb2, 0xb9, 0x4a, 0x35, 0x5b, 0x28, 0x8a,
	0xe1, 0xd4, 0x95, 0x5e, 0x3f, 0xbd, 0xc4, 0xf2, 0xb2, 0xfc, 0x33, 0x22, 0x0d, 0x96, 0xfd, 0xb9,
	0xc5, 0x92, 0x18, 0x49, 0x25, 0x7a, 0xfd, 0xf4, 0x22, 0x4b, 0x2b, 0x62, 0xb8, 0x0b, 0x92, 0xc1,
	0x0c, 0xfd, 0x41, 0xa1, 0xfa, 0x43, 0xbd, 0xa6, 0x56, 0x4b, 0x62, 0x34, 0xb5, 0xd6, 0xeb, 0xa7,
	0x45, 0x2f, 0xd7, 0xbb, 0xd3, 0x53, 0xd1, 0x67, 0x7f, 0x94, 0x42, 0x37, 0xfe, 0x1d, 0x06, 0xcb,
	0xc1, 0x5f, 0x1a, 0x30, 0x03, 0xbe, 0x52, 0xd6, 0x4a, 0xe5, 0x52, 0x25, 0x7b, 0x4f, 0xaf, 0x54,
	0xb3, 0xd5, 0xfb, 0x95, 0xb1, 0x09, 0xd3, 0xa9, 0xb0, 0xe4, 0xa2, 0xd9, 0x82, 0x77, 0x81, 0x34,
	0x9e, 0x9f, 0x57, 0xcb, 0xa5, 0x4a, 0xa1, 0xaa, 0x97, 0x55, 0xad, 0x50, 0xca, 0x8b, 0x42, 0x6a,
	0xa3, 0xd7, 0x4f, 0xaf, 0xb2, 0x92, 0xe0, 0xe5, 0xf0, 0x5d, 0x70, 0x6d, 0xbc, 0xb8, 0x56, 0xaa,
	0x16, 0x8a, 0x3f, 0xf0, 0x6a, 0xc3, 0xa9, 0xf5, 0x5e, 0x3f, 0x0d, 0x59, 0xad, 0xbf, 0x9d, 0xc0,
	0x9b, 0x60, 0x7d, 0xbc, 0xb4, 0x9c, 0xad, 0x54, 0xd4, 0xbc, 0x18, 0x49, 0x89, 0xbd, 0x7e, 0x3a,
	0xc1, 0x6a, 0xca, 0x86, 0xe3, 0xa0, 0x06, 0xfc, 0x06, 0x48, 0x8e, 0x67, 0x6b, 0xea, 0x8f, 0xd4,
	0xfd, 0xaa, 0x9a, 0x17, 0xa3, 0x29, 0xd8, 0xeb, 0xa7, 0x97, 0x59, 0xbe, 0x86, 0x9e, 0xa0, 0x3a,
	0x41, 0x97, 0xe2, 0x1f, 0x64, 0x0b, 0xf7, 0xd4, 0xbc, 0x38, 0xe7, 0xc7, 0x3f, 0x30, 0xcc, 0x16,
	0x6a, 0x30, 0x3b, 0x73, 0x3f, 0x7f, 0xf5, 0x4e, 0x0a, 0xbd, 0x79, 0x27, 0x85, 0x7e, 0x7d, 0x26,
	0x85, 0x5e, 0x9d, 0x49, 0xc2, 0xeb, 0x33, 0x49, 0xf8, 0xff, 0x99, 0x24, 0x3c, 0x3f, 0x97, 0x42,
	0xaf, 0xcf, 0xa5, 0xd0, 0x9b, 0x73, 0x29, 0xf4, 0x93, 0x2f, 0x77, 0x15, 0x9d, 0xd0, 0x3f, 0x67,
	0xe8, 0x86, 0x3e, 0x9c, 0xa7, 0xa9, 0xdf, 0xfc, 0x3c, 0x00, 0x00, 0xff, 0xff, 0x02, 0xc6, 0x46,
	0x62, 0xb7, 0x11, 0x00, 0x00,
}

func (this *TextProposal) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *Proposal) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *TallyResult) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (m *WeightedVoteOption) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *WeightedVoteOption) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *WeightedVoteOption) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TextProposal) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TextProposal) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TextProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Deposit) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Deposit) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Deposit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Proposal) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Proposal) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Proposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TallyResult) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TallyResult) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *TallyResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Vote) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Vote) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Vote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DepositParams) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DepositParams) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DepositParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *VotingParams) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *VotingParams) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *VotingParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TallyParams) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TallyParams) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *TallyParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintGov(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *WeightedVoteOption) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TextProposal) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Deposit) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Proposal) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TallyResult) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Vote) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DepositParams) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *VotingParams) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TallyParams) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovGov(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozGov(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *WeightedVoteOption) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TextProposal) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Deposit) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Proposal) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TallyResult) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Vote) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *DepositParams) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *VotingParams) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TallyParams) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipGov(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthGov        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGov          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGov = fmt.Errorf("proto: unexpected end of group")
)
