// Moved from sei-iavl/proto/changeset.pb.go
// Originally generated by protoc-gen-gogo from iavl/changeset.proto

package proto

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

type KVPair struct {
	Delete bool   `protobuf:"varint,1,opt,name=delete,proto3" json:"delete,omitempty"`
	Key    []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value  []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *KVPair) Reset()                    { _ = "STUB: not implemented"; return }
func (m *KVPair) String() string            { _ = "STUB: not implemented"; return "" }
func (*KVPair) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*KVPair) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *KVPair) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *KVPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *KVPair) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *KVPair) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *KVPair) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_KVPair proto.InternalMessageInfo

func (m *KVPair) GetDelete() bool { _ = "STUB: not implemented"; return false }

func (m *KVPair) GetKey() []byte { _ = "STUB: not implemented"; return nil }

func (m *KVPair) GetValue() []byte { _ = "STUB: not implemented"; return nil }

type ChangeSet struct {
	Pairs []*KVPair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
}

func (m *ChangeSet) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ChangeSet) String() string            { _ = "STUB: not implemented"; return "" }
func (*ChangeSet) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ChangeSet) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ChangeSet) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ChangeSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ChangeSet) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ChangeSet) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ChangeSet) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ChangeSet proto.InternalMessageInfo

func (m *ChangeSet) GetPairs() []*KVPair { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*KVPair)(nil), "iavl.KVPair")
	proto.RegisterType((*ChangeSet)(nil), "iavl.ChangeSet")
}

var fileDescriptor_changeset = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc9, 0x4c, 0x2c, 0xcb,
	0xd1, 0x4f, 0xce, 0x48, 0xcc, 0x4b, 0x4f, 0x2d, 0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x01, 0x89, 0x2a, 0x79, 0x70, 0xb1, 0x79, 0x87, 0x05, 0x24, 0x66, 0x16, 0x09, 0x89,
	0x71, 0xb1, 0xa5, 0xa4, 0xe6, 0xa4, 0x96, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x04, 0x41,
	0x79, 0x42, 0x02, 0x5c, 0xcc, 0xd9, 0xa9, 0x95, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x20,
	0xa6, 0x90, 0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69, 0xaa, 0x04, 0x33, 0x58, 0x0c, 0xc2, 0x51,
	0xd2, 0xe7, 0xe2, 0x74, 0x06, 0x5b, 0x11, 0x9c, 0x5a, 0x22, 0xa4, 0xc4, 0xc5, 0x5a, 0x90, 0x98,
	0x59, 0x54, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0xc4, 0xa3, 0x07, 0xb2, 0x4c, 0x0f, 0x62,
	0x53, 0x10, 0x44, 0xca, 0xc9, 0xeb, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c,
	0x92, 0x63, 0x9c, 0xf0, 0x58, 0x8e, 0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2,
	0x0c, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x8b, 0x53, 0x33, 0x75,
	0xc1, 0x0e, 0x4e, 0xce, 0xcf, 0x01, 0x73, 0x92, 0x33, 0x12, 0x33, 0xf3, 0xc0, 0x2c, 0xb0, 0xb7,
	0xc0, 0x72, 0x49, 0x6c, 0x60, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xbd, 0x58, 0xe8,
	0xeb, 0x00, 0x00, 0x00,
}

func (m *KVPair) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *KVPair) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *KVPair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ChangeSet) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *ChangeSet) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ChangeSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintChangeset(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *KVPair) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ChangeSet) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovChangeset(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *KVPair) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ChangeSet) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipChangeset(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthChangeset        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowChangeset          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupChangeset = fmt.Errorf("proto: unexpected end of group")
)
