// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/base/kv/v1beta1/kv.proto

package kv

import (
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Pairs defines a repeated slice of Pair objects.
type Pairs struct {
	Pairs []Pair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs"`
}

func (m *Pairs) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Pairs) String() string            { _ = "STUB: not implemented"; return "" }
func (*Pairs) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Pairs) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Pairs) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Pairs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Pairs) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Pairs) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Pairs) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Pairs proto.InternalMessageInfo

func (m *Pairs) GetPairs() []Pair { _ = "STUB: not implemented"; return nil }

// Pair defines a key/value bytes tuple.
type Pair struct {
	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Pair) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Pair) String() string            { _ = "STUB: not implemented"; return "" }
func (*Pair) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Pair) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Pair) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Pair) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Pair) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Pair) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetKey() []byte { _ = "STUB: not implemented"; return nil }

func (m *Pair) GetValue() []byte { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*Pairs)(nil), "cosmos.base.kv.v1beta1.Pairs")
	proto.RegisterType((*Pair)(nil), "cosmos.base.kv.v1beta1.Pair")
}

func init() { proto.RegisterFile("cosmos/base/kv/v1beta1/kv.proto", fileDescriptor_a44e87fe7182bb73) }

var fileDescriptor_a44e87fe7182bb73 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0xce, 0x2f, 0xce,
	0xcd, 0x2f, 0xd6, 0x4f, 0x4a, 0x2c, 0x4e, 0xd5, 0xcf, 0x2e, 0xd3, 0x2f, 0x33, 0x4c, 0x4a, 0x2d,
	0x49, 0x34, 0xd4, 0xcf, 0x2e, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x83, 0x28, 0xd0,
	0x03, 0x29, 0xd0, 0xcb, 0x2e, 0xd3, 0x83, 0x2a, 0x90, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x2b,
	0xd1, 0x07, 0xb1, 0x20, 0xaa, 0x95, 0x1c, 0xb9, 0x58, 0x03, 0x12, 0x33, 0x8b, 0x8a, 0x85, 0x2c,
	0xb8, 0x58, 0x0b, 0x40, 0x0c, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x19, 0x3d, 0xec, 0xc6,
	0xe8, 0x81, 0x54, 0x3b, 0xb1, 0x9c, 0xb8, 0x27, 0xcf, 0x10, 0x04, 0xd1, 0xa0, 0xa4, 0xc7, 0xc5,
	0x02, 0x12, 0x14, 0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09,
	0x02, 0x31, 0x85, 0x44, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x98, 0xc0, 0x62, 0x10,
	0x8e, 0x93, 0xff, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38,
	0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0x99, 0xa6, 0x67,
	0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x17, 0xa7, 0x66, 0xea, 0x82, 0x9d, 0x98,
	0x9c, 0x9f, 0x03, 0xe6, 0x24, 0x67, 0x24, 0x66, 0xe6, 0x41, 0x58, 0x90, 0x10, 0x28, 0xa9, 0x2c,
	0x48, 0x2d, 0xd6, 0xcf, 0x2e, 0x4b, 0x62, 0x03, 0xab, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xf1, 0x07, 0xdb, 0xfc, 0x1b, 0x01, 0x00, 0x00,
}

func (m *Pairs) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Pairs) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Pairs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Pair) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Pair) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Pair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintKv(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *Pairs) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Pair) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovKv(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozKv(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Pairs) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Pair) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipKv(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthKv        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowKv          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupKv = fmt.Errorf("proto: unexpected end of group")
)
