// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/params/types/types.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_sei_protocol_sei_chain_sei_cosmos_types "github.com/sei-protocol/sei-chain/sei-cosmos/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Defines fee params that are controlled through governance
type FeesParams struct {
	GlobalMinimumGasPrices github_com_sei_protocol_sei_chain_sei_cosmos_types.DecCoins `protobuf:"bytes,1,rep,name=global_minimum_gas_prices,json=globalMinimumGasPrices,proto3,castrepeated=github.com/sei-protocol/sei-chain/sei-cosmos/types.DecCoins" json:"global_minimum_gas_prices"`
	AllowedFeeDenoms       []string                                                    `protobuf:"bytes,2,rep,name=allowed_fee_denoms,json=allowedFeeDenoms,proto3" json:"allowed_fee_denoms,omitempty"`
}

func (m *FeesParams) Reset()                    { _ = "STUB: not implemented"; return }
func (m *FeesParams) String() string            { _ = "STUB: not implemented"; return "" }
func (*FeesParams) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*FeesParams) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *FeesParams) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *FeesParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *FeesParams) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *FeesParams) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *FeesParams) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_FeesParams proto.InternalMessageInfo

func (m *FeesParams) GetGlobalMinimumGasPrices() github_com_sei_protocol_sei_chain_sei_cosmos_types.DecCoins {
	_ = "STUB: not implemented"
	return *new(github_com_sei_protocol_sei_chain_sei_cosmos_types.DecCoins)
}

func (m *FeesParams) GetAllowedFeeDenoms() []string { _ = "STUB: not implemented"; return nil }

type CosmosGasParams struct {
	CosmosGasMultiplierNumerator   uint64 `protobuf:"varint,1,opt,name=cosmos_gas_multiplier_numerator,json=cosmosGasMultiplierNumerator,proto3" json:"cosmos_gas_multiplier_numerator,string,omitempty"`
	CosmosGasMultiplierDenominator uint64 `protobuf:"varint,2,opt,name=cosmos_gas_multiplier_denominator,json=cosmosGasMultiplierDenominator,proto3" json:"cosmos_gas_multiplier_denominator,string,omitempty"`
}

func (m *CosmosGasParams) Reset()                    { _ = "STUB: not implemented"; return }
func (m *CosmosGasParams) String() string            { _ = "STUB: not implemented"; return "" }
func (*CosmosGasParams) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*CosmosGasParams) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *CosmosGasParams) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CosmosGasParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CosmosGasParams) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *CosmosGasParams) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *CosmosGasParams) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_CosmosGasParams proto.InternalMessageInfo

func (m *CosmosGasParams) GetCosmosGasMultiplierNumerator() uint64 {
	_ = "STUB: not implemented"
	return 0
}

func (m *CosmosGasParams) GetCosmosGasMultiplierDenominator() uint64 {
	_ = "STUB: not implemented"
	return 0
}

type GenesisState struct {
	FeesParams      FeesParams      `protobuf:"bytes,1,opt,name=fees_params,json=feesParams,proto3" json:"fees_params"`
	CosmosGasParams CosmosGasParams `protobuf:"bytes,2,opt,name=cosmos_gas_params,json=cosmosGasParams,proto3" json:"cosmos_gas_params"`
}

func (m *GenesisState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *GenesisState) String() string            { _ = "STUB: not implemented"; return "" }
func (*GenesisState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*GenesisState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *GenesisState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GenesisState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *GenesisState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *GenesisState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetFeesParams() FeesParams {
	_ = "STUB: not implemented"
	return *new(FeesParams)
}

func (m *GenesisState) GetCosmosGasParams() CosmosGasParams {
	_ = "STUB: not implemented"
	return *new(CosmosGasParams)
}

func init() {
	proto.RegisterType((*FeesParams)(nil), "cosmos.params.v1beta1.FeesParams")
	proto.RegisterType((*CosmosGasParams)(nil), "cosmos.params.v1beta1.CosmosGasParams")
	proto.RegisterType((*GenesisState)(nil), "cosmos.params.v1beta1.GenesisState")
}

func init() { proto.RegisterFile("cosmos/params/types/types.proto", fileDescriptor_56d782f42fecdb16) }

var fileDescriptor_56d782f42fecdb16 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x31, 0x6f, 0x13, 0x31,
	0x14, 0x8e, 0xd3, 0x0a, 0x09, 0x07, 0xa9, 0x70, 0x02, 0x14, 0xaa, 0xca, 0x97, 0x66, 0x40, 0x19,
	0xc2, 0x1d, 0x0d, 0x88, 0x85, 0x2d, 0x89, 0x5a, 0x96, 0xa2, 0x2a, 0x2c, 0xc0, 0x72, 0xf2, 0xb9,
	0x2f, 0x57, 0x4b, 0x67, 0xfb, 0x74, 0x76, 0x80, 0x8a, 0x89, 0x7f, 0x80, 0x98, 0xf9, 0x01, 0x88,
	0x91, 0x5f, 0xd1, 0xb1, 0x23, 0x2c, 0x01, 0x25, 0x5b, 0x7f, 0x05, 0x8a, 0xed, 0x23, 0x50, 0x82,
	0x22, 0x96, 0xd3, 0xbb, 0x77, 0xdf, 0xfb, 0xbe, 0xef, 0x9d, 0x3f, 0xe3, 0x90, 0x29, 0x2d, 0x94,
	0x8e, 0x0b, 0x5a, 0x52, 0xa1, 0x63, 0x73, 0x5a, 0x80, 0x7f, 0x46, 0x45, 0xa9, 0x8c, 0x0a, 0x6e,
	0x39, 0x40, 0xe4, 0x00, 0xd1, 0xab, 0xbd, 0x14, 0x0c, 0xdd, 0xdb, 0x26, 0x7e, 0x2e, 0xa5, 0x1a,
	0x62, 0xdf, 0x8c, 0x99, 0xe2, 0xd2, 0x8d, 0x6d, 0xdf, 0xcc, 0x54, 0xa6, 0x6c, 0x19, 0x2f, 0x2a,
	0xd7, 0x6d, 0x7f, 0x43, 0x18, 0xef, 0x03, 0xe8, 0x23, 0x4b, 0x16, 0x7c, 0x44, 0xf8, 0x4e, 0x96,
	0xab, 0x94, 0xe6, 0x89, 0xe0, 0x92, 0x8b, 0x89, 0x48, 0x32, 0xaa, 0x93, 0xa2, 0xe4, 0x0c, 0x74,
	0x13, 0xb5, 0x36, 0x3a, 0x8d, 0xde, 0x4e, 0xe4, 0x0d, 0x2c, 0x94, 0x2a, 0xf9, 0x68, 0x08, 0x6c,
	0xa0, 0xb8, 0xec, 0x0f, 0xce, 0xa6, 0x61, 0xed, 0xf3, 0xf7, 0xf0, 0x71, 0xc6, 0xcd, 0xc9, 0x24,
	0x8d, 0x98, 0x12, 0xb1, 0x06, 0x7e, 0xcf, 0xca, 0x31, 0x95, 0xdb, 0x17, 0x76, 0x42, 0xb9, 0x74,
	0x95, 0x33, 0xed, 0xf6, 0xf3, 0x1c, 0x7a, 0x74, 0xdb, 0x79, 0x38, 0x74, 0x16, 0x0e, 0xa8, 0x3e,
	0xb2, 0x06, 0x82, 0x2e, 0x0e, 0x68, 0x9e, 0xab, 0xd7, 0x70, 0x9c, 0x8c, 0x01, 0x92, 0x63, 0x90,
	0x4a, 0xe8, 0x66, 0xbd, 0xb5, 0xd1, 0xb9, 0x3a, 0xba, 0xee, 0xbf, 0xec, 0x03, 0x0c, 0x6d, 0xbf,
	0xfd, 0xa1, 0x8e, 0xb7, 0x06, 0x96, 0x7f, 0xc1, 0xe0, 0x16, 0x7c, 0x5b, 0xfd, 0x5f, 0xbb, 0x97,
	0x98, 0xe4, 0x86, 0x17, 0x39, 0x87, 0x32, 0x91, 0x13, 0x01, 0x25, 0x35, 0xaa, 0x6c, 0xa2, 0x16,
	0xea, 0x6c, 0xf6, 0x1f, 0x5e, 0x4c, 0xc3, 0xfb, 0x6b, 0xa0, 0x5d, 0x6d, 0x4a, 0x2e, 0xb3, 0xae,
	0x12, 0xdc, 0x80, 0x28, 0xcc, 0xe9, 0x68, 0x87, 0x55, 0x7a, 0x87, 0xbf, 0xf0, 0x4f, 0x2b, 0x78,
	0xf0, 0x0e, 0xe1, 0xdd, 0xd5, 0x94, 0x76, 0x13, 0x2e, 0xad, 0x7e, 0xdd, 0xea, 0x3f, 0xba, 0x98,
	0x86, 0xbd, 0xb5, 0xe0, 0xbf, 0x1d, 0x90, 0x15, 0x0e, 0x86, 0xcb, 0x81, 0xf6, 0x17, 0x84, 0xaf,
	0x1d, 0x80, 0x04, 0xcd, 0xf5, 0x33, 0x43, 0x0d, 0x04, 0x4f, 0x70, 0x63, 0x0c, 0xa0, 0x13, 0x17,
	0x27, 0xbb, 0x7d, 0xa3, 0xb7, 0x1b, 0xad, 0x0c, 0x59, 0xb4, 0x8c, 0x4a, 0x7f, 0x73, 0x71, 0xd0,
	0x23, 0x3c, 0x5e, 0x86, 0xe7, 0x39, 0xbe, 0xf1, 0x9b, 0x61, 0xcf, 0x57, 0xb7, 0x7c, 0x77, 0xff,
	0xc1, 0x77, 0xe9, 0x78, 0x3c, 0xe9, 0x16, 0xbb, 0xd4, 0x7e, 0xf1, 0x69, 0x46, 0xd0, 0xd9, 0x8c,
	0xa0, 0xf3, 0x19, 0x41, 0x3f, 0x66, 0x04, 0xbd, 0x9f, 0x93, 0xda, 0xf9, 0x9c, 0xd4, 0xbe, 0xce,
	0x49, 0xed, 0xe5, 0xff, 0x45, 0xed, 0xcd, 0x1f, 0x37, 0x2b, 0xbd, 0x62, 0xd1, 0x0f, 0x7e, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x56, 0x9c, 0x40, 0xbe, 0x77, 0x03, 0x00, 0x00,
}

func (this *FeesParams) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *CosmosGasParams) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *GenesisState) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (m *FeesParams) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *FeesParams) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *FeesParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CosmosGasParams) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CosmosGasParams) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CosmosGasParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *FeesParams) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CosmosGasParams) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *GenesisState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *FeesParams) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CosmosGasParams) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *GenesisState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipTypes(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
