// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/crypto/keys.proto

package crypto

import (
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PublicKey defines the keys available for use with Tendermint Validators
type PublicKey struct {
	// Types that are valid to be assigned to Sum:
	//
	//	*PublicKey_Ed25519
	Sum isPublicKey_Sum `protobuf_oneof:"sum"`
}

func (m *PublicKey) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PublicKey) String() string            { _ = "STUB: not implemented"; return "" }
func (*PublicKey) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PublicKey) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PublicKey) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PublicKey) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PublicKey) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PublicKey) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PublicKey proto.InternalMessageInfo

type isPublicKey_Sum interface {
	isPublicKey_Sum()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
	Compare(interface{}) int
}

type PublicKey_Ed25519 struct {
	Ed25519 []byte `protobuf:"bytes,1,opt,name=ed25519,proto3,oneof" json:"ed25519,omitempty"`
}

func (*PublicKey_Ed25519) isPublicKey_Sum() { _ = "STUB: not implemented"; return }

func (m *PublicKey) GetSum() isPublicKey_Sum {
	_ = "STUB: not implemented"
	return *new(isPublicKey_Sum)
}

func (m *PublicKey) GetEd25519() []byte { _ = "STUB: not implemented"; return nil }

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PublicKey) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*PublicKey)(nil), "tendermint.crypto.PublicKey")
}

func init() { proto.RegisterFile("tendermint/crypto/keys.proto", fileDescriptor_cb048658b234868c) }

var fileDescriptor_cb048658b234868c = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x49, 0xcd, 0x4b,
	0x49, 0x2d, 0xca, 0xcd, 0xcc, 0x2b, 0xd1, 0x4f, 0x2e, 0xaa, 0x2c, 0x28, 0xc9, 0xd7, 0xcf, 0x4e,
	0xad, 0x2c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x44, 0xc8, 0xea, 0x41, 0x64, 0xa5,
	0x44, 0xd2, 0xf3, 0xd3, 0xf3, 0xc1, 0xb2, 0xfa, 0x20, 0x16, 0x44, 0xa1, 0x52, 0x04, 0x17, 0x67,
	0x40, 0x69, 0x52, 0x4e, 0x66, 0xb2, 0x77, 0x6a, 0xa5, 0x90, 0x14, 0x17, 0x7b, 0x6a, 0x8a, 0x91,
	0xa9, 0xa9, 0xa1, 0xa5, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x8f, 0x07, 0x43, 0x10, 0x4c, 0xc0, 0x8a,
	0xe3, 0xc5, 0x02, 0x79, 0xc6, 0x17, 0x0b, 0xe5, 0x19, 0x9d, 0x58, 0xb9, 0x98, 0x8b, 0x4b, 0x73,
	0xbd, 0x58, 0x38, 0x98, 0x04, 0x98, 0xbd, 0x58, 0x38, 0x98, 0x05, 0x58, 0x82, 0x38, 0x8b, 0x53,
	0x93, 0x0b, 0x8c, 0x4c, 0xcd, 0xb2, 0x0d, 0x83, 0xd8, 0x8b, 0x8b, 0xc0, 0x1a, 0x9c, 0x92, 0x4e,
	0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18,
	0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0xca, 0x23, 0x3d, 0xb3, 0x24, 0xa3, 0x34,
	0x49, 0x2f, 0x39, 0x3f, 0x57, 0xbf, 0x38, 0x35, 0x53, 0x17, 0xec, 0x92, 0xe4, 0xfc, 0x1c, 0x30,
	0x27, 0x39, 0x23, 0x31, 0x33, 0x0f, 0xcc, 0x42, 0xf2, 0x20, 0xc4, 0xd9, 0x18, 0x3e, 0x4e, 0x62,
	0x03, 0x4b, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x14, 0x21, 0xf4, 0xf3, 0x0d, 0x01, 0x00,
	0x00,
}

func (this *PublicKey) Compare(that interface{}) int { _ = "STUB: not implemented"; return 0 }

func (this *PublicKey_Ed25519) Compare(that interface{}) int { _ = "STUB: not implemented"; return 0 }

func (this *PublicKey) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *PublicKey_Ed25519) Equal(that interface{}) bool {
	_ = "STUB: not implemented"
	return false
}

func (m *PublicKey) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *PublicKey) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *PublicKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PublicKey_Ed25519) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PublicKey_Ed25519) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintKeys(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *PublicKey) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PublicKey_Ed25519) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovKeys(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozKeys(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PublicKey) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipKeys(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthKeys        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowKeys          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupKeys = fmt.Errorf("proto: unexpected end of group")
)
