// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/staking/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	query "github.com/sei-protocol/sei-chain/sei-cosmos/types/query"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryValidatorsRequest is request type for Query/Validators RPC method.
type QueryValidatorsRequest struct {
	// status enables to query for validators matching a given status.
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryValidatorsRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryValidatorsRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryValidatorsRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryValidatorsRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorsRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryValidatorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorsRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryValidatorsRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryValidatorsRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryValidatorsRequest proto.InternalMessageInfo

func (m *QueryValidatorsRequest) GetStatus() string { _ = "STUB: not implemented"; return "" }

func (m *QueryValidatorsRequest) GetPagination() *query.PageRequest {
	_ = "STUB: not implemented"
	return nil
}

// QueryValidatorsResponse is response type for the Query/Validators RPC method
type QueryValidatorsResponse struct {
	// validators contains all the queried validators.
	Validators []Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryValidatorsResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryValidatorsResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryValidatorsResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryValidatorsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorsResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryValidatorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorsResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryValidatorsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryValidatorsResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryValidatorsResponse proto.InternalMessageInfo

func (m *QueryValidatorsResponse) GetValidators() []Validator {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryValidatorsResponse) GetPagination() *query.PageResponse {
	_ = "STUB: not implemented"
	return nil
}

// QueryValidatorRequest is response type for the Query/Validator RPC method
type QueryValidatorRequest struct {
	// validator_addr defines the validator address to query for.
	ValidatorAddr string `protobuf:"bytes,1,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
}

func (m *QueryValidatorRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryValidatorRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryValidatorRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryValidatorRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryValidatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryValidatorRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryValidatorRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryValidatorRequest proto.InternalMessageInfo

func (m *QueryValidatorRequest) GetValidatorAddr() string { _ = "STUB: not implemented"; return "" }

// QueryValidatorResponse is response type for the Query/Validator RPC method
type QueryValidatorResponse struct {
	// validator defines the the validator info.
	Validator Validator `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator"`
}

func (m *QueryValidatorResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryValidatorResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryValidatorResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryValidatorResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryValidatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryValidatorResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryValidatorResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryValidatorResponse proto.InternalMessageInfo

func (m *QueryValidatorResponse) GetValidator() Validator {
	_ = "STUB: not implemented"
	return *new(Validator)
}

// QueryValidatorDelegationsRequest is request type for the
// Query/ValidatorDelegations RPC method
type QueryValidatorDelegationsRequest struct {
	// validator_addr defines the validator address to query for.
	ValidatorAddr string `protobuf:"bytes,1,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryValidatorDelegationsRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryValidatorDelegationsRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryValidatorDelegationsRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryValidatorDelegationsRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorDelegationsRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryValidatorDelegationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorDelegationsRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryValidatorDelegationsRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryValidatorDelegationsRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryValidatorDelegationsRequest proto.InternalMessageInfo

func (m *QueryValidatorDelegationsRequest) GetValidatorAddr() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *QueryValidatorDelegationsRequest) GetPagination() *query.PageRequest {
	_ = "STUB: not implemented"
	return nil
}

// QueryValidatorDelegationsResponse is response type for the
// Query/ValidatorDelegations RPC method
type QueryValidatorDelegationsResponse struct {
	DelegationResponses DelegationResponses `protobuf:"bytes,1,rep,name=delegation_responses,json=delegationResponses,proto3,castrepeated=DelegationResponses" json:"delegation_responses"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryValidatorDelegationsResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryValidatorDelegationsResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryValidatorDelegationsResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryValidatorDelegationsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorDelegationsResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryValidatorDelegationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorDelegationsResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryValidatorDelegationsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryValidatorDelegationsResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryValidatorDelegationsResponse proto.InternalMessageInfo

func (m *QueryValidatorDelegationsResponse) GetDelegationResponses() DelegationResponses {
	_ = "STUB: not implemented"
	return *new(DelegationResponses)
}

func (m *QueryValidatorDelegationsResponse) GetPagination() *query.PageResponse {
	_ = "STUB: not implemented"
	return nil
}

// QueryValidatorUnbondingDelegationsRequest is required type for the
// Query/ValidatorUnbondingDelegations RPC method
type QueryValidatorUnbondingDelegationsRequest struct {
	// validator_addr defines the validator address to query for.
	ValidatorAddr string `protobuf:"bytes,1,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryValidatorUnbondingDelegationsRequest) Reset() { _ = "STUB: not implemented"; return }

func (m *QueryValidatorUnbondingDelegationsRequest) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (*QueryValidatorUnbondingDelegationsRequest) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*QueryValidatorUnbondingDelegationsRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorUnbondingDelegationsRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryValidatorUnbondingDelegationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorUnbondingDelegationsRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryValidatorUnbondingDelegationsRequest) XXX_Size() int {
	_ = "STUB: not implemented"
	return 0
}

func (m *QueryValidatorUnbondingDelegationsRequest) XXX_DiscardUnknown() {
	_ = "STUB: not implemented"
	return
}

var xxx_messageInfo_QueryValidatorUnbondingDelegationsRequest proto.InternalMessageInfo

func (m *QueryValidatorUnbondingDelegationsRequest) GetValidatorAddr() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *QueryValidatorUnbondingDelegationsRequest) GetPagination() *query.PageRequest {
	_ = "STUB: not implemented"
	return nil
}

// QueryValidatorUnbondingDelegationsResponse is response type for the
// Query/ValidatorUnbondingDelegations RPC method.
type QueryValidatorUnbondingDelegationsResponse struct {
	UnbondingResponses []UnbondingDelegation `protobuf:"bytes,1,rep,name=unbonding_responses,json=unbondingResponses,proto3" json:"unbonding_responses"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryValidatorUnbondingDelegationsResponse) Reset() { _ = "STUB: not implemented"; return }

func (m *QueryValidatorUnbondingDelegationsResponse) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (*QueryValidatorUnbondingDelegationsResponse) ProtoMessage() {
	_ = "STUB: not implemented"
	return
}
func (*QueryValidatorUnbondingDelegationsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorUnbondingDelegationsResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryValidatorUnbondingDelegationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorUnbondingDelegationsResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryValidatorUnbondingDelegationsResponse) XXX_Size() int {
	_ = "STUB: not implemented"
	return 0
}

func (m *QueryValidatorUnbondingDelegationsResponse) XXX_DiscardUnknown() {
	_ = "STUB: not implemented"
	return
}

var xxx_messageInfo_QueryValidatorUnbondingDelegationsResponse proto.InternalMessageInfo

func (m *QueryValidatorUnbondingDelegationsResponse) GetUnbondingResponses() []UnbondingDelegation {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryValidatorUnbondingDelegationsResponse) GetPagination() *query.PageResponse {
	_ = "STUB: not implemented"
	return nil
}

// QueryDelegationRequest is request type for the Query/Delegation RPC method.
type QueryDelegationRequest struct {
	// delegator_addr defines the delegator address to query for.
	DelegatorAddr string `protobuf:"bytes,1,opt,name=delegator_addr,json=delegatorAddr,proto3" json:"delegator_addr,omitempty"`
	// validator_addr defines the validator address to query for.
	ValidatorAddr string `protobuf:"bytes,2,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
}

func (m *QueryDelegationRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryDelegationRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryDelegationRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryDelegationRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegationRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegationRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryDelegationRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryDelegationRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryDelegationRequest proto.InternalMessageInfo

// QueryDelegationResponse is response type for the Query/Delegation RPC method.
type QueryDelegationResponse struct {
	// delegation_responses defines the delegation info of a delegation.
	DelegationResponse *DelegationResponse `protobuf:"bytes,1,opt,name=delegation_response,json=delegationResponse,proto3" json:"delegation_response,omitempty"`
}

func (m *QueryDelegationResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryDelegationResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryDelegationResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryDelegationResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegationResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegationResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryDelegationResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryDelegationResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryDelegationResponse proto.InternalMessageInfo

func (m *QueryDelegationResponse) GetDelegationResponse() *DelegationResponse {
	_ = "STUB: not implemented"
	return nil
}

// QueryUnbondingDelegationRequest is request type for the
// Query/UnbondingDelegation RPC method.
type QueryUnbondingDelegationRequest struct {
	// delegator_addr defines the delegator address to query for.
	DelegatorAddr string `protobuf:"bytes,1,opt,name=delegator_addr,json=delegatorAddr,proto3" json:"delegator_addr,omitempty"`
	// validator_addr defines the validator address to query for.
	ValidatorAddr string `protobuf:"bytes,2,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
}

func (m *QueryUnbondingDelegationRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryUnbondingDelegationRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryUnbondingDelegationRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryUnbondingDelegationRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnbondingDelegationRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryUnbondingDelegationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnbondingDelegationRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryUnbondingDelegationRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryUnbondingDelegationRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryUnbondingDelegationRequest proto.InternalMessageInfo

// QueryDelegationResponse is response type for the Query/UnbondingDelegation
// RPC method.
type QueryUnbondingDelegationResponse struct {
	// unbond defines the unbonding information of a delegation.
	Unbond UnbondingDelegation `protobuf:"bytes,1,opt,name=unbond,proto3" json:"unbond"`
}

func (m *QueryUnbondingDelegationResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryUnbondingDelegationResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryUnbondingDelegationResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryUnbondingDelegationResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnbondingDelegationResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryUnbondingDelegationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnbondingDelegationResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryUnbondingDelegationResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryUnbondingDelegationResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryUnbondingDelegationResponse proto.InternalMessageInfo

func (m *QueryUnbondingDelegationResponse) GetUnbond() UnbondingDelegation {
	_ = "STUB: not implemented"
	return *new(UnbondingDelegation)
}

// QueryDelegatorDelegationsRequest is request type for the
// Query/DelegatorDelegations RPC method.
type QueryDelegatorDelegationsRequest struct {
	// delegator_addr defines the delegator address to query for.
	DelegatorAddr string `protobuf:"bytes,1,opt,name=delegator_addr,json=delegatorAddr,proto3" json:"delegator_addr,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDelegatorDelegationsRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryDelegatorDelegationsRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryDelegatorDelegationsRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryDelegatorDelegationsRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorDelegationsRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorDelegationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorDelegationsRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryDelegatorDelegationsRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryDelegatorDelegationsRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryDelegatorDelegationsRequest proto.InternalMessageInfo

// QueryDelegatorDelegationsResponse is response type for the
// Query/DelegatorDelegations RPC method.
type QueryDelegatorDelegationsResponse struct {
	// delegation_responses defines all the delegations' info of a delegator.
	DelegationResponses []DelegationResponse `protobuf:"bytes,1,rep,name=delegation_responses,json=delegationResponses,proto3" json:"delegation_responses"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDelegatorDelegationsResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryDelegatorDelegationsResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryDelegatorDelegationsResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryDelegatorDelegationsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorDelegationsResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorDelegationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorDelegationsResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryDelegatorDelegationsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryDelegatorDelegationsResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryDelegatorDelegationsResponse proto.InternalMessageInfo

func (m *QueryDelegatorDelegationsResponse) GetDelegationResponses() []DelegationResponse {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorDelegationsResponse) GetPagination() *query.PageResponse {
	_ = "STUB: not implemented"
	return nil
}

// QueryDelegatorUnbondingDelegationsRequest is request type for the
// Query/DelegatorUnbondingDelegations RPC method.
type QueryDelegatorUnbondingDelegationsRequest struct {
	// delegator_addr defines the delegator address to query for.
	DelegatorAddr string `protobuf:"bytes,1,opt,name=delegator_addr,json=delegatorAddr,proto3" json:"delegator_addr,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDelegatorUnbondingDelegationsRequest) Reset() { _ = "STUB: not implemented"; return }

func (m *QueryDelegatorUnbondingDelegationsRequest) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (*QueryDelegatorUnbondingDelegationsRequest) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*QueryDelegatorUnbondingDelegationsRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorUnbondingDelegationsRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorUnbondingDelegationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorUnbondingDelegationsRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryDelegatorUnbondingDelegationsRequest) XXX_Size() int {
	_ = "STUB: not implemented"
	return 0
}

func (m *QueryDelegatorUnbondingDelegationsRequest) XXX_DiscardUnknown() {
	_ = "STUB: not implemented"
	return
}

var xxx_messageInfo_QueryDelegatorUnbondingDelegationsRequest proto.InternalMessageInfo

// QueryUnbondingDelegatorDelegationsResponse is response type for the
// Query/UnbondingDelegatorDelegations RPC method.
type QueryDelegatorUnbondingDelegationsResponse struct {
	UnbondingResponses []UnbondingDelegation `protobuf:"bytes,1,rep,name=unbonding_responses,json=unbondingResponses,proto3" json:"unbonding_responses"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDelegatorUnbondingDelegationsResponse) Reset() { _ = "STUB: not implemented"; return }

func (m *QueryDelegatorUnbondingDelegationsResponse) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (*QueryDelegatorUnbondingDelegationsResponse) ProtoMessage() {
	_ = "STUB: not implemented"
	return
}
func (*QueryDelegatorUnbondingDelegationsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorUnbondingDelegationsResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorUnbondingDelegationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorUnbondingDelegationsResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryDelegatorUnbondingDelegationsResponse) XXX_Size() int {
	_ = "STUB: not implemented"
	return 0
}

func (m *QueryDelegatorUnbondingDelegationsResponse) XXX_DiscardUnknown() {
	_ = "STUB: not implemented"
	return
}

var xxx_messageInfo_QueryDelegatorUnbondingDelegationsResponse proto.InternalMessageInfo

func (m *QueryDelegatorUnbondingDelegationsResponse) GetUnbondingResponses() []UnbondingDelegation {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorUnbondingDelegationsResponse) GetPagination() *query.PageResponse {
	_ = "STUB: not implemented"
	return nil
}

// QueryRedelegationsRequest is request type for the Query/Redelegations RPC
// method.
type QueryRedelegationsRequest struct {
	// delegator_addr defines the delegator address to query for.
	DelegatorAddr string `protobuf:"bytes,1,opt,name=delegator_addr,json=delegatorAddr,proto3" json:"delegator_addr,omitempty"`
	// src_validator_addr defines the validator address to redelegate from.
	SrcValidatorAddr string `protobuf:"bytes,2,opt,name=src_validator_addr,json=srcValidatorAddr,proto3" json:"src_validator_addr,omitempty"`
	// dst_validator_addr defines the validator address to redelegate to.
	DstValidatorAddr string `protobuf:"bytes,3,opt,name=dst_validator_addr,json=dstValidatorAddr,proto3" json:"dst_validator_addr,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRedelegationsRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryRedelegationsRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryRedelegationsRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryRedelegationsRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryRedelegationsRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryRedelegationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryRedelegationsRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryRedelegationsRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryRedelegationsRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryRedelegationsRequest proto.InternalMessageInfo

// QueryRedelegationsResponse is response type for the Query/Redelegations RPC
// method.
type QueryRedelegationsResponse struct {
	RedelegationResponses []RedelegationResponse `protobuf:"bytes,1,rep,name=redelegation_responses,json=redelegationResponses,proto3" json:"redelegation_responses"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRedelegationsResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryRedelegationsResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryRedelegationsResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryRedelegationsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryRedelegationsResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryRedelegationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryRedelegationsResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryRedelegationsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryRedelegationsResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryRedelegationsResponse proto.InternalMessageInfo

func (m *QueryRedelegationsResponse) GetRedelegationResponses() []RedelegationResponse {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryRedelegationsResponse) GetPagination() *query.PageResponse {
	_ = "STUB: not implemented"
	return nil
}

// QueryDelegatorValidatorsRequest is request type for the
// Query/DelegatorValidators RPC method.
type QueryDelegatorValidatorsRequest struct {
	// delegator_addr defines the delegator address to query for.
	DelegatorAddr string `protobuf:"bytes,1,opt,name=delegator_addr,json=delegatorAddr,proto3" json:"delegator_addr,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDelegatorValidatorsRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryDelegatorValidatorsRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryDelegatorValidatorsRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryDelegatorValidatorsRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorValidatorsRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorValidatorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorValidatorsRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryDelegatorValidatorsRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryDelegatorValidatorsRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryDelegatorValidatorsRequest proto.InternalMessageInfo

// QueryDelegatorValidatorsResponse is response type for the
// Query/DelegatorValidators RPC method.
type QueryDelegatorValidatorsResponse struct {
	// validators defines the the validators' info of a delegator.
	Validators []Validator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDelegatorValidatorsResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryDelegatorValidatorsResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryDelegatorValidatorsResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryDelegatorValidatorsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorValidatorsResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorValidatorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorValidatorsResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryDelegatorValidatorsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryDelegatorValidatorsResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryDelegatorValidatorsResponse proto.InternalMessageInfo

func (m *QueryDelegatorValidatorsResponse) GetValidators() []Validator {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorValidatorsResponse) GetPagination() *query.PageResponse {
	_ = "STUB: not implemented"
	return nil
}

// QueryDelegatorValidatorRequest is request type for the
// Query/DelegatorValidator RPC method.
type QueryDelegatorValidatorRequest struct {
	// delegator_addr defines the delegator address to query for.
	DelegatorAddr string `protobuf:"bytes,1,opt,name=delegator_addr,json=delegatorAddr,proto3" json:"delegator_addr,omitempty"`
	// validator_addr defines the validator address to query for.
	ValidatorAddr string `protobuf:"bytes,2,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
}

func (m *QueryDelegatorValidatorRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryDelegatorValidatorRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryDelegatorValidatorRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryDelegatorValidatorRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorValidatorRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorValidatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorValidatorRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryDelegatorValidatorRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryDelegatorValidatorRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryDelegatorValidatorRequest proto.InternalMessageInfo

// QueryDelegatorValidatorResponse response type for the
// Query/DelegatorValidator RPC method.
type QueryDelegatorValidatorResponse struct {
	// validator defines the the validator info.
	Validator Validator `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator"`
}

func (m *QueryDelegatorValidatorResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryDelegatorValidatorResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryDelegatorValidatorResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryDelegatorValidatorResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorValidatorResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorValidatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorValidatorResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryDelegatorValidatorResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryDelegatorValidatorResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryDelegatorValidatorResponse proto.InternalMessageInfo

func (m *QueryDelegatorValidatorResponse) GetValidator() Validator {
	_ = "STUB: not implemented"
	return *new(Validator)
}

// QueryHistoricalInfoRequest is request type for the Query/HistoricalInfo RPC
// method.
type QueryHistoricalInfoRequest struct {
	// height defines at which height to query the historical info.
	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *QueryHistoricalInfoRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryHistoricalInfoRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryHistoricalInfoRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryHistoricalInfoRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryHistoricalInfoRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryHistoricalInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryHistoricalInfoRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryHistoricalInfoRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryHistoricalInfoRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryHistoricalInfoRequest proto.InternalMessageInfo

func (m *QueryHistoricalInfoRequest) GetHeight() int64 { _ = "STUB: not implemented"; return 0 }

// QueryHistoricalInfoResponse is response type for the Query/HistoricalInfo RPC
// method.
type QueryHistoricalInfoResponse struct {
	// hist defines the historical info at the given height.
	Hist *HistoricalInfo `protobuf:"bytes,1,opt,name=hist,proto3" json:"hist,omitempty"`
}

func (m *QueryHistoricalInfoResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryHistoricalInfoResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryHistoricalInfoResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryHistoricalInfoResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryHistoricalInfoResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryHistoricalInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryHistoricalInfoResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryHistoricalInfoResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryHistoricalInfoResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryHistoricalInfoResponse proto.InternalMessageInfo

func (m *QueryHistoricalInfoResponse) GetHist() *HistoricalInfo {
	_ = "STUB: not implemented"
	return nil
}

// QueryPoolRequest is request type for the Query/Pool RPC method.
type QueryPoolRequest struct {
}

func (m *QueryPoolRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *QueryPoolRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*QueryPoolRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*QueryPoolRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *QueryPoolRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryPoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPoolRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryPoolRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryPoolRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryPoolRequest proto.InternalMessageInfo

// QueryPoolResponse is response type for the Query/Pool RPC method.
type QueryPoolResponse struct {
	// pool defines the pool info.
	Pool Pool `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool"`
}

func (m *QueryPoolResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (m *QueryPoolResponse) String() string            { _ = "STUB: not implemented"; return "" }
func (*QueryPoolResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*QueryPoolResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *QueryPoolResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPoolResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryPoolResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryPoolResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryPoolResponse proto.InternalMessageInfo

func (m *QueryPoolResponse) GetPool() Pool { _ = "STUB: not implemented"; return *new(Pool) }

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *QueryParamsRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*QueryParamsRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*QueryParamsRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryParamsRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryParamsRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryParamsRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryParamsResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryParamsResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryParamsResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryParamsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryParamsResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params { _ = "STUB: not implemented"; return *new(Params) }

func init() {
	proto.RegisterType((*QueryValidatorsRequest)(nil), "cosmos.staking.v1beta1.QueryValidatorsRequest")
	proto.RegisterType((*QueryValidatorsResponse)(nil), "cosmos.staking.v1beta1.QueryValidatorsResponse")
	proto.RegisterType((*QueryValidatorRequest)(nil), "cosmos.staking.v1beta1.QueryValidatorRequest")
	proto.RegisterType((*QueryValidatorResponse)(nil), "cosmos.staking.v1beta1.QueryValidatorResponse")
	proto.RegisterType((*QueryValidatorDelegationsRequest)(nil), "cosmos.staking.v1beta1.QueryValidatorDelegationsRequest")
	proto.RegisterType((*QueryValidatorDelegationsResponse)(nil), "cosmos.staking.v1beta1.QueryValidatorDelegationsResponse")
	proto.RegisterType((*QueryValidatorUnbondingDelegationsRequest)(nil), "cosmos.staking.v1beta1.QueryValidatorUnbondingDelegationsRequest")
	proto.RegisterType((*QueryValidatorUnbondingDelegationsResponse)(nil), "cosmos.staking.v1beta1.QueryValidatorUnbondingDelegationsResponse")
	proto.RegisterType((*QueryDelegationRequest)(nil), "cosmos.staking.v1beta1.QueryDelegationRequest")
	proto.RegisterType((*QueryDelegationResponse)(nil), "cosmos.staking.v1beta1.QueryDelegationResponse")
	proto.RegisterType((*QueryUnbondingDelegationRequest)(nil), "cosmos.staking.v1beta1.QueryUnbondingDelegationRequest")
	proto.RegisterType((*QueryUnbondingDelegationResponse)(nil), "cosmos.staking.v1beta1.QueryUnbondingDelegationResponse")
	proto.RegisterType((*QueryDelegatorDelegationsRequest)(nil), "cosmos.staking.v1beta1.QueryDelegatorDelegationsRequest")
	proto.RegisterType((*QueryDelegatorDelegationsResponse)(nil), "cosmos.staking.v1beta1.QueryDelegatorDelegationsResponse")
	proto.RegisterType((*QueryDelegatorUnbondingDelegationsRequest)(nil), "cosmos.staking.v1beta1.QueryDelegatorUnbondingDelegationsRequest")
	proto.RegisterType((*QueryDelegatorUnbondingDelegationsResponse)(nil), "cosmos.staking.v1beta1.QueryDelegatorUnbondingDelegationsResponse")
	proto.RegisterType((*QueryRedelegationsRequest)(nil), "cosmos.staking.v1beta1.QueryRedelegationsRequest")
	proto.RegisterType((*QueryRedelegationsResponse)(nil), "cosmos.staking.v1beta1.QueryRedelegationsResponse")
	proto.RegisterType((*QueryDelegatorValidatorsRequest)(nil), "cosmos.staking.v1beta1.QueryDelegatorValidatorsRequest")
	proto.RegisterType((*QueryDelegatorValidatorsResponse)(nil), "cosmos.staking.v1beta1.QueryDelegatorValidatorsResponse")
	proto.RegisterType((*QueryDelegatorValidatorRequest)(nil), "cosmos.staking.v1beta1.QueryDelegatorValidatorRequest")
	proto.RegisterType((*QueryDelegatorValidatorResponse)(nil), "cosmos.staking.v1beta1.QueryDelegatorValidatorResponse")
	proto.RegisterType((*QueryHistoricalInfoRequest)(nil), "cosmos.staking.v1beta1.QueryHistoricalInfoRequest")
	proto.RegisterType((*QueryHistoricalInfoResponse)(nil), "cosmos.staking.v1beta1.QueryHistoricalInfoResponse")
	proto.RegisterType((*QueryPoolRequest)(nil), "cosmos.staking.v1beta1.QueryPoolRequest")
	proto.RegisterType((*QueryPoolResponse)(nil), "cosmos.staking.v1beta1.QueryPoolResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmos.staking.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmos.staking.v1beta1.QueryParamsResponse")
}

func init() {
	proto.RegisterFile("cosmos/staking/v1beta1/query.proto", fileDescriptor_f270127f442bbcd8)
}

var fileDescriptor_f270127f442bbcd8 = []byte{
	// 1313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x59, 0xcd, 0x6f, 0x1b, 0x55,
	0x10, 0xf7, 0x4b, 0x42, 0x44, 0xa6, 0x6a, 0x55, 0x9e, 0x93, 0x10, 0xb6, 0xc1, 0x4e, 0x57, 0x21,
	0xa4, 0x69, 0xea, 0x25, 0x49, 0x49, 0x43, 0x89, 0x0a, 0x09, 0xa5, 0x25, 0xea, 0x81, 0xc4, 0x88,
	0xf0, 0x75, 0x88, 0xd6, 0xf6, 0x76, 0xbd, 0xc2, 0xd9, 0xe7, 0xee, 0x6e, 0xa2, 0x84, 0x28, 0x07,
	0x38, 0xc1, 0x0d, 0xc4, 0x09, 0xb8, 0xf4, 0x80, 0x84, 0x04, 0x47, 0xf8, 0x07, 0x38, 0x51, 0x6e,
	0x41, 0x70, 0x80, 0x4b, 0x41, 0x09, 0x87, 0x8a, 0x13, 0x37, 0xc4, 0xad, 0xf2, 0xdb, 0xd9, 0xf5,
	0x6e, 0xf6, 0xd3, 0x8e, 0xa3, 0xa8, 0x37, 0xfb, 0x79, 0x3e, 0x7e, 0xbf, 0x99, 0x37, 0xf3, 0x66,
	0x64, 0x10, 0xcb, 0xcc, 0x5c, 0x67, 0xa6, 0x64, 0x5a, 0xf2, 0xfb, 0x9a, 0xae, 0x4a, 0x9b, 0x53,
	0x25, 0xc5, 0x92, 0xa7, 0xa4, 0x3b, 0x1b, 0x8a, 0xb1, 0x5d, 0xa8, 0x1b, 0xcc, 0x62, 0x74, 0xd0,
	0x96, 0x29, 0xa0, 0x4c, 0x01, 0x65, 0x84, 0x09, 0xd4, 0x2d, 0xc9, 0xa6, 0x62, 0x2b, 0xb8, 0xea,
	0x75, 0x59, 0xd5, 0x74, 0xd9, 0xd2, 0x98, 0x6e, 0xdb, 0x10, 0x46, 0x23, 0xfc, 0x38, 0x36, 0x6d,
	0xa9, 0x7e, 0x95, 0xa9, 0x8c, 0x7f, 0x94, 0x1a, 0x9f, 0xf0, 0x74, 0x58, 0x65, 0x4c, 0xad, 0x29,
	0x92, 0x5c, 0xd7, 0x24, 0x59, 0xd7, 0x99, 0xc5, 0x0d, 0x9b, 0xf6, 0xaf, 0xe2, 0x16, 0x0c, 0xae,
	0x34, 0x7c, 0xaf, 0xca, 0x35, 0xad, 0x22, 0x5b, 0xcc, 0x30, 0x8b, 0xca, 0x9d, 0x0d, 0xc5, 0xb4,
	0xe8, 0x20, 0xf4, 0x9a, 0x96, 0x6c, 0x6d, 0x98, 0x43, 0x64, 0x84, 0x8c, 0xf7, 0x15, 0xf1, 0x1b,
	0xbd, 0x01, 0xd0, 0xc4, 0x37, 0xd4, 0x35, 0x42, 0xc6, 0x4f, 0x4d, 0x8f, 0x15, 0x90, 0x64, 0x83,
	0x4c, 0xc1, 0x66, 0x8f, 0x18, 0x0b, 0xcb, 0xb2, 0xaa, 0xa0, 0xcd, 0xa2, 0x47, 0x53, 0xfc, 0x8e,
	0xc0, 0x93, 0x01, 0xd7, 0x66, 0x9d, 0xe9, 0xa6, 0x42, 0x6f, 0x02, 0x6c, 0xba, 0xa7, 0x43, 0x64,
	0xa4, 0x7b, 0xfc, 0xd4, 0xf4, 0xf9, 0x42, 0x78, 0x20, 0x0b, 0xae, 0xfe, 0x62, 0xcf, 0xbd, 0xfb,
	0xf9, 0x4c, 0xd1, 0xa3, 0xda, 0x30, 0x14, 0x00, 0xfb, 0x6c, 0x22, 0x58, 0x1b, 0x85, 0x0f, 0xed,
	0x35, 0x18, 0xf0, 0x83, 0x75, 0xc2, 0xf4, 0x0c, 0x9c, 0x71, 0xfd, 0xad, 0xc9, 0x95, 0x8a, 0x81,
	0xe1, 0x3a, 0xed, 0x9e, 0x2e, 0x54, 0x2a, 0x86, 0xb8, 0x76, 0x38, 0xce, 0x2e, 0xd7, 0x57, 0xa1,
	0xcf, 0x15, 0xe5, 0xba, 0x2d, 0x50, 0x6d, 0x6a, 0x8a, 0x9f, 0x11, 0x18, 0xf1, 0x7b, 0xb8, 0xae,
	0xd4, 0x14, 0xd5, 0x4e, 0x76, 0x6b, 0x60, 0x3b, 0x96, 0xe2, 0x07, 0x04, 0xce, 0xc7, 0x60, 0xc2,
	0x00, 0x7c, 0x00, 0xfd, 0x15, 0xf7, 0x78, 0xcd, 0xc0, 0x63, 0x27, 0xed, 0x13, 0x51, 0xb1, 0x68,
	0x9a, 0x72, 0x2c, 0x2d, 0x9e, 0x6b, 0x04, 0xe5, 0xdb, 0x3f, 0xf3, 0xd9, 0xe0, 0x6f, 0x66, 0x31,
	0x5b, 0x09, 0x1e, 0x76, 0xee, 0x7e, 0x7c, 0x49, 0xe0, 0x82, 0x9f, 0xea, 0x9b, 0x7a, 0x89, 0xe9,
	0x15, 0x4d, 0x57, 0x4f, 0x3e, 0x0f, 0x7f, 0x10, 0x98, 0x48, 0x03, 0x0e, 0x13, 0x52, 0x82, 0xec,
	0x86, 0xf3, 0x7b, 0x20, 0x1f, 0x17, 0xa3, 0xf2, 0x11, 0x62, 0x12, 0x6f, 0x29, 0x75, 0xad, 0x1d,
	0x43, 0xe0, 0xeb, 0x58, 0x58, 0xde, 0x94, 0xbb, 0x41, 0xc6, 0x94, 0x1f, 0x0a, 0xb2, 0x7b, 0xca,
	0x83, 0x1c, 0xcc, 0x45, 0x57, 0x48, 0x2e, 0xae, 0x3e, 0xfe, 0xf1, 0xdd, 0x7c, 0xe6, 0xc1, 0xdd,
	0x7c, 0x46, 0xdc, 0xc4, 0xbe, 0x15, 0xbc, 0x64, 0xf4, 0x3d, 0xc8, 0x86, 0x5c, 0x65, 0xac, 0xea,
	0x16, 0x6e, 0x72, 0x91, 0x06, 0x2f, 0xab, 0xb8, 0x0d, 0x79, 0xee, 0x37, 0x24, 0xd0, 0xc7, 0x4d,
	0x79, 0x1d, 0x7b, 0x4b, 0xa8, 0x6b, 0xe4, 0xbe, 0x04, 0xbd, 0x76, 0x9e, 0x91, 0x6e, 0x1b, 0x17,
	0x05, 0x0d, 0x88, 0x5f, 0x39, 0xbd, 0xec, 0xba, 0x03, 0x3b, 0xbc, 0x86, 0xd2, 0x70, 0xed, 0x50,
	0x0d, 0x79, 0x82, 0xf1, 0x8b, 0xd3, 0xd5, 0xc2, 0xd1, 0x61, 0x38, 0xca, 0x1d, 0xeb, 0x6a, 0x76,
	0x6c, 0x8e, 0xb7, 0x7d, 0x7d, 0xed, 0xb4, 0x2f, 0x97, 0x53, 0x42, 0xfb, 0x3a, 0x99, 0xd0, 0xbb,
	0x8d, 0x2c, 0x01, 0xe6, 0xa3, 0xd8, 0xc8, 0xfe, 0x25, 0xf0, 0x14, 0xe7, 0x56, 0x54, 0x2a, 0x6d,
	0x87, 0x7c, 0x12, 0xa8, 0x69, 0x94, 0xd7, 0x42, 0xab, 0xfb, 0xac, 0x69, 0x94, 0x57, 0x7d, 0xef,
	0xcb, 0x24, 0xd0, 0x8a, 0x69, 0x1d, 0x96, 0xee, 0xb6, 0xa5, 0x2b, 0xa6, 0xb5, 0x1a, 0xf3, 0x1a,
	0xf5, 0x74, 0x20, 0x9d, 0x7b, 0x04, 0x84, 0x30, 0xca, 0x98, 0x3e, 0x0d, 0x06, 0x0d, 0x25, 0xa6,
	0x88, 0x26, 0xa3, 0x32, 0xe8, 0x35, 0x77, 0xa8, 0x8c, 0x06, 0x0c, 0xe5, 0xb8, 0xe7, 0x80, 0xbc,
	0xff, 0x86, 0x06, 0x27, 0xeb, 0x13, 0x2b, 0x9f, 0x1f, 0x02, 0x7d, 0xf5, 0x91, 0x98, 0xbd, 0xb7,
	0x20, 0x17, 0x81, 0xfa, 0xb8, 0xdf, 0xbd, 0x6a, 0x64, 0x32, 0x3b, 0x3d, 0xbe, 0x5f, 0xc6, 0x4a,
	0x78, 0x4d, 0x33, 0x2d, 0x66, 0x68, 0x65, 0xb9, 0xb6, 0xa4, 0xdf, 0x66, 0x9e, 0x5d, 0xac, 0xaa,
	0x68, 0x6a, 0xd5, 0xe2, 0x1e, 0xba, 0x8b, 0xf8, 0x4d, 0x7c, 0x07, 0xce, 0x85, 0x6a, 0x21, 0xb6,
	0xab, 0xd0, 0x53, 0xd5, 0x4c, 0x0b, 0x61, 0x8d, 0x45, 0xc1, 0x3a, 0xa4, 0xcd, 0x75, 0x44, 0x0a,
	0x67, 0xb9, 0xe9, 0x65, 0xc6, 0x6a, 0x08, 0x43, 0xbc, 0x05, 0x4f, 0x78, 0xce, 0xd0, 0xc9, 0x2c,
	0xf4, 0xd4, 0x19, 0xab, 0xa1, 0x93, 0xe1, 0x28, 0x27, 0x0d, 0x1d, 0xa4, 0xcd, 0xe5, 0xc5, 0x7e,
	0xa0, 0xb6, 0x31, 0xd9, 0x90, 0xd7, 0x9d, 0xda, 0x10, 0xdf, 0x80, 0xac, 0xef, 0x14, 0x9d, 0xcc,
	0x43, 0x6f, 0x9d, 0x9f, 0xa0, 0x9b, 0x5c, 0xa4, 0x1b, 0x2e, 0xe5, 0xcc, 0x13, 0xb6, 0xce, 0xf4,
	0x3f, 0x03, 0xf0, 0x18, 0xb7, 0x4a, 0xbf, 0x20, 0x00, 0xcd, 0x3b, 0x4f, 0x0b, 0x51, 0x66, 0xc2,
	0x77, 0x62, 0x41, 0x4a, 0x2d, 0x8f, 0x33, 0xdb, 0xc4, 0x47, 0xbf, 0xfe, 0xfd, 0x79, 0xd7, 0x28,
	0x15, 0xa5, 0x88, 0x0d, 0xde, 0x53, 0x2f, 0xdf, 0x10, 0xe8, 0x73, 0x4d, 0xd0, 0x4b, 0xe9, 0x5c,
	0x39, 0xc8, 0x0a, 0x69, 0xc5, 0x11, 0xd8, 0x8b, 0x1c, 0xd8, 0xf3, 0x74, 0x26, 0x19, 0x98, 0xb4,
	0xe3, 0x2f, 0x9a, 0x5d, 0xfa, 0x1b, 0x81, 0xfe, 0xb0, 0x95, 0x8e, 0xce, 0xa5, 0x43, 0x11, 0x1c,
	0x29, 0x84, 0x17, 0xda, 0xd0, 0x44, 0x2a, 0x37, 0x39, 0x95, 0x05, 0xfa, 0x52, 0x1b, 0x54, 0x24,
	0xcf, 0xbb, 0x43, 0xff, 0x27, 0xf0, 0x74, 0xec, 0x86, 0x44, 0x17, 0xd2, 0xa1, 0x8c, 0x99, 0x9d,
	0x84, 0xc5, 0xa3, 0x98, 0x40, 0xc6, 0x2b, 0x9c, 0xf1, 0x2d, 0xba, 0xd4, 0x0e, 0xe3, 0xe6, 0x44,
	0xe4, 0xe5, 0xfe, 0x13, 0x01, 0x68, 0xba, 0x4a, 0x28, 0x8c, 0xc0, 0xe2, 0x91, 0x50, 0x18, 0xc1,
	0xa1, 0x56, 0x7c, 0x9b, 0x53, 0x28, 0xd2, 0xe5, 0x23, 0x26, 0x4d, 0xda, 0xf1, 0x37, 0xfe, 0x5d,
	0xfa, 0x1f, 0x81, 0x6c, 0x48, 0xf4, 0xe8, 0x95, 0x58, 0x88, 0xd1, 0x4b, 0x95, 0x30, 0xd7, 0xba,
	0x22, 0x92, 0x5c, 0xe7, 0x24, 0x55, 0xaa, 0x74, 0x9a, 0x64, 0x68, 0x12, 0xe9, 0xcf, 0x04, 0xfa,
	0xc3, 0x76, 0x92, 0x84, 0xb2, 0x8c, 0x59, 0xb2, 0x12, 0xca, 0x32, 0x6e, 0x01, 0x12, 0xe7, 0x39,
	0xf9, 0x59, 0x7a, 0x39, 0x8a, 0x7c, 0x6c, 0x16, 0x1b, 0xb5, 0x18, 0x3b, 0xe4, 0x27, 0xd4, 0x62,
	0x9a, 0x3d, 0x26, 0xa1, 0x16, 0x53, 0xed, 0x18, 0xc9, 0xb5, 0xe8, 0x32, 0x4b, 0x99, 0x46, 0x93,
	0xfe, 0x48, 0xe0, 0xb4, 0x6f, 0x22, 0xa6, 0x53, 0xb1, 0x40, 0xc3, 0x16, 0x06, 0x61, 0xba, 0x15,
	0x15, 0xe4, 0xb2, 0xc4, 0xb9, 0xbc, 0x42, 0x17, 0xda, 0xe1, 0x62, 0xf8, 0x10, 0xef, 0x11, 0xc8,
	0x86, 0x4c, 0x99, 0x09, 0x55, 0x18, 0x3d, 0x34, 0x0b, 0x73, 0xad, 0x2b, 0x22, 0xab, 0x1b, 0x9c,
	0xd5, 0xcb, 0xf4, 0x5a, 0x3b, 0xac, 0x3c, 0xef, 0xf3, 0x7d, 0x02, 0x34, 0xe8, 0x87, 0xce, 0xb6,
	0x08, 0xcc, 0x21, 0x74, 0xa5, 0x65, 0x3d, 0xe4, 0xf3, 0x16, 0xe7, 0xb3, 0x42, 0x5f, 0x3f, 0x1a,
	0x9f, 0xe0, 0xb3, 0xfe, 0x3d, 0x81, 0x33, 0xfe, 0x59, 0x90, 0xc6, 0xdf, 0xa2, 0xd0, 0x61, 0x55,
	0x98, 0x69, 0x49, 0x07, 0x49, 0xcd, 0x71, 0x52, 0xd3, 0xf4, 0xb9, 0x28, 0x52, 0x55, 0x57, 0x6f,
	0x4d, 0xd3, 0x6f, 0x33, 0x69, 0xc7, 0x1e, 0x81, 0x77, 0xe9, 0x87, 0x04, 0x7a, 0x1a, 0xc3, 0x25,
	0x1d, 0x8f, 0xf5, 0xeb, 0x99, 0x63, 0x85, 0x0b, 0x29, 0x24, 0x11, 0xd7, 0x28, 0xc7, 0x95, 0xa3,
	0xc3, 0x51, 0xb8, 0x1a, 0xb3, 0x2c, 0xfd, 0x84, 0x40, 0xaf, 0x3d, 0x79, 0xd2, 0x89, 0x78, 0xdb,
	0xde, 0x61, 0x57, 0xb8, 0x98, 0x4a, 0x16, 0x91, 0x8c, 0x71, 0x24, 0x23, 0x34, 0x17, 0x89, 0xc4,
	0x1e, 0x7d, 0x57, 0xef, 0xed, 0xe7, 0xc8, 0xde, 0x7e, 0x8e, 0xfc, 0xb5, 0x9f, 0x23, 0x9f, 0x1e,
	0xe4, 0x32, 0x7b, 0x07, 0xb9, 0xcc, 0xef, 0x07, 0xb9, 0xcc, 0xbb, 0xf3, 0xaa, 0x66, 0x55, 0x37,
	0x4a, 0x85, 0x32, 0x5b, 0x97, 0x4c, 0x45, 0xbb, 0xc4, 0xff, 0x01, 0x2a, 0xb3, 0x1a, 0xff, 0x52,
	0xae, 0xca, 0x9a, 0x6e, 0x7f, 0xb2, 0xcd, 0x6f, 0xb9, 0x0e, 0xac, 0xed, 0xba, 0x62, 0x96, 0x7a,
	0xb9, 0xf8, 0xcc, 0xc3, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x89, 0x7b, 0xe0, 0xf4, 0x1a, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Validators queries all validators that match the given status.
	Validators(ctx context.Context, in *QueryValidatorsRequest, opts ...grpc.CallOption) (*QueryValidatorsResponse, error)
	// Validator queries validator info for given validator address.
	Validator(ctx context.Context, in *QueryValidatorRequest, opts ...grpc.CallOption) (*QueryValidatorResponse, error)
	// ValidatorDelegations queries delegate info for given validator.
	ValidatorDelegations(ctx context.Context, in *QueryValidatorDelegationsRequest, opts ...grpc.CallOption) (*QueryValidatorDelegationsResponse, error)
	// ValidatorUnbondingDelegations queries unbonding delegations of a validator.
	ValidatorUnbondingDelegations(ctx context.Context, in *QueryValidatorUnbondingDelegationsRequest, opts ...grpc.CallOption) (*QueryValidatorUnbondingDelegationsResponse, error)
	// Delegation queries delegate info for given validator delegator pair.
	Delegation(ctx context.Context, in *QueryDelegationRequest, opts ...grpc.CallOption) (*QueryDelegationResponse, error)
	// UnbondingDelegation queries unbonding info for given validator delegator
	// pair.
	UnbondingDelegation(ctx context.Context, in *QueryUnbondingDelegationRequest, opts ...grpc.CallOption) (*QueryUnbondingDelegationResponse, error)
	// DelegatorDelegations queries all delegations of a given delegator address.
	DelegatorDelegations(ctx context.Context, in *QueryDelegatorDelegationsRequest, opts ...grpc.CallOption) (*QueryDelegatorDelegationsResponse, error)
	// DelegatorUnbondingDelegations queries all unbonding delegations of a given
	// delegator address.
	DelegatorUnbondingDelegations(ctx context.Context, in *QueryDelegatorUnbondingDelegationsRequest, opts ...grpc.CallOption) (*QueryDelegatorUnbondingDelegationsResponse, error)
	// Redelegations queries redelegations of given address.
	Redelegations(ctx context.Context, in *QueryRedelegationsRequest, opts ...grpc.CallOption) (*QueryRedelegationsResponse, error)
	// DelegatorValidators queries all validators info for given delegator
	// address.
	DelegatorValidators(ctx context.Context, in *QueryDelegatorValidatorsRequest, opts ...grpc.CallOption) (*QueryDelegatorValidatorsResponse, error)
	// DelegatorValidator queries validator info for given delegator validator
	// pair.
	DelegatorValidator(ctx context.Context, in *QueryDelegatorValidatorRequest, opts ...grpc.CallOption) (*QueryDelegatorValidatorResponse, error)
	// HistoricalInfo queries the historical info for given height.
	HistoricalInfo(ctx context.Context, in *QueryHistoricalInfoRequest, opts ...grpc.CallOption) (*QueryHistoricalInfoResponse, error)
	// Pool queries the pool info.
	Pool(ctx context.Context, in *QueryPoolRequest, opts ...grpc.CallOption) (*QueryPoolResponse, error)
	// Parameters queries the staking parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	_ = "STUB: not implemented"
	return *new(QueryClient)
}

func (c *queryClient) Validators(ctx context.Context, in *QueryValidatorsRequest, opts ...grpc.CallOption) (*QueryValidatorsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) Validator(ctx context.Context, in *QueryValidatorRequest, opts ...grpc.CallOption) (*QueryValidatorResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) ValidatorDelegations(ctx context.Context, in *QueryValidatorDelegationsRequest, opts ...grpc.CallOption) (*QueryValidatorDelegationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) ValidatorUnbondingDelegations(ctx context.Context, in *QueryValidatorUnbondingDelegationsRequest, opts ...grpc.CallOption) (*QueryValidatorUnbondingDelegationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) Delegation(ctx context.Context, in *QueryDelegationRequest, opts ...grpc.CallOption) (*QueryDelegationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) UnbondingDelegation(ctx context.Context, in *QueryUnbondingDelegationRequest, opts ...grpc.CallOption) (*QueryUnbondingDelegationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) DelegatorDelegations(ctx context.Context, in *QueryDelegatorDelegationsRequest, opts ...grpc.CallOption) (*QueryDelegatorDelegationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) DelegatorUnbondingDelegations(ctx context.Context, in *QueryDelegatorUnbondingDelegationsRequest, opts ...grpc.CallOption) (*QueryDelegatorUnbondingDelegationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) Redelegations(ctx context.Context, in *QueryRedelegationsRequest, opts ...grpc.CallOption) (*QueryRedelegationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) DelegatorValidators(ctx context.Context, in *QueryDelegatorValidatorsRequest, opts ...grpc.CallOption) (*QueryDelegatorValidatorsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) DelegatorValidator(ctx context.Context, in *QueryDelegatorValidatorRequest, opts ...grpc.CallOption) (*QueryDelegatorValidatorResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) HistoricalInfo(ctx context.Context, in *QueryHistoricalInfoRequest, opts ...grpc.CallOption) (*QueryHistoricalInfoResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) Pool(ctx context.Context, in *QueryPoolRequest, opts ...grpc.CallOption) (*QueryPoolResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Validators queries all validators that match the given status.
	Validators(context.Context, *QueryValidatorsRequest) (*QueryValidatorsResponse, error)
	// Validator queries validator info for given validator address.
	Validator(context.Context, *QueryValidatorRequest) (*QueryValidatorResponse, error)
	// ValidatorDelegations queries delegate info for given validator.
	ValidatorDelegations(context.Context, *QueryValidatorDelegationsRequest) (*QueryValidatorDelegationsResponse, error)
	// ValidatorUnbondingDelegations queries unbonding delegations of a validator.
	ValidatorUnbondingDelegations(context.Context, *QueryValidatorUnbondingDelegationsRequest) (*QueryValidatorUnbondingDelegationsResponse, error)
	// Delegation queries delegate info for given validator delegator pair.
	Delegation(context.Context, *QueryDelegationRequest) (*QueryDelegationResponse, error)
	// UnbondingDelegation queries unbonding info for given validator delegator
	// pair.
	UnbondingDelegation(context.Context, *QueryUnbondingDelegationRequest) (*QueryUnbondingDelegationResponse, error)
	// DelegatorDelegations queries all delegations of a given delegator address.
	DelegatorDelegations(context.Context, *QueryDelegatorDelegationsRequest) (*QueryDelegatorDelegationsResponse, error)
	// DelegatorUnbondingDelegations queries all unbonding delegations of a given
	// delegator address.
	DelegatorUnbondingDelegations(context.Context, *QueryDelegatorUnbondingDelegationsRequest) (*QueryDelegatorUnbondingDelegationsResponse, error)
	// Redelegations queries redelegations of given address.
	Redelegations(context.Context, *QueryRedelegationsRequest) (*QueryRedelegationsResponse, error)
	// DelegatorValidators queries all validators info for given delegator
	// address.
	DelegatorValidators(context.Context, *QueryDelegatorValidatorsRequest) (*QueryDelegatorValidatorsResponse, error)
	// DelegatorValidator queries validator info for given delegator validator
	// pair.
	DelegatorValidator(context.Context, *QueryDelegatorValidatorRequest) (*QueryDelegatorValidatorResponse, error)
	// HistoricalInfo queries the historical info for given height.
	HistoricalInfo(context.Context, *QueryHistoricalInfoRequest) (*QueryHistoricalInfoResponse, error)
	// Pool queries the pool info.
	Pool(context.Context, *QueryPoolRequest) (*QueryPoolResponse, error)
	// Parameters queries the staking parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Validators(ctx context.Context, req *QueryValidatorsRequest) (*QueryValidatorsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) Validator(ctx context.Context, req *QueryValidatorRequest) (*QueryValidatorResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) ValidatorDelegations(ctx context.Context, req *QueryValidatorDelegationsRequest) (*QueryValidatorDelegationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) ValidatorUnbondingDelegations(ctx context.Context, req *QueryValidatorUnbondingDelegationsRequest) (*QueryValidatorUnbondingDelegationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) Delegation(ctx context.Context, req *QueryDelegationRequest) (*QueryDelegationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) UnbondingDelegation(ctx context.Context, req *QueryUnbondingDelegationRequest) (*QueryUnbondingDelegationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) DelegatorDelegations(ctx context.Context, req *QueryDelegatorDelegationsRequest) (*QueryDelegatorDelegationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) DelegatorUnbondingDelegations(ctx context.Context, req *QueryDelegatorUnbondingDelegationsRequest) (*QueryDelegatorUnbondingDelegationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) Redelegations(ctx context.Context, req *QueryRedelegationsRequest) (*QueryRedelegationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) DelegatorValidators(ctx context.Context, req *QueryDelegatorValidatorsRequest) (*QueryDelegatorValidatorsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) DelegatorValidator(ctx context.Context, req *QueryDelegatorValidatorRequest) (*QueryDelegatorValidatorResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) HistoricalInfo(ctx context.Context, req *QueryHistoricalInfoRequest) (*QueryHistoricalInfoResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) Pool(ctx context.Context, req *QueryPoolRequest) (*QueryPoolResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) { _ = "STUB: not implemented"; return }

func _Query_Validators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_Validator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_ValidatorDelegations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_ValidatorUnbondingDelegations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_Delegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_UnbondingDelegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_DelegatorDelegations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_DelegatorUnbondingDelegations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_Redelegations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_DelegatorValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_DelegatorValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_HistoricalInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_Pool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.staking.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validators",
			Handler:    _Query_Validators_Handler,
		},
		{
			MethodName: "Validator",
			Handler:    _Query_Validator_Handler,
		},
		{
			MethodName: "ValidatorDelegations",
			Handler:    _Query_ValidatorDelegations_Handler,
		},
		{
			MethodName: "ValidatorUnbondingDelegations",
			Handler:    _Query_ValidatorUnbondingDelegations_Handler,
		},
		{
			MethodName: "Delegation",
			Handler:    _Query_Delegation_Handler,
		},
		{
			MethodName: "UnbondingDelegation",
			Handler:    _Query_UnbondingDelegation_Handler,
		},
		{
			MethodName: "DelegatorDelegations",
			Handler:    _Query_DelegatorDelegations_Handler,
		},
		{
			MethodName: "DelegatorUnbondingDelegations",
			Handler:    _Query_DelegatorUnbondingDelegations_Handler,
		},
		{
			MethodName: "Redelegations",
			Handler:    _Query_Redelegations_Handler,
		},
		{
			MethodName: "DelegatorValidators",
			Handler:    _Query_DelegatorValidators_Handler,
		},
		{
			MethodName: "DelegatorValidator",
			Handler:    _Query_DelegatorValidator_Handler,
		},
		{
			MethodName: "HistoricalInfo",
			Handler:    _Query_HistoricalInfo_Handler,
		},
		{
			MethodName: "Pool",
			Handler:    _Query_Pool_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/staking/v1beta1/query.proto",
}

func (m *QueryValidatorsRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorsRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryValidatorsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryValidatorsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryValidatorsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryValidatorRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryValidatorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryValidatorResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryValidatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryValidatorDelegationsRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorDelegationsRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryValidatorDelegationsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryValidatorDelegationsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorDelegationsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryValidatorDelegationsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryValidatorUnbondingDelegationsRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorUnbondingDelegationsRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryValidatorUnbondingDelegationsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryValidatorUnbondingDelegationsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryValidatorUnbondingDelegationsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryValidatorUnbondingDelegationsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegationRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegationRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegationResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegationResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryUnbondingDelegationRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnbondingDelegationRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryUnbondingDelegationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryUnbondingDelegationResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnbondingDelegationResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryUnbondingDelegationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegatorDelegationsRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorDelegationsRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegatorDelegationsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegatorDelegationsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorDelegationsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegatorDelegationsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegatorUnbondingDelegationsRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorUnbondingDelegationsRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegatorUnbondingDelegationsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegatorUnbondingDelegationsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorUnbondingDelegationsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegatorUnbondingDelegationsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryRedelegationsRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryRedelegationsRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryRedelegationsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryRedelegationsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryRedelegationsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryRedelegationsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegatorValidatorsRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorValidatorsRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegatorValidatorsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegatorValidatorsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorValidatorsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegatorValidatorsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegatorValidatorRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorValidatorRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegatorValidatorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegatorValidatorResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryDelegatorValidatorResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryDelegatorValidatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryHistoricalInfoRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryHistoricalInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryHistoricalInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryHistoricalInfoResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryHistoricalInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryHistoricalInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPoolRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPoolRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPoolRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPoolResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPoolResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPoolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *QueryValidatorsRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryValidatorsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryValidatorRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryValidatorResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryValidatorDelegationsRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryValidatorDelegationsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryValidatorUnbondingDelegationsRequest) Size() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *QueryValidatorUnbondingDelegationsResponse) Size() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *QueryDelegationRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryDelegationResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryUnbondingDelegationRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryUnbondingDelegationResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryDelegatorDelegationsRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryDelegatorDelegationsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryDelegatorUnbondingDelegationsRequest) Size() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *QueryDelegatorUnbondingDelegationsResponse) Size() (n int) {
	_ = "STUB: not implemented"
	return 0
}

func (m *QueryRedelegationsRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryRedelegationsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryDelegatorValidatorsRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryDelegatorValidatorsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryDelegatorValidatorRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryDelegatorValidatorResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryHistoricalInfoRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryHistoricalInfoResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryPoolRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryPoolResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryParamsRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryParamsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovQuery(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozQuery(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryValidatorsRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryValidatorsResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryValidatorRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryValidatorResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryValidatorDelegationsRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryValidatorDelegationsResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryValidatorUnbondingDelegationsRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryValidatorUnbondingDelegationsResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegationRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegationResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryUnbondingDelegationRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryUnbondingDelegationResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorDelegationsRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorDelegationsResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorUnbondingDelegationsRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorUnbondingDelegationsResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryRedelegationsRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryRedelegationsResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorValidatorsRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorValidatorsResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorValidatorRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryDelegatorValidatorResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryHistoricalInfoRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryHistoricalInfoResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPoolRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryPoolResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipQuery(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
