// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proofs.proto

package ics23

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HashOp int32

const (
	// NO_HASH is the default if no data passed. Note this is an illegal argument some places.
	HashOp_NO_HASH    HashOp = 0
	HashOp_SHA256     HashOp = 1
	HashOp_SHA512     HashOp = 2
	HashOp_KECCAK     HashOp = 3
	HashOp_RIPEMD160  HashOp = 4
	HashOp_BITCOIN    HashOp = 5
	HashOp_SHA512_256 HashOp = 6
)

var HashOp_name = map[int32]string{
	0: "NO_HASH",
	1: "SHA256",
	2: "SHA512",
	3: "KECCAK",
	4: "RIPEMD160",
	5: "BITCOIN",
	6: "SHA512_256",
}

var HashOp_value = map[string]int32{
	"NO_HASH":    0,
	"SHA256":     1,
	"SHA512":     2,
	"KECCAK":     3,
	"RIPEMD160":  4,
	"BITCOIN":    5,
	"SHA512_256": 6,
}

func (x HashOp) String() string { _ = "STUB: not implemented"; return "" }

func (HashOp) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// *
// LengthOp defines how to process the key and value of the LeafOp
// to include length information. After encoding the length with the given
// algorithm, the length will be prepended to the key and value bytes.
// (Each one with it's own encoded length)
type LengthOp int32

const (
	// NO_PREFIX don't include any length info
	LengthOp_NO_PREFIX LengthOp = 0
	// VAR_PROTO uses protobuf (and go-amino) varint encoding of the length
	LengthOp_VAR_PROTO LengthOp = 1
	// VAR_RLP uses rlp int encoding of the length
	LengthOp_VAR_RLP LengthOp = 2
	// FIXED32_BIG uses big-endian encoding of the length as a 32 bit integer
	LengthOp_FIXED32_BIG LengthOp = 3
	// FIXED32_LITTLE uses little-endian encoding of the length as a 32 bit integer
	LengthOp_FIXED32_LITTLE LengthOp = 4
	// FIXED64_BIG uses big-endian encoding of the length as a 64 bit integer
	LengthOp_FIXED64_BIG LengthOp = 5
	// FIXED64_LITTLE uses little-endian encoding of the length as a 64 bit integer
	LengthOp_FIXED64_LITTLE LengthOp = 6
	// REQUIRE_32_BYTES is like NONE, but will fail if the input is not exactly 32 bytes (sha256 output)
	LengthOp_REQUIRE_32_BYTES LengthOp = 7
	// REQUIRE_64_BYTES is like NONE, but will fail if the input is not exactly 64 bytes (sha512 output)
	LengthOp_REQUIRE_64_BYTES LengthOp = 8
)

var LengthOp_name = map[int32]string{
	0: "NO_PREFIX",
	1: "VAR_PROTO",
	2: "VAR_RLP",
	3: "FIXED32_BIG",
	4: "FIXED32_LITTLE",
	5: "FIXED64_BIG",
	6: "FIXED64_LITTLE",
	7: "REQUIRE_32_BYTES",
	8: "REQUIRE_64_BYTES",
}

var LengthOp_value = map[string]int32{
	"NO_PREFIX":        0,
	"VAR_PROTO":        1,
	"VAR_RLP":          2,
	"FIXED32_BIG":      3,
	"FIXED32_LITTLE":   4,
	"FIXED64_BIG":      5,
	"FIXED64_LITTLE":   6,
	"REQUIRE_32_BYTES": 7,
	"REQUIRE_64_BYTES": 8,
}

func (x LengthOp) String() string { _ = "STUB: not implemented"; return "" }

func (LengthOp) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// *
// ExistenceProof takes a key and a value and a set of steps to perform on it.
// The result of peforming all these steps will provide a "root hash", which can
// be compared to the value in a header.
//
// Since it is computationally infeasible to produce a hash collission for any of the used
// cryptographic hash functions, if someone can provide a series of operations to transform
// a given key and value into a root hash that matches some trusted root, these key and values
// must be in the referenced merkle tree.
//
// The only possible issue is maliablity in LeafOp, such as providing extra prefix data,
// which should be controlled by a spec. Eg. with lengthOp as NONE,
// prefix = FOO, key = BAR, value = CHOICE
// and
// prefix = F, key = OOBAR, value = CHOICE
// would produce the same value.
//
// With LengthOp this is tricker but not impossible. Which is why the "leafPrefixEqual" field
// in the ProofSpec is valuable to prevent this mutability. And why all trees should
// length-prefix the data before hashing it.
type ExistenceProof struct {
	Key   []byte     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Leaf  *LeafOp    `protobuf:"bytes,3,opt,name=leaf,proto3" json:"leaf,omitempty"`
	Path  []*InnerOp `protobuf:"bytes,4,rep,name=path,proto3" json:"path,omitempty"`
}

func (m *ExistenceProof) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ExistenceProof) String() string            { _ = "STUB: not implemented"; return "" }
func (*ExistenceProof) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ExistenceProof) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ExistenceProof) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ExistenceProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ExistenceProof) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ExistenceProof) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ExistenceProof) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ExistenceProof proto.InternalMessageInfo

func (m *ExistenceProof) GetKey() []byte { _ = "STUB: not implemented"; return nil }

func (m *ExistenceProof) GetValue() []byte { _ = "STUB: not implemented"; return nil }

func (m *ExistenceProof) GetLeaf() *LeafOp { _ = "STUB: not implemented"; return nil }

func (m *ExistenceProof) GetPath() []*InnerOp { _ = "STUB: not implemented"; return nil }

// NonExistenceProof takes a proof of two neighbors, one left of the desired key,
// one right of the desired key. If both proofs are valid AND they are neighbors,
// then there is no valid proof for the given key.
type NonExistenceProof struct {
	Key   []byte          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Left  *ExistenceProof `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	Right *ExistenceProof `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
}

func (m *NonExistenceProof) Reset()                    { _ = "STUB: not implemented"; return }
func (m *NonExistenceProof) String() string            { _ = "STUB: not implemented"; return "" }
func (*NonExistenceProof) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*NonExistenceProof) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *NonExistenceProof) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *NonExistenceProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NonExistenceProof) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *NonExistenceProof) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *NonExistenceProof) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_NonExistenceProof proto.InternalMessageInfo

func (m *NonExistenceProof) GetKey() []byte { _ = "STUB: not implemented"; return nil }

func (m *NonExistenceProof) GetLeft() *ExistenceProof { _ = "STUB: not implemented"; return nil }

func (m *NonExistenceProof) GetRight() *ExistenceProof { _ = "STUB: not implemented"; return nil }

// CommitmentProof is either an ExistenceProof or a NonExistenceProof, or a Batch of such messages
type CommitmentProof struct {
	// Types that are valid to be assigned to Proof:
	//	*CommitmentProof_Exist
	//	*CommitmentProof_Nonexist
	//	*CommitmentProof_Batch
	//	*CommitmentProof_Compressed
	Proof isCommitmentProof_Proof `protobuf_oneof:"proof"`
}

func (m *CommitmentProof) Reset()                    { _ = "STUB: not implemented"; return }
func (m *CommitmentProof) String() string            { _ = "STUB: not implemented"; return "" }
func (*CommitmentProof) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*CommitmentProof) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *CommitmentProof) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CommitmentProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CommitmentProof) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *CommitmentProof) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *CommitmentProof) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_CommitmentProof proto.InternalMessageInfo

type isCommitmentProof_Proof interface {
	isCommitmentProof_Proof()
	MarshalTo([]byte) (int, error)
	Size() int
}

type CommitmentProof_Exist struct {
	Exist *ExistenceProof `protobuf:"bytes,1,opt,name=exist,proto3,oneof" json:"exist,omitempty"`
}
type CommitmentProof_Nonexist struct {
	Nonexist *NonExistenceProof `protobuf:"bytes,2,opt,name=nonexist,proto3,oneof" json:"nonexist,omitempty"`
}
type CommitmentProof_Batch struct {
	Batch *BatchProof `protobuf:"bytes,3,opt,name=batch,proto3,oneof" json:"batch,omitempty"`
}
type CommitmentProof_Compressed struct {
	Compressed *CompressedBatchProof `protobuf:"bytes,4,opt,name=compressed,proto3,oneof" json:"compressed,omitempty"`
}

func (*CommitmentProof_Exist) isCommitmentProof_Proof()      { _ = "STUB: not implemented"; return }
func (*CommitmentProof_Nonexist) isCommitmentProof_Proof()   { _ = "STUB: not implemented"; return }
func (*CommitmentProof_Batch) isCommitmentProof_Proof()      { _ = "STUB: not implemented"; return }
func (*CommitmentProof_Compressed) isCommitmentProof_Proof() { _ = "STUB: not implemented"; return }

func (m *CommitmentProof) GetProof() isCommitmentProof_Proof {
	_ = "STUB: not implemented"
	return *new(isCommitmentProof_Proof)
}

func (m *CommitmentProof) GetExist() *ExistenceProof { _ = "STUB: not implemented"; return nil }

func (m *CommitmentProof) GetNonexist() *NonExistenceProof { _ = "STUB: not implemented"; return nil }

func (m *CommitmentProof) GetBatch() *BatchProof { _ = "STUB: not implemented"; return nil }

func (m *CommitmentProof) GetCompressed() *CompressedBatchProof {
	_ = "STUB: not implemented"
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CommitmentProof) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

// *
// LeafOp represents the raw key-value data we wish to prove, and
// must be flexible to represent the internal transformation from
// the original key-value pairs into the basis hash, for many existing
// merkle trees.
//
// key and value are passed in. So that the signature of this operation is:
// leafOp(key, value) -> output
//
// To process this, first prehash the keys and values if needed (ANY means no hash in this case):
// hkey = prehashKey(key)
// hvalue = prehashValue(value)
//
// Then combine the bytes, and hash it
// output = hash(prefix || length(hkey) || hkey || length(hvalue) || hvalue)
type LeafOp struct {
	Hash         HashOp   `protobuf:"varint,1,opt,name=hash,proto3,enum=ics23.HashOp" json:"hash,omitempty"`
	PrehashKey   HashOp   `protobuf:"varint,2,opt,name=prehash_key,json=prehashKey,proto3,enum=ics23.HashOp" json:"prehash_key,omitempty"`
	PrehashValue HashOp   `protobuf:"varint,3,opt,name=prehash_value,json=prehashValue,proto3,enum=ics23.HashOp" json:"prehash_value,omitempty"`
	Length       LengthOp `protobuf:"varint,4,opt,name=length,proto3,enum=ics23.LengthOp" json:"length,omitempty"`
	// prefix is a fixed bytes that may optionally be included at the beginning to differentiate
	// a leaf node from an inner node.
	Prefix []byte `protobuf:"bytes,5,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (m *LeafOp) Reset()                    { _ = "STUB: not implemented"; return }
func (m *LeafOp) String() string            { _ = "STUB: not implemented"; return "" }
func (*LeafOp) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*LeafOp) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *LeafOp) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *LeafOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *LeafOp) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *LeafOp) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *LeafOp) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_LeafOp proto.InternalMessageInfo

func (m *LeafOp) GetHash() HashOp { _ = "STUB: not implemented"; return *new(HashOp) }

func (m *LeafOp) GetPrehashKey() HashOp { _ = "STUB: not implemented"; return *new(HashOp) }

func (m *LeafOp) GetPrehashValue() HashOp { _ = "STUB: not implemented"; return *new(HashOp) }

func (m *LeafOp) GetLength() LengthOp { _ = "STUB: not implemented"; return *new(LengthOp) }

func (m *LeafOp) GetPrefix() []byte { _ = "STUB: not implemented"; return nil }

// *
// InnerOp represents a merkle-proof step that is not a leaf.
// It represents concatenating two children and hashing them to provide the next result.
//
// The result of the previous step is passed in, so the signature of this op is:
// innerOp(child) -> output
//
// The result of applying InnerOp should be:
// output = op.hash(op.prefix || child || op.suffix)
//
// where the || operator is concatenation of binary data,
// and child is the result of hashing all the tree below this step.
//
// Any special data, like prepending child with the length, or prepending the entire operation with
// some value to differentiate from leaf nodes, should be included in prefix and suffix.
// If either of prefix or suffix is empty, we just treat it as an empty string
type InnerOp struct {
	Hash   HashOp `protobuf:"varint,1,opt,name=hash,proto3,enum=ics23.HashOp" json:"hash,omitempty"`
	Prefix []byte `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Suffix []byte `protobuf:"bytes,3,opt,name=suffix,proto3" json:"suffix,omitempty"`
}

func (m *InnerOp) Reset()                    { _ = "STUB: not implemented"; return }
func (m *InnerOp) String() string            { _ = "STUB: not implemented"; return "" }
func (*InnerOp) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*InnerOp) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *InnerOp) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *InnerOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *InnerOp) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *InnerOp) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *InnerOp) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_InnerOp proto.InternalMessageInfo

func (m *InnerOp) GetHash() HashOp { _ = "STUB: not implemented"; return *new(HashOp) }

func (m *InnerOp) GetPrefix() []byte { _ = "STUB: not implemented"; return nil }

func (m *InnerOp) GetSuffix() []byte { _ = "STUB: not implemented"; return nil }

// *
// ProofSpec defines what the expected parameters are for a given proof type.
// This can be stored in the client and used to validate any incoming proofs.
//
// verify(ProofSpec, Proof) -> Proof | Error
//
// As demonstrated in tests, if we don't fix the algorithm used to calculate the
// LeafHash for a given tree, there are many possible key-value pairs that can
// generate a given hash (by interpretting the preimage differently).
// We need this for proper security, requires client knows a priori what
// tree format server uses. But not in code, rather a configuration object.
type ProofSpec struct {
	// any field in the ExistenceProof must be the same as in this spec.
	// except Prefix, which is just the first bytes of prefix (spec can be longer)
	LeafSpec  *LeafOp    `protobuf:"bytes,1,opt,name=leaf_spec,json=leafSpec,proto3" json:"leaf_spec,omitempty"`
	InnerSpec *InnerSpec `protobuf:"bytes,2,opt,name=inner_spec,json=innerSpec,proto3" json:"inner_spec,omitempty"`
	// max_depth (if > 0) is the maximum number of InnerOps allowed (mainly for fixed-depth tries)
	MaxDepth int32 `protobuf:"varint,3,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	// min_depth (if > 0) is the minimum number of InnerOps allowed (mainly for fixed-depth tries)
	MinDepth int32 `protobuf:"varint,4,opt,name=min_depth,json=minDepth,proto3" json:"min_depth,omitempty"`
}

func (m *ProofSpec) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ProofSpec) String() string            { _ = "STUB: not implemented"; return "" }
func (*ProofSpec) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ProofSpec) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ProofSpec) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ProofSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ProofSpec) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ProofSpec) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ProofSpec) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ProofSpec proto.InternalMessageInfo

func (m *ProofSpec) GetLeafSpec() *LeafOp { _ = "STUB: not implemented"; return nil }

func (m *ProofSpec) GetInnerSpec() *InnerSpec { _ = "STUB: not implemented"; return nil }

func (m *ProofSpec) GetMaxDepth() int32 { _ = "STUB: not implemented"; return 0 }

func (m *ProofSpec) GetMinDepth() int32 { _ = "STUB: not implemented"; return 0 }

// InnerSpec contains all store-specific structure info to determine if two proofs from a
// given store are neighbors.
//
// This enables:
//
// isLeftMost(spec: InnerSpec, op: InnerOp)
// isRightMost(spec: InnerSpec, op: InnerOp)
// isLeftNeighbor(spec: InnerSpec, left: InnerOp, right: InnerOp)
type InnerSpec struct {
	// Child order is the ordering of the children node, must count from 0
	// iavl tree is [0, 1] (left then right)
	// merk is [0, 2, 1] (left, right, here)
	ChildOrder      []int32 `protobuf:"varint,1,rep,packed,name=child_order,json=childOrder,proto3" json:"child_order,omitempty"`
	ChildSize       int32   `protobuf:"varint,2,opt,name=child_size,json=childSize,proto3" json:"child_size,omitempty"`
	MinPrefixLength int32   `protobuf:"varint,3,opt,name=min_prefix_length,json=minPrefixLength,proto3" json:"min_prefix_length,omitempty"`
	MaxPrefixLength int32   `protobuf:"varint,4,opt,name=max_prefix_length,json=maxPrefixLength,proto3" json:"max_prefix_length,omitempty"`
	// empty child is the prehash image that is used when one child is nil (eg. 20 bytes of 0)
	EmptyChild []byte `protobuf:"bytes,5,opt,name=empty_child,json=emptyChild,proto3" json:"empty_child,omitempty"`
	// hash is the algorithm that must be used for each InnerOp
	Hash HashOp `protobuf:"varint,6,opt,name=hash,proto3,enum=ics23.HashOp" json:"hash,omitempty"`
}

func (m *InnerSpec) Reset()                    { _ = "STUB: not implemented"; return }
func (m *InnerSpec) String() string            { _ = "STUB: not implemented"; return "" }
func (*InnerSpec) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*InnerSpec) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *InnerSpec) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *InnerSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *InnerSpec) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *InnerSpec) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *InnerSpec) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_InnerSpec proto.InternalMessageInfo

func (m *InnerSpec) GetChildOrder() []int32 { _ = "STUB: not implemented"; return nil }

func (m *InnerSpec) GetChildSize() int32 { _ = "STUB: not implemented"; return 0 }

func (m *InnerSpec) GetMinPrefixLength() int32 { _ = "STUB: not implemented"; return 0 }

func (m *InnerSpec) GetMaxPrefixLength() int32 { _ = "STUB: not implemented"; return 0 }

func (m *InnerSpec) GetEmptyChild() []byte { _ = "STUB: not implemented"; return nil }

func (m *InnerSpec) GetHash() HashOp { _ = "STUB: not implemented"; return *new(HashOp) }

// BatchProof is a group of multiple proof types than can be compressed
type BatchProof struct {
	Entries []*BatchEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (m *BatchProof) Reset()                    { _ = "STUB: not implemented"; return }
func (m *BatchProof) String() string            { _ = "STUB: not implemented"; return "" }
func (*BatchProof) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*BatchProof) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *BatchProof) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BatchProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BatchProof) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *BatchProof) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *BatchProof) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_BatchProof proto.InternalMessageInfo

func (m *BatchProof) GetEntries() []*BatchEntry { _ = "STUB: not implemented"; return nil }

// Use BatchEntry not CommitmentProof, to avoid recursion
type BatchEntry struct {
	// Types that are valid to be assigned to Proof:
	//	*BatchEntry_Exist
	//	*BatchEntry_Nonexist
	Proof isBatchEntry_Proof `protobuf_oneof:"proof"`
}

func (m *BatchEntry) Reset()                    { _ = "STUB: not implemented"; return }
func (m *BatchEntry) String() string            { _ = "STUB: not implemented"; return "" }
func (*BatchEntry) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*BatchEntry) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *BatchEntry) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BatchEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *BatchEntry) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *BatchEntry) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *BatchEntry) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_BatchEntry proto.InternalMessageInfo

type isBatchEntry_Proof interface {
	isBatchEntry_Proof()
	MarshalTo([]byte) (int, error)
	Size() int
}

type BatchEntry_Exist struct {
	Exist *ExistenceProof `protobuf:"bytes,1,opt,name=exist,proto3,oneof" json:"exist,omitempty"`
}
type BatchEntry_Nonexist struct {
	Nonexist *NonExistenceProof `protobuf:"bytes,2,opt,name=nonexist,proto3,oneof" json:"nonexist,omitempty"`
}

func (*BatchEntry_Exist) isBatchEntry_Proof()    { _ = "STUB: not implemented"; return }
func (*BatchEntry_Nonexist) isBatchEntry_Proof() { _ = "STUB: not implemented"; return }

func (m *BatchEntry) GetProof() isBatchEntry_Proof {
	_ = "STUB: not implemented"
	return *new(isBatchEntry_Proof)
}

func (m *BatchEntry) GetExist() *ExistenceProof { _ = "STUB: not implemented"; return nil }

func (m *BatchEntry) GetNonexist() *NonExistenceProof { _ = "STUB: not implemented"; return nil }

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BatchEntry) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

type CompressedBatchProof struct {
	Entries      []*CompressedBatchEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	LookupInners []*InnerOp              `protobuf:"bytes,2,rep,name=lookup_inners,json=lookupInners,proto3" json:"lookup_inners,omitempty"`
}

func (m *CompressedBatchProof) Reset()         { _ = "STUB: not implemented"; return }
func (m *CompressedBatchProof) String() string { _ = "STUB: not implemented"; return "" }
func (*CompressedBatchProof) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*CompressedBatchProof) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CompressedBatchProof) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CompressedBatchProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CompressedBatchProof) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *CompressedBatchProof) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *CompressedBatchProof) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_CompressedBatchProof proto.InternalMessageInfo

func (m *CompressedBatchProof) GetEntries() []*CompressedBatchEntry {
	_ = "STUB: not implemented"
	return nil
}

func (m *CompressedBatchProof) GetLookupInners() []*InnerOp { _ = "STUB: not implemented"; return nil }

// Use BatchEntry not CommitmentProof, to avoid recursion
type CompressedBatchEntry struct {
	// Types that are valid to be assigned to Proof:
	//	*CompressedBatchEntry_Exist
	//	*CompressedBatchEntry_Nonexist
	Proof isCompressedBatchEntry_Proof `protobuf_oneof:"proof"`
}

func (m *CompressedBatchEntry) Reset()         { _ = "STUB: not implemented"; return }
func (m *CompressedBatchEntry) String() string { _ = "STUB: not implemented"; return "" }
func (*CompressedBatchEntry) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*CompressedBatchEntry) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CompressedBatchEntry) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CompressedBatchEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CompressedBatchEntry) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *CompressedBatchEntry) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *CompressedBatchEntry) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_CompressedBatchEntry proto.InternalMessageInfo

type isCompressedBatchEntry_Proof interface {
	isCompressedBatchEntry_Proof()
	MarshalTo([]byte) (int, error)
	Size() int
}

type CompressedBatchEntry_Exist struct {
	Exist *CompressedExistenceProof `protobuf:"bytes,1,opt,name=exist,proto3,oneof" json:"exist,omitempty"`
}
type CompressedBatchEntry_Nonexist struct {
	Nonexist *CompressedNonExistenceProof `protobuf:"bytes,2,opt,name=nonexist,proto3,oneof" json:"nonexist,omitempty"`
}

func (*CompressedBatchEntry_Exist) isCompressedBatchEntry_Proof() {
	_ = "STUB: not implemented"
	return
}
func (*CompressedBatchEntry_Nonexist) isCompressedBatchEntry_Proof() {
	_ = "STUB: not implemented"
	return
}

func (m *CompressedBatchEntry) GetProof() isCompressedBatchEntry_Proof {
	_ = "STUB: not implemented"
	return *new(isCompressedBatchEntry_Proof)
}

func (m *CompressedBatchEntry) GetExist() *CompressedExistenceProof {
	_ = "STUB: not implemented"
	return nil
}

func (m *CompressedBatchEntry) GetNonexist() *CompressedNonExistenceProof {
	_ = "STUB: not implemented"
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CompressedBatchEntry) XXX_OneofWrappers() []interface{} {
	_ = "STUB: not implemented"
	return nil
}

type CompressedExistenceProof struct {
	Key   []byte  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Leaf  *LeafOp `protobuf:"bytes,3,opt,name=leaf,proto3" json:"leaf,omitempty"`
	// these are indexes into the lookup_inners table in CompressedBatchProof
	Path []int32 `protobuf:"varint,4,rep,packed,name=path,proto3" json:"path,omitempty"`
}

func (m *CompressedExistenceProof) Reset()         { _ = "STUB: not implemented"; return }
func (m *CompressedExistenceProof) String() string { _ = "STUB: not implemented"; return "" }
func (*CompressedExistenceProof) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*CompressedExistenceProof) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CompressedExistenceProof) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CompressedExistenceProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CompressedExistenceProof) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *CompressedExistenceProof) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *CompressedExistenceProof) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_CompressedExistenceProof proto.InternalMessageInfo

func (m *CompressedExistenceProof) GetKey() []byte { _ = "STUB: not implemented"; return nil }

func (m *CompressedExistenceProof) GetValue() []byte { _ = "STUB: not implemented"; return nil }

func (m *CompressedExistenceProof) GetLeaf() *LeafOp { _ = "STUB: not implemented"; return nil }

func (m *CompressedExistenceProof) GetPath() []int32 { _ = "STUB: not implemented"; return nil }

type CompressedNonExistenceProof struct {
	Key   []byte                    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Left  *CompressedExistenceProof `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	Right *CompressedExistenceProof `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
}

func (m *CompressedNonExistenceProof) Reset()         { _ = "STUB: not implemented"; return }
func (m *CompressedNonExistenceProof) String() string { _ = "STUB: not implemented"; return "" }
func (*CompressedNonExistenceProof) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*CompressedNonExistenceProof) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CompressedNonExistenceProof) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CompressedNonExistenceProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CompressedNonExistenceProof) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *CompressedNonExistenceProof) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *CompressedNonExistenceProof) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_CompressedNonExistenceProof proto.InternalMessageInfo

func (m *CompressedNonExistenceProof) GetKey() []byte { _ = "STUB: not implemented"; return nil }

func (m *CompressedNonExistenceProof) GetLeft() *CompressedExistenceProof {
	_ = "STUB: not implemented"
	return nil
}

func (m *CompressedNonExistenceProof) GetRight() *CompressedExistenceProof {
	_ = "STUB: not implemented"
	return nil
}

func init() {
	proto.RegisterEnum("ics23.HashOp", HashOp_name, HashOp_value)
	proto.RegisterEnum("ics23.LengthOp", LengthOp_name, LengthOp_value)
	proto.RegisterType((*ExistenceProof)(nil), "ics23.ExistenceProof")
	proto.RegisterType((*NonExistenceProof)(nil), "ics23.NonExistenceProof")
	proto.RegisterType((*CommitmentProof)(nil), "ics23.CommitmentProof")
	proto.RegisterType((*LeafOp)(nil), "ics23.LeafOp")
	proto.RegisterType((*InnerOp)(nil), "ics23.InnerOp")
	proto.RegisterType((*ProofSpec)(nil), "ics23.ProofSpec")
	proto.RegisterType((*InnerSpec)(nil), "ics23.InnerSpec")
	proto.RegisterType((*BatchProof)(nil), "ics23.BatchProof")
	proto.RegisterType((*BatchEntry)(nil), "ics23.BatchEntry")
	proto.RegisterType((*CompressedBatchProof)(nil), "ics23.CompressedBatchProof")
	proto.RegisterType((*CompressedBatchEntry)(nil), "ics23.CompressedBatchEntry")
	proto.RegisterType((*CompressedExistenceProof)(nil), "ics23.CompressedExistenceProof")
	proto.RegisterType((*CompressedNonExistenceProof)(nil), "ics23.CompressedNonExistenceProof")
}

func init() { proto.RegisterFile("proofs.proto", fileDescriptor_855156e15e7b8e99) }

var fileDescriptor_855156e15e7b8e99 = []byte{
	// 940 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x4b, 0x6f, 0xe3, 0x54,
	0x14, 0xce, 0x4d, 0x62, 0x27, 0x39, 0x69, 0x53, 0xf7, 0xaa, 0x20, 0x4b, 0x15, 0x69, 0xf1, 0x86,
	0x4e, 0x47, 0x14, 0x26, 0x99, 0x06, 0xb1, 0x40, 0xa2, 0x49, 0x3d, 0xc4, 0x6a, 0x69, 0xc2, 0x4d,
	0x18, 0x0d, 0x12, 0x92, 0xe5, 0x49, 0x6f, 0x26, 0xd6, 0x24, 0xb6, 0x65, 0xbb, 0x28, 0x19, 0x81,
	0x90, 0xf8, 0x05, 0xac, 0x61, 0xc7, 0x96, 0x3f, 0xc2, 0xb2, 0x4b, 0x96, 0xa8, 0x5d, 0xb0, 0xe0,
	0x4f, 0xa0, 0xfb, 0x88, 0x9b, 0x27, 0xed, 0x02, 0xcd, 0xee, 0x9e, 0xef, 0x7c, 0xe7, 0x71, 0xcf,
	0xc3, 0xd7, 0xb0, 0x11, 0x84, 0xbe, 0xdf, 0x8f, 0x8e, 0x82, 0xd0, 0x8f, 0x7d, 0xac, 0xb8, 0xbd,
	0xa8, 0x52, 0x35, 0x7e, 0x84, 0x92, 0x39, 0x76, 0xa3, 0x98, 0x7a, 0x3d, 0xda, 0x66, 0x7a, 0xac,
	0x41, 0xe6, 0x35, 0x9d, 0xe8, 0x68, 0x1f, 0x1d, 0x6c, 0x10, 0x76, 0xc4, 0x3b, 0xa0, 0x7c, 0xe7,
	0x0c, 0xaf, 0xa8, 0x9e, 0xe6, 0x98, 0x10, 0xf0, 0xfb, 0x90, 0x1d, 0x52, 0xa7, 0xaf, 0x67, 0xf6,
	0xd1, 0x41, 0xb1, 0xb2, 0x79, 0xc4, 0xfd, 0x1d, 0x9d, 0x53, 0xa7, 0xdf, 0x0a, 0x08, 0x57, 0x61,
	0x03, 0xb2, 0x81, 0x13, 0x0f, 0xf4, 0xec, 0x7e, 0xe6, 0xa0, 0x58, 0x29, 0x49, 0x8a, 0xe5, 0x79,
	0x34, 0x64, 0x1c, 0xa6, 0x33, 0x7e, 0x80, 0xed, 0x0b, 0xdf, 0xbb, 0x37, 0x87, 0x47, 0x2c, 0x5a,
	0x3f, 0xe6, 0x29, 0x14, 0x2b, 0xef, 0x48, 0x57, 0xf3, 0x66, 0x84, 0x53, 0xf0, 0x63, 0x50, 0x42,
	0xf7, 0xd5, 0x20, 0x96, 0x99, 0xad, 0xe1, 0x0a, 0x8e, 0xf1, 0x0f, 0x82, 0xad, 0x86, 0x3f, 0x1a,
	0xb9, 0xf1, 0x88, 0x7a, 0xb1, 0x88, 0xfe, 0x21, 0x28, 0x94, 0x91, 0x79, 0xfc, 0x75, 0x0e, 0x9a,
	0x29, 0x22, 0x58, 0xb8, 0x06, 0x79, 0xcf, 0xf7, 0x84, 0x85, 0x48, 0x4f, 0x97, 0x16, 0x4b, 0x17,
	0x6b, 0xa6, 0x48, 0xc2, 0xc5, 0x8f, 0x40, 0x79, 0xe9, 0xc4, 0xbd, 0x81, 0xcc, 0x73, 0x5b, 0x1a,
	0xd5, 0x19, 0x96, 0x84, 0xe0, 0x0c, 0xfc, 0x19, 0x40, 0xcf, 0x1f, 0x05, 0x21, 0x8d, 0x22, 0x7a,
	0xa9, 0x67, 0x39, 0x7f, 0x57, 0xf2, 0x1b, 0x89, 0x62, 0xce, 0x72, 0xc6, 0xa0, 0x9e, 0x03, 0x85,
	0xf7, 0xde, 0xb8, 0x46, 0xa0, 0x8a, 0x0e, 0xb1, 0xf6, 0x0d, 0x9c, 0x68, 0xc0, 0xef, 0x58, 0x4a,
	0xda, 0xd7, 0x74, 0xa2, 0x01, 0x6b, 0x0d, 0x53, 0xe1, 0x23, 0x28, 0x06, 0x21, 0x65, 0x47, 0x9b,
	0x75, 0x23, 0xbd, 0x8a, 0x09, 0x92, 0x71, 0x46, 0x27, 0xb8, 0x02, 0x9b, 0x53, 0xbe, 0x98, 0x97,
	0xcc, 0x2a, 0x8b, 0x0d, 0xc9, 0x79, 0xce, 0xa7, 0xe8, 0x03, 0x50, 0x87, 0xd4, 0x7b, 0xc5, 0x87,
	0x84, 0x91, 0xb7, 0x92, 0x39, 0x62, 0x60, 0x2b, 0x20, 0x52, 0x8d, 0xdf, 0x05, 0x35, 0x08, 0x69,
	0xdf, 0x1d, 0xeb, 0x0a, 0x9f, 0x0a, 0x29, 0x19, 0xdf, 0x42, 0x4e, 0x0e, 0xd4, 0x43, 0xae, 0x74,
	0xe7, 0x25, 0x3d, 0xeb, 0x85, 0xe1, 0xd1, 0x55, 0x9f, 0xe1, 0x19, 0x81, 0x0b, 0xc9, 0xf8, 0x0d,
	0x41, 0x81, 0x57, 0xb4, 0x13, 0xd0, 0x1e, 0x3e, 0x84, 0x02, 0x9b, 0x6b, 0x3b, 0x0a, 0x68, 0x4f,
	0x0e, 0xc7, 0xc2, 0xdc, 0xe7, 0x99, 0x9e, 0x73, 0x3f, 0x02, 0x70, 0x59, 0x5e, 0x82, 0x2c, 0xe6,
	0x42, 0x9b, 0xdd, 0x00, 0xc6, 0x22, 0x05, 0x77, 0x7a, 0xc4, 0xbb, 0x50, 0x18, 0x39, 0x63, 0xfb,
	0x92, 0x06, 0xb1, 0x18, 0x09, 0x85, 0xe4, 0x47, 0xce, 0xf8, 0x94, 0xc9, 0x5c, 0xe9, 0x7a, 0x52,
	0x99, 0x95, 0x4a, 0xd7, 0xe3, 0x4a, 0xe3, 0x6f, 0x04, 0x85, 0xc4, 0x25, 0xde, 0x83, 0x62, 0x6f,
	0xe0, 0x0e, 0x2f, 0x6d, 0x3f, 0xbc, 0xa4, 0xa1, 0x8e, 0xf6, 0x33, 0x07, 0x0a, 0x01, 0x0e, 0xb5,
	0x18, 0x82, 0xdf, 0x03, 0x21, 0xd9, 0x91, 0xfb, 0x46, 0xec, 0xb4, 0x42, 0x0a, 0x1c, 0xe9, 0xb8,
	0x6f, 0x28, 0x3e, 0x84, 0x6d, 0x16, 0x4a, 0x14, 0xc6, 0x96, 0xcd, 0x11, 0xf9, 0x6c, 0x8d, 0x5c,
	0xaf, 0xcd, 0x71, 0xd1, 0x1e, 0xce, 0x75, 0xc6, 0x0b, 0xdc, 0xac, 0xe4, 0x3a, 0xe3, 0x39, 0xee,
	0x1e, 0x14, 0xe9, 0x28, 0x88, 0x27, 0x36, 0x0f, 0x25, 0xbb, 0x08, 0x1c, 0x6a, 0x30, 0x24, 0x69,
	0x9f, 0xba, 0xb6, 0x7d, 0xc6, 0xa7, 0x00, 0x77, 0x43, 0x8e, 0x1f, 0x43, 0x8e, 0x7a, 0x71, 0xe8,
	0xd2, 0x88, 0xdf, 0x72, 0x61, 0x85, 0x4c, 0x2f, 0x0e, 0x27, 0x64, 0xca, 0x30, 0xbe, 0x97, 0xa6,
	0x1c, 0x7e, 0x4b, 0x2b, 0x7e, 0xb7, 0x78, 0x3f, 0x21, 0xd8, 0x59, 0xb5, 0xa8, 0xf8, 0x78, 0xf1,
	0x0e, 0x6b, 0xd6, 0x7a, 0xfe, 0x36, 0xb8, 0x0a, 0x9b, 0x43, 0xdf, 0x7f, 0x7d, 0x15, 0xd8, 0x7c,
	0x80, 0x22, 0x3d, 0xbd, 0xf2, 0x13, 0xbb, 0x21, 0x48, 0x5c, 0x8c, 0x8c, 0x5f, 0x96, 0x93, 0x10,
	0xd5, 0xf8, 0x64, 0xbe, 0x1a, 0x7b, 0x4b, 0x29, 0xac, 0xab, 0xcb, 0xe7, 0x4b, 0x75, 0x31, 0x96,
	0x6c, 0x1f, 0x58, 0xa1, 0x09, 0xe8, 0xeb, 0xe2, 0xfd, 0x9f, 0x4f, 0x12, 0x9e, 0x79, 0x92, 0x14,
	0xf9, 0x04, 0xfd, 0x8a, 0x60, 0xf7, 0x3f, 0xf2, 0x5d, 0x11, 0xbe, 0x3a, 0xf7, 0x1a, 0xdd, 0x57,
	0x2f, 0xf9, 0x2e, 0x1d, 0xcf, 0xbf, 0x4b, 0xf7, 0x5a, 0x09, 0xf6, 0x21, 0x05, 0x55, 0xec, 0x00,
	0x2e, 0x42, 0xee, 0xa2, 0x65, 0x37, 0x4f, 0x3a, 0x4d, 0x2d, 0x85, 0x01, 0xd4, 0x4e, 0xf3, 0xa4,
	0x72, 0x5c, 0xd3, 0x90, 0x3c, 0x1f, 0x3f, 0xa9, 0x68, 0x69, 0x76, 0x3e, 0x33, 0x1b, 0x8d, 0x93,
	0x33, 0x2d, 0x83, 0x37, 0xa1, 0x40, 0xac, 0xb6, 0xf9, 0xe5, 0xe9, 0x93, 0xda, 0xc7, 0x5a, 0x96,
	0xd9, 0xd7, 0xad, 0x6e, 0xa3, 0x65, 0x5d, 0x68, 0x0a, 0x2e, 0x01, 0x08, 0x1b, 0x9b, 0xf9, 0x50,
	0x0f, 0x7f, 0x47, 0x90, 0x9f, 0x7e, 0x74, 0x99, 0xe1, 0x45, 0xcb, 0x6e, 0x13, 0xf3, 0x99, 0xf5,
	0x42, 0x4b, 0x31, 0xf1, 0xf9, 0x09, 0xb1, 0xdb, 0xa4, 0xd5, 0x6d, 0x69, 0x88, 0xf9, 0x61, 0x22,
	0x39, 0x6f, 0x6b, 0x69, 0xbc, 0x05, 0xc5, 0x67, 0xd6, 0x0b, 0xf3, 0xb4, 0x5a, 0xb1, 0xeb, 0xd6,
	0x17, 0x5a, 0x06, 0x63, 0x28, 0x4d, 0x81, 0x73, 0xab, 0xdb, 0x3d, 0x37, 0xb5, 0x6c, 0x42, 0xaa,
	0x3d, 0xe5, 0x24, 0x25, 0x21, 0xd5, 0x9e, 0x4e, 0x49, 0x2a, 0xde, 0x01, 0x8d, 0x98, 0x5f, 0x7d,
	0x6d, 0x11, 0xd3, 0x66, 0xce, 0xbe, 0xe9, 0x9a, 0x1d, 0x2d, 0x37, 0x8b, 0x32, 0x6b, 0x8e, 0xe6,
	0xeb, 0xfa, 0x1f, 0x37, 0x65, 0x74, 0x7d, 0x53, 0x46, 0x7f, 0xdd, 0x94, 0xd1, 0xcf, 0xb7, 0xe5,
	0xd4, 0xf5, 0x6d, 0x39, 0xf5, 0xe7, 0x6d, 0x39, 0xf5, 0x52, 0xe5, 0xbf, 0x37, 0xd5, 0x7f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xd4, 0x7d, 0x87, 0x8f, 0xee, 0x08, 0x00, 0x00,
}

func (m *ExistenceProof) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ExistenceProof) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ExistenceProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *NonExistenceProof) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *NonExistenceProof) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *NonExistenceProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CommitmentProof) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CommitmentProof) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CommitmentProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CommitmentProof_Exist) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CommitmentProof_Exist) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CommitmentProof_Nonexist) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CommitmentProof_Nonexist) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CommitmentProof_Batch) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CommitmentProof_Batch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CommitmentProof_Compressed) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CommitmentProof_Compressed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *LeafOp) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *LeafOp) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *LeafOp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InnerOp) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *InnerOp) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *InnerOp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ProofSpec) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *ProofSpec) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ProofSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InnerSpec) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *InnerSpec) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *InnerSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BatchProof) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *BatchProof) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *BatchProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BatchEntry) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *BatchEntry) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *BatchEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BatchEntry_Exist) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BatchEntry_Exist) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BatchEntry_Nonexist) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *BatchEntry_Nonexist) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompressedBatchProof) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CompressedBatchProof) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompressedBatchProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompressedBatchEntry) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CompressedBatchEntry) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompressedBatchEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompressedBatchEntry_Exist) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompressedBatchEntry_Exist) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompressedBatchEntry_Nonexist) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompressedBatchEntry_Nonexist) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompressedExistenceProof) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CompressedExistenceProof) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompressedExistenceProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompressedNonExistenceProof) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CompressedNonExistenceProof) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CompressedNonExistenceProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintProofs(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *ExistenceProof) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *NonExistenceProof) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CommitmentProof) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CommitmentProof_Exist) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CommitmentProof_Nonexist) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CommitmentProof_Batch) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CommitmentProof_Compressed) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *LeafOp) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *InnerOp) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ProofSpec) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *InnerSpec) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BatchProof) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BatchEntry) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BatchEntry_Exist) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *BatchEntry_Nonexist) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CompressedBatchProof) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CompressedBatchEntry) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CompressedBatchEntry_Exist) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CompressedBatchEntry_Nonexist) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CompressedExistenceProof) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CompressedNonExistenceProof) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovProofs(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozProofs(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ExistenceProof) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *NonExistenceProof) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CommitmentProof) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *LeafOp) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *InnerOp) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ProofSpec) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *InnerSpec) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BatchProof) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *BatchEntry) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CompressedBatchProof) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CompressedBatchEntry) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CompressedExistenceProof) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CompressedNonExistenceProof) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func skipProofs(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthProofs        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProofs          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProofs = fmt.Errorf("proto: unexpected end of group")
)
