// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/evidence/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
	types "github.com/sei-protocol/sei-chain/sei-cosmos/codec/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the evidence module's genesis state.
type GenesisState struct {
	// evidence defines all the evidence at genesis.
	Evidence []*types.Any `protobuf:"bytes,1,rep,name=evidence,proto3" json:"evidence,omitempty"`
}

func (m *GenesisState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *GenesisState) String() string            { _ = "STUB: not implemented"; return "" }
func (*GenesisState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*GenesisState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *GenesisState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GenesisState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *GenesisState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *GenesisState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetEvidence() []*types.Any { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*GenesisState)(nil), "cosmos.evidence.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("cosmos/evidence/v1beta1/genesis.proto", fileDescriptor_c610c52c26e0e202)
}

var fileDescriptor_c610c52c26e0e202 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4d, 0xce, 0x2f, 0xce,
	0xcd, 0x2f, 0xd6, 0x4f, 0x2d, 0xcb, 0x4c, 0x49, 0xcd, 0x4b, 0x4e, 0xd5, 0x2f, 0x33, 0x4c, 0x4a,
	0x2d, 0x49, 0x34, 0xd4, 0x4f, 0x4f, 0xcd, 0x4b, 0x2d, 0xce, 0x2c, 0xd6, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x12, 0x87, 0x28, 0xd3, 0x83, 0x29, 0xd3, 0x83, 0x2a, 0x93, 0x92, 0x4c, 0xcf, 0xcf,
	0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x2b, 0x4b, 0x2a, 0x4d, 0xd3, 0x4f, 0xcc, 0xab, 0x84, 0xe8, 0x51,
	0x72, 0xe0, 0xe2, 0x71, 0x87, 0x18, 0x12, 0x5c, 0x92, 0x58, 0x92, 0x2a, 0x64, 0xc0, 0xc5, 0x01,
	0xd3, 0x2e, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xa2, 0x07, 0xd1, 0xad, 0x07, 0xd3, 0xad,
	0xe7, 0x98, 0x57, 0x19, 0x04, 0x57, 0xe5, 0x14, 0x7e, 0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72,
	0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7, 0x70, 0xe1, 0xb1, 0x1c, 0xc3, 0x8d, 0xc7,
	0x72, 0x0c, 0x51, 0xb6, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xc5,
	0xa9, 0x99, 0xba, 0x60, 0x03, 0x92, 0xf3, 0x73, 0xc0, 0x9c, 0xe4, 0x8c, 0xc4, 0xcc, 0x3c, 0x08,
	0x0b, 0xe2, 0xb9, 0x0a, 0x84, 0xf7, 0x4a, 0x2a, 0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0, 0xea, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xee, 0xf3, 0xc9, 0xfe, 0x00, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *GenesisState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovGenesis(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozGenesis(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *GenesisState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipGenesis(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
