// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/bank/v1beta1/bank.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	github_com_sei_protocol_sei_chain_sei_cosmos_types "github.com/sei-protocol/sei-chain/sei-cosmos/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the bank module.
type Params struct {
	SendEnabled        []*SendEnabled `protobuf:"bytes,1,rep,name=send_enabled,json=sendEnabled,proto3" json:"send_enabled,omitempty" yaml:"send_enabled,omitempty"`
	DefaultSendEnabled bool           `protobuf:"varint,2,opt,name=default_send_enabled,json=defaultSendEnabled,proto3" json:"default_send_enabled,omitempty" yaml:"default_send_enabled,omitempty"`
}

func (m *Params) Reset()                    { _ = "STUB: not implemented"; return }
func (*Params) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Params) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Params) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Params) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Params) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Params) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetSendEnabled() []*SendEnabled { _ = "STUB: not implemented"; return nil }

func (m *Params) GetDefaultSendEnabled() bool { _ = "STUB: not implemented"; return false }

// SendEnabled maps coin denom to a send_enabled status (whether a denom is
// sendable).
type SendEnabled struct {
	Denom   string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Enabled bool   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (m *SendEnabled) Reset()                    { _ = "STUB: not implemented"; return }
func (*SendEnabled) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SendEnabled) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SendEnabled) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SendEnabled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SendEnabled) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SendEnabled) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SendEnabled) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SendEnabled proto.InternalMessageInfo

func (m *SendEnabled) GetDenom() string { _ = "STUB: not implemented"; return "" }

func (m *SendEnabled) GetEnabled() bool { _ = "STUB: not implemented"; return false }

// Input models transaction input.
type Input struct {
	Address string                                                   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Coins   github_com_sei_protocol_sei_chain_sei_cosmos_types.Coins `protobuf:"bytes,2,rep,name=coins,proto3,castrepeated=github.com/sei-protocol/sei-chain/sei-cosmos/types.Coins" json:"coins"`
}

func (m *Input) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Input) String() string            { _ = "STUB: not implemented"; return "" }
func (*Input) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Input) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Input) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Input) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Input) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Input) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Input proto.InternalMessageInfo

// Output models transaction outputs.
type Output struct {
	Address string                                                   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Coins   github_com_sei_protocol_sei_chain_sei_cosmos_types.Coins `protobuf:"bytes,2,rep,name=coins,proto3,castrepeated=github.com/sei-protocol/sei-chain/sei-cosmos/types.Coins" json:"coins"`
}

func (m *Output) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Output) String() string            { _ = "STUB: not implemented"; return "" }
func (*Output) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Output) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Output) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Output) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Output) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Output) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Output proto.InternalMessageInfo

// Supply represents a struct that passively keeps track of the total supply
// amounts in the network.
// This message is deprecated now that supply is indexed by denom.
//
// Deprecated: Do not use.
type Supply struct {
	Total github_com_sei_protocol_sei_chain_sei_cosmos_types.Coins `protobuf:"bytes,1,rep,name=total,proto3,castrepeated=github.com/sei-protocol/sei-chain/sei-cosmos/types.Coins" json:"total"`
}

func (m *Supply) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Supply) String() string            { _ = "STUB: not implemented"; return "" }
func (*Supply) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Supply) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Supply) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Supply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Supply) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Supply) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Supply) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Supply proto.InternalMessageInfo

// DenomUnit represents a struct that describes a given
// denomination unit of the basic token.
type DenomUnit struct {
	// denom represents the string name of the given denom unit (e.g uatom).
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	// exponent represents power of 10 exponent that one must
	// raise the base_denom to in order to equal the given DenomUnit's denom
	// 1 denom = 1^exponent base_denom
	// (e.g. with a base_denom of uatom, one can create a DenomUnit of 'atom' with
	// exponent = 6, thus: 1 atom = 10^6 uatom).
	Exponent uint32 `protobuf:"varint,2,opt,name=exponent,proto3" json:"exponent,omitempty"`
	// aliases is a list of string aliases for the given denom
	Aliases []string `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
}

func (m *DenomUnit) Reset()                    { _ = "STUB: not implemented"; return }
func (m *DenomUnit) String() string            { _ = "STUB: not implemented"; return "" }
func (*DenomUnit) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*DenomUnit) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *DenomUnit) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *DenomUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DenomUnit) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *DenomUnit) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *DenomUnit) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_DenomUnit proto.InternalMessageInfo

func (m *DenomUnit) GetDenom() string { _ = "STUB: not implemented"; return "" }

func (m *DenomUnit) GetExponent() uint32 { _ = "STUB: not implemented"; return 0 }

func (m *DenomUnit) GetAliases() []string { _ = "STUB: not implemented"; return nil }

// Metadata represents a struct that describes
// a basic token.
type Metadata struct {
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// denom_units represents the list of DenomUnit's for a given coin
	DenomUnits []*DenomUnit `protobuf:"bytes,2,rep,name=denom_units,json=denomUnits,proto3" json:"denom_units,omitempty"`
	// base represents the base denom (should be the DenomUnit with exponent = 0).
	Base string `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
	// display indicates the suggested denom that should be
	// displayed in clients.
	Display string `protobuf:"bytes,4,opt,name=display,proto3" json:"display,omitempty"`
	// name defines the name of the token (eg: Cosmos Atom)
	//
	// Since: cosmos-sdk 0.43
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// symbol is the token symbol usually shown on exchanges (eg: ATOM). This can
	// be the same as the display.
	//
	// Since: cosmos-sdk 0.43
	Symbol string `protobuf:"bytes,6,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (m *Metadata) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Metadata) String() string            { _ = "STUB: not implemented"; return "" }
func (*Metadata) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Metadata) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Metadata) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Metadata) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Metadata) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Metadata) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetDescription() string { _ = "STUB: not implemented"; return "" }

func (m *Metadata) GetDenomUnits() []*DenomUnit { _ = "STUB: not implemented"; return nil }

func (m *Metadata) GetBase() string { _ = "STUB: not implemented"; return "" }

func (m *Metadata) GetDisplay() string { _ = "STUB: not implemented"; return "" }

func (m *Metadata) GetName() string { _ = "STUB: not implemented"; return "" }

func (m *Metadata) GetSymbol() string { _ = "STUB: not implemented"; return "" }

type AllowList struct {
	// Can be empty for no admin, or a valid sei address
	Addresses []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty" yaml:"addresses"`
}

func (m *AllowList) Reset()                    { _ = "STUB: not implemented"; return }
func (m *AllowList) String() string            { _ = "STUB: not implemented"; return "" }
func (*AllowList) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*AllowList) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *AllowList) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AllowList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AllowList) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *AllowList) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *AllowList) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_AllowList proto.InternalMessageInfo

func (m *AllowList) GetAddresses() []string { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*Params)(nil), "cosmos.bank.v1beta1.Params")
	proto.RegisterType((*SendEnabled)(nil), "cosmos.bank.v1beta1.SendEnabled")
	proto.RegisterType((*Input)(nil), "cosmos.bank.v1beta1.Input")
	proto.RegisterType((*Output)(nil), "cosmos.bank.v1beta1.Output")
	proto.RegisterType((*Supply)(nil), "cosmos.bank.v1beta1.Supply")
	proto.RegisterType((*DenomUnit)(nil), "cosmos.bank.v1beta1.DenomUnit")
	proto.RegisterType((*Metadata)(nil), "cosmos.bank.v1beta1.Metadata")
	proto.RegisterType((*AllowList)(nil), "cosmos.bank.v1beta1.AllowList")
}

func init() { proto.RegisterFile("cosmos/bank/v1beta1/bank.proto", fileDescriptor_dd052eee12edf988) }

var fileDescriptor_dd052eee12edf988 = []byte{
	// 638 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0xcd, 0x6e, 0x13, 0x3d,
	0x14, 0x8d, 0x9b, 0x9f, 0x2f, 0x71, 0x3e, 0x24, 0x64, 0x22, 0x34, 0xad, 0xc4, 0x4c, 0x18, 0x09,
	0xa9, 0x20, 0x9a, 0xb4, 0x85, 0x05, 0x64, 0x03, 0x04, 0x2a, 0xa8, 0x04, 0x02, 0x4d, 0x05, 0x48,
	0xb0, 0x88, 0x9c, 0x19, 0x37, 0xb5, 0xf0, 0xd8, 0x43, 0xec, 0x29, 0x9d, 0x37, 0x60, 0xc9, 0x92,
	0x15, 0x74, 0xcd, 0x9a, 0x77, 0xa0, 0xcb, 0x0a, 0x36, 0xac, 0x02, 0x6a, 0x37, 0xac, 0xfb, 0x04,
	0xc8, 0xf6, 0xe4, 0xa7, 0x52, 0x59, 0x80, 0x84, 0xc4, 0xee, 0x9e, 0x7b, 0x8f, 0x8f, 0xcf, 0xf8,
	0xdc, 0x81, 0x6e, 0x28, 0x64, 0x2c, 0x64, 0xbb, 0x8f, 0xf9, 0x8b, 0xf6, 0xf6, 0x4a, 0x9f, 0x28,
	0xbc, 0x62, 0x40, 0x2b, 0x19, 0x0a, 0x25, 0xd0, 0x19, 0x3b, 0x6f, 0x99, 0x56, 0x3e, 0x5f, 0x98,
	0x1e, 0x92, 0x64, 0x72, 0x28, 0x14, 0x94, 0xdb, 0x43, 0x0b, 0xf3, 0x76, 0xde, 0x33, 0xa8, 0x9d,
	0x2b, 0xd8, 0x51, 0x63, 0x20, 0x06, 0xc2, 0xf6, 0x75, 0x65, 0xbb, 0xfe, 0x17, 0x00, 0x2b, 0x8f,
	0xf0, 0x10, 0xc7, 0x12, 0x6d, 0xc2, 0xff, 0x25, 0xe1, 0x51, 0x8f, 0x70, 0xdc, 0x67, 0x24, 0x72,
	0x40, 0xb3, 0xb8, 0x58, 0x5f, 0x6d, 0xb6, 0x4e, 0xf0, 0xd1, 0xda, 0x20, 0x3c, 0x5a, 0xb3, 0xbc,
	0xee, 0xf9, 0xa3, 0x91, 0x77, 0x2e, 0xc3, 0x31, 0xeb, 0xf8, 0xb3, 0xe7, 0x2f, 0x8b, 0x98, 0x2a,
	0x12, 0x27, 0x2a, 0xf3, 0x83, 0xba, 0x9c, 0xf2, 0xd1, 0x73, 0xd8, 0x88, 0xc8, 0x26, 0x4e, 0x99,
	0xea, 0x1d, 0xbb, 0x6f, 0xae, 0x09, 0x16, 0xab, 0xdd, 0x8b, 0x47, 0x23, 0xef, 0x82, 0x55, 0x3b,
	0x89, 0x35, 0xab, 0x8a, 0x72, 0xc2, 0x8c, 0x99, 0x4e, 0xe9, 0xed, 0xae, 0x57, 0xf0, 0xef, 0xc2,
	0xfa, 0x4c, 0x13, 0x35, 0x60, 0x39, 0x22, 0x5c, 0xc4, 0x0e, 0x68, 0x82, 0xc5, 0x5a, 0x60, 0x01,
	0x72, 0xe0, 0x7f, 0xc7, 0xae, 0x0e, 0xc6, 0xb0, 0x53, 0xd5, 0x22, 0x3f, 0x76, 0x3d, 0xe0, 0xbf,
	0x03, 0xb0, 0xbc, 0xce, 0x93, 0x54, 0x69, 0x36, 0x8e, 0xa2, 0x21, 0x91, 0x32, 0x57, 0x19, 0x43,
	0xf4, 0x12, 0x96, 0x75, 0x02, 0xd2, 0x99, 0x33, 0x0f, 0x36, 0x3f, 0x7d, 0x30, 0x49, 0x26, 0x0f,
	0x76, 0x5b, 0x50, 0xde, 0xbd, 0xb9, 0x37, 0xf2, 0x0a, 0x1f, 0xbe, 0x79, 0xd7, 0x06, 0x54, 0x6d,
	0xa5, 0xfd, 0x56, 0x28, 0xe2, 0xb6, 0x24, 0x74, 0xc9, 0x44, 0x11, 0x0a, 0x66, 0x40, 0xb8, 0x85,
	0x29, 0xb7, 0x95, 0xcd, 0x5a, 0x65, 0x09, 0x91, 0x46, 0x40, 0x06, 0xf6, 0xa6, 0x4e, 0xf5, 0xb5,
	0x35, 0x58, 0xf0, 0xdf, 0x03, 0x58, 0x79, 0x98, 0xaa, 0x7f, 0xd8, 0xa1, 0xde, 0xb0, 0x8d, 0x34,
	0x49, 0x58, 0xa6, 0x7d, 0x28, 0xa1, 0x30, 0xcb, 0x57, 0xeb, 0xef, 0xfa, 0x30, 0x37, 0x75, 0x9e,
	0xe4, 0x3e, 0xc0, 0xe7, 0x8f, 0x4b, 0xf7, 0x2e, 0xfd, 0x96, 0xda, 0x8e, 0xfd, 0x35, 0x19, 0x19,
	0xe0, 0x30, 0x6b, 0x6f, 0x2f, 0x5f, 0x5d, 0x6e, 0xd9, 0xef, 0x58, 0x77, 0x80, 0xff, 0x14, 0xd6,
	0xee, 0xe8, 0x2d, 0x7a, 0xcc, 0xa9, 0xfa, 0xc5, 0x7e, 0x2d, 0xc0, 0x2a, 0xd9, 0x49, 0x04, 0x27,
	0x5c, 0x99, 0x05, 0x3b, 0x15, 0x4c, 0xb0, 0xc9, 0x8a, 0x51, 0x2c, 0x89, 0x74, 0x8a, 0xcd, 0xa2,
	0xc9, 0xca, 0x42, 0xff, 0x13, 0x80, 0xd5, 0x07, 0x44, 0xe1, 0x08, 0x2b, 0x8c, 0x9a, 0xb0, 0x1e,
	0x11, 0x19, 0x0e, 0x69, 0xa2, 0xa8, 0xe0, 0xb9, 0xfc, 0x6c, 0x0b, 0xdd, 0xd0, 0x0c, 0x2e, 0xe2,
	0x5e, 0xca, 0xa9, 0x1a, 0x07, 0xec, 0x9e, 0xf8, 0xcf, 0x4e, 0xfc, 0x06, 0x30, 0x1a, 0x97, 0x12,
	0x21, 0x58, 0xd2, 0xcf, 0xef, 0x14, 0x8d, 0xb6, 0xa9, 0xb5, 0xbb, 0x88, 0xca, 0x84, 0xe1, 0xcc,
	0x29, 0xd9, 0x4d, 0xca, 0xa1, 0x66, 0x73, 0x1c, 0x13, 0xa7, 0x6c, 0xd9, 0xba, 0x46, 0x67, 0x61,
	0x45, 0x66, 0x71, 0x5f, 0x30, 0xa7, 0x62, 0xba, 0x39, 0xf2, 0xd7, 0x60, 0xed, 0x16, 0x63, 0xe2,
	0xd5, 0x7d, 0x2a, 0x15, 0x5a, 0x85, 0xb5, 0x7c, 0x1b, 0x89, 0x34, 0xf1, 0xd7, 0xba, 0x8d, 0xa3,
	0x91, 0x77, 0xda, 0xfe, 0xe9, 0x93, 0x91, 0x1f, 0x4c, 0x69, 0x9d, 0x92, 0xce, 0xad, 0xbb, 0xb1,
	0x77, 0xe0, 0x82, 0xfd, 0x03, 0x17, 0x7c, 0x3f, 0x70, 0xc1, 0x9b, 0x43, 0xb7, 0xb0, 0x7f, 0xe8,
	0x16, 0xbe, 0x1e, 0xba, 0x85, 0x67, 0xd7, 0xff, 0x24, 0x4e, 0xb3, 0x23, 0xfd, 0x8a, 0xe1, 0x5e,
	0xf9, 0x19, 0x00, 0x00, 0xff, 0xff, 0x84, 0xcb, 0x17, 0x3b, 0x85, 0x05, 0x00, 0x00,
}

func (this *SendEnabled) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *Supply) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (this *AllowList) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (m *Params) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Params) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SendEnabled) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SendEnabled) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *SendEnabled) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Input) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Input) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Input) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Output) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Output) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Output) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Supply) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Supply) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Supply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DenomUnit) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *DenomUnit) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *DenomUnit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Metadata) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Metadata) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Metadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AllowList) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *AllowList) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *AllowList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintBank(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *Params) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SendEnabled) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Input) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Output) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Supply) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DenomUnit) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Metadata) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AllowList) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovBank(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozBank(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Params) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SendEnabled) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Input) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Output) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Supply) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *DenomUnit) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Metadata) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AllowList) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipBank(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthBank        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBank          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBank = fmt.Errorf("proto: unexpected end of group")
)
