// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/mempool/types.proto

package mempool

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Txs struct {
	Txs [][]byte `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
}

func (m *Txs) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Txs) String() string            { _ = "STUB: not implemented"; return "" }
func (*Txs) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Txs) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Txs) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Txs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Txs) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Txs) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Txs) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Txs proto.InternalMessageInfo

func (m *Txs) GetTxs() [][]byte { _ = "STUB: not implemented"; return nil }

type Message struct {
	// Types that are valid to be assigned to Sum:
	//
	//	*Message_Txs
	Sum isMessage_Sum `protobuf_oneof:"sum"`
}

func (m *Message) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Message) String() string            { _ = "STUB: not implemented"; return "" }
func (*Message) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Message) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Message) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Message) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Message) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Message) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Sum interface {
	isMessage_Sum()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Message_Txs struct {
	Txs *Txs `protobuf:"bytes,1,opt,name=txs,proto3,oneof" json:"txs,omitempty"`
}

func (*Message_Txs) isMessage_Sum() { _ = "STUB: not implemented"; return }

func (m *Message) GetSum() isMessage_Sum { _ = "STUB: not implemented"; return *new(isMessage_Sum) }

func (m *Message) GetTxs() *Txs { _ = "STUB: not implemented"; return nil }

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*Txs)(nil), "tendermint.mempool.Txs")
	proto.RegisterType((*Message)(nil), "tendermint.mempool.Message")
}

func init() { proto.RegisterFile("tendermint/mempool/types.proto", fileDescriptor_2af51926fdbcbc05) }

var fileDescriptor_2af51926fdbcbc05 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x49, 0xcd, 0x4b,
	0x49, 0x2d, 0xca, 0xcd, 0xcc, 0x2b, 0xd1, 0xcf, 0x4d, 0xcd, 0x2d, 0xc8, 0xcf, 0xcf, 0xd1, 0x2f,
	0xa9, 0x2c, 0x48, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x42, 0xc8, 0xeb, 0x41,
	0xe5, 0x95, 0xc4, 0xb9, 0x98, 0x43, 0x2a, 0x8a, 0x85, 0x04, 0xb8, 0x98, 0x4b, 0x2a, 0x8a, 0x25,
	0x18, 0x15, 0x98, 0x35, 0x78, 0x82, 0x40, 0x4c, 0x25, 0x5b, 0x2e, 0x76, 0xdf, 0xd4, 0xe2, 0xe2,
	0xc4, 0xf4, 0x54, 0x21, 0x6d, 0x98, 0x24, 0xa3, 0x06, 0xb7, 0x91, 0xb8, 0x1e, 0xa6, 0x29, 0x7a,
	0x21, 0x15, 0xc5, 0x1e, 0x0c, 0x60, 0x7d, 0x4e, 0xac, 0x5c, 0xcc, 0xc5, 0xa5, 0xb9, 0x4e, 0xc9,
	0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x84, 0xc7, 0x72,
	0x0c, 0x17, 0x1e, 0xcb, 0x31, 0xdc, 0x78, 0x2c, 0xc7, 0x10, 0xe5, 0x99, 0x9e, 0x59, 0x92, 0x51,
	0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x5f, 0x9c, 0x9a, 0xa9, 0x0b, 0x76, 0x5b, 0x72, 0x7e, 0x0e,
	0x98, 0x93, 0x9c, 0x91, 0x98, 0x99, 0x07, 0x66, 0x21, 0xf9, 0x05, 0xac, 0x42, 0x1f, 0xd3, 0x73,
	0x49, 0x6c, 0x60, 0x19, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x41, 0x3b, 0x0c, 0xa5, 0xf9,
	0x00, 0x00, 0x00,
}

func (m *Txs) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Txs) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Txs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Message) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_Txs) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Message_Txs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *Txs) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_Txs) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Txs) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Message) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipTypes(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
