// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/params/v1beta1/query.proto

package proposal

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
	// subspace defines the module to query the parameter for.
	Subspace string `protobuf:"bytes,1,opt,name=subspace,proto3" json:"subspace,omitempty"`
	// key defines the key of the parameter in the subspace.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *QueryParamsRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *QueryParamsRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*QueryParamsRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*QueryParamsRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryParamsRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryParamsRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryParamsRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

func (m *QueryParamsRequest) GetSubspace() string { _ = "STUB: not implemented"; return "" }

func (m *QueryParamsRequest) GetKey() string { _ = "STUB: not implemented"; return "" }

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// param defines the queried parameter.
	Param ParamChange `protobuf:"bytes,1,opt,name=param,proto3" json:"param"`
}

func (m *QueryParamsResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryParamsResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryParamsResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryParamsResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryParamsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryParamsResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParam() ParamChange {
	_ = "STUB: not implemented"
	return *new(ParamChange)
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmos.params.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmos.params.v1beta1.QueryParamsResponse")
}

func init() { proto.RegisterFile("cosmos/params/v1beta1/query.proto", fileDescriptor_2b32979c1792ccc4) }

var fileDescriptor_2b32979c1792ccc4 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x3f, 0x4b, 0x03, 0x31,
	0x18, 0xc6, 0x2f, 0xd5, 0x16, 0x8d, 0x8b, 0x44, 0x85, 0x72, 0xe8, 0x55, 0x0f, 0x04, 0x15, 0x4c,
	0x68, 0xdd, 0x1d, 0xaa, 0x1f, 0x40, 0x0b, 0x2e, 0x0e, 0x42, 0xee, 0x08, 0xe9, 0x61, 0x9b, 0x37,
	0xbd, 0xe4, 0xc4, 0xae, 0x0e, 0xce, 0x05, 0xbf, 0x54, 0xc7, 0x82, 0x8b, 0x93, 0x48, 0xeb, 0x07,
	0x91, 0x26, 0xa7, 0x20, 0x56, 0x71, 0x7b, 0xde, 0x97, 0xe7, 0xf9, 0xbd, 0x7f, 0xf0, 0x5e, 0x0a,
	0xa6, 0x0f, 0x86, 0x69, 0x9e, 0xf3, 0xbe, 0x61, 0x77, 0xcd, 0x44, 0x58, 0xde, 0x64, 0x83, 0x42,
	0xe4, 0x43, 0xaa, 0x73, 0xb0, 0x40, 0xb6, 0xbc, 0x85, 0x7a, 0x0b, 0x2d, 0x2d, 0x61, 0xbc, 0x38,
	0x59, 0xba, 0x5c, 0x34, 0xdc, 0x94, 0x20, 0xc1, 0x49, 0x36, 0x57, 0x65, 0x77, 0x5b, 0x02, 0xc8,
	0x9e, 0x60, 0x5c, 0x67, 0x8c, 0x2b, 0x05, 0x96, 0xdb, 0x0c, 0x54, 0x99, 0x89, 0xdb, 0x98, 0x5c,
	0xce, 0xa7, 0x5f, 0x38, 0x50, 0x47, 0x0c, 0x0a, 0x61, 0x2c, 0x09, 0xf1, 0x8a, 0x29, 0x12, 0xa3,
	0x79, 0x2a, 0xea, 0x68, 0x17, 0x1d, 0xac, 0x76, 0xbe, 0x6a, 0xb2, 0x8e, 0x97, 0x6e, 0xc5, 0xb0,
	0x5e, 0x71, 0xed, 0xb9, 0x8c, 0xaf, 0xf0, 0xc6, 0x37, 0x86, 0xd1, 0xa0, 0x8c, 0x20, 0xa7, 0xb8,
	0xea, 0xd6, 0x73, 0x84, 0xb5, 0x56, 0x4c, 0x17, 0x5e, 0x46, 0x5d, 0xea, 0xac, 0xcb, 0x95, 0x14,
	0xed, 0xe5, 0xf1, 0x6b, 0x23, 0xe8, 0xf8, 0x58, 0x6b, 0x84, 0x70, 0xd5, 0x71, 0xc9, 0x23, 0xc2,
	0x35, 0x0f, 0x27, 0x87, 0xbf, 0x50, 0x7e, 0x1e, 0x11, 0x1e, 0xfd, 0xc7, 0xea, 0x77, 0x8d, 0xf7,
	0x1f, 0x9e, 0xdf, 0x9f, 0x2a, 0x0d, 0xb2, 0xc3, 0xfe, 0xfa, 0x73, 0xfb, 0x66, 0x3c, 0x8d, 0xd0,
	0x64, 0x1a, 0xa1, 0xb7, 0x69, 0x84, 0x46, 0xb3, 0x28, 0x98, 0xcc, 0xa2, 0xe0, 0x65, 0x16, 0x05,
	0xd7, 0xe7, 0x32, 0xb3, 0xdd, 0x22, 0xa1, 0x29, 0xf4, 0x99, 0x11, 0xd9, 0xb1, 0xfb, 0x6e, 0x0a,
	0x3d, 0x57, 0xa4, 0x5d, 0x9e, 0x29, 0xaf, 0x3c, 0xfd, 0xfe, 0x93, 0x6f, 0x87, 0x5a, 0x18, 0xa6,
	0x73, 0xd0, 0x60, 0x78, 0x2f, 0xa9, 0xb9, 0xd8, 0xc9, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda,
	0x19, 0xc2, 0x47, 0x28, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries a specific parameter of a module, given its subspace and
	// key.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	_ = "STUB: not implemented"
	return *new(QueryClient)
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params queries a specific parameter of a module, given its subspace and
	// key.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) { _ = "STUB: not implemented"; return }

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.params.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/params/v1beta1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *QueryParamsRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryParamsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovQuery(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozQuery(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipQuery(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
