// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	indexer "github.com/sei-protocol/sei-chain/sei-tendermint/internal/state/indexer"
	mock "github.com/stretchr/testify/mock"

	query "github.com/sei-protocol/sei-chain/sei-tendermint/internal/pubsub/query"

	sei_tenderminttypes "github.com/sei-protocol/sei-chain/sei-tendermint/types"

	types "github.com/sei-protocol/sei-chain/sei-tendermint/abci/types"
)

// EventSink is an autogenerated mock type for the EventSink type
type EventSink struct {
	mock.Mock
}

// GetTxByHash provides a mock function with given fields: _a0
func (_m *EventSink) GetTxByHash(_a0 []byte) (*types.TxResultV2, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HasBlock provides a mock function with given fields: _a0
func (_m *EventSink) HasBlock(_a0 int64) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// IndexBlockEvents provides a mock function with given fields: _a0
func (_m *EventSink) IndexBlockEvents(_a0 sei_tenderminttypes.EventDataNewBlockHeader) error {
	_ = "STUB: not implemented"
	return nil
}

// IndexTxEvents provides a mock function with given fields: _a0
func (_m *EventSink) IndexTxEvents(_a0 []*types.TxResultV2) error {
	_ = "STUB: not implemented"
	return nil
}

// SearchBlockEvents provides a mock function with given fields: _a0, _a1
func (_m *EventSink) SearchBlockEvents(_a0 context.Context, _a1 *query.Query) ([]int64, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SearchTxEvents provides a mock function with given fields: _a0, _a1
func (_m *EventSink) SearchTxEvents(_a0 context.Context, _a1 *query.Query) ([]*types.TxResultV2, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Stop provides a mock function with no fields
func (_m *EventSink) Stop() error { _ = "STUB: not implemented"; return nil }

// Type provides a mock function with no fields
func (_m *EventSink) Type() indexer.EventSinkType {
	_ = "STUB: not implemented"
	return *new(indexer.EventSinkType)
}

// NewEventSink creates a new instance of EventSink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventSink {
	_ = "STUB: not implemented"
	return nil
}
