// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oracle/query.proto

package types

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryExchangeRateRequest is the request type for the Query/ExchangeRate RPC method.
type QueryExchangeRateRequest struct {
	// denom defines the denomination to query for.
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryExchangeRateRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryExchangeRateRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryExchangeRateRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryExchangeRateRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryExchangeRateRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryExchangeRateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryExchangeRateRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryExchangeRateRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryExchangeRateRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryExchangeRateRequest proto.InternalMessageInfo

// QueryExchangeRateResponse is response type for the
// Query/ExchangeRate RPC method.
type QueryExchangeRateResponse struct {
	// exchange_rate defines the exchange rate of Sei denominated in various Sei
	OracleExchangeRate OracleExchangeRate `protobuf:"bytes,1,opt,name=oracle_exchange_rate,json=oracleExchangeRate,proto3" json:"oracle_exchange_rate"`
}

func (m *QueryExchangeRateResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryExchangeRateResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryExchangeRateResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryExchangeRateResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryExchangeRateResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryExchangeRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryExchangeRateResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryExchangeRateResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryExchangeRateResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryExchangeRateResponse proto.InternalMessageInfo

func (m *QueryExchangeRateResponse) GetOracleExchangeRate() OracleExchangeRate {
	_ = "STUB: not implemented"
	return *new(OracleExchangeRate)
}

// QueryExchangeRatesRequest is the request type for the Query/ExchangeRates RPC method.
type QueryExchangeRatesRequest struct {
}

func (m *QueryExchangeRatesRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryExchangeRatesRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryExchangeRatesRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryExchangeRatesRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryExchangeRatesRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryExchangeRatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryExchangeRatesRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryExchangeRatesRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryExchangeRatesRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryExchangeRatesRequest proto.InternalMessageInfo

type DenomOracleExchangeRatePair struct {
	Denom              string             `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	OracleExchangeRate OracleExchangeRate `protobuf:"bytes,2,opt,name=oracle_exchange_rate,json=oracleExchangeRate,proto3" json:"oracle_exchange_rate"`
}

func (m *DenomOracleExchangeRatePair) Reset()         { _ = "STUB: not implemented"; return }
func (m *DenomOracleExchangeRatePair) String() string { _ = "STUB: not implemented"; return "" }
func (*DenomOracleExchangeRatePair) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*DenomOracleExchangeRatePair) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DenomOracleExchangeRatePair) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *DenomOracleExchangeRatePair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DenomOracleExchangeRatePair) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *DenomOracleExchangeRatePair) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *DenomOracleExchangeRatePair) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_DenomOracleExchangeRatePair proto.InternalMessageInfo

func (m *DenomOracleExchangeRatePair) GetDenom() string { _ = "STUB: not implemented"; return "" }

func (m *DenomOracleExchangeRatePair) GetOracleExchangeRate() OracleExchangeRate {
	_ = "STUB: not implemented"
	return *new(OracleExchangeRate)
}

// QueryExchangeRatesResponse is response type for the
// Query/ExchangeRates RPC method.
type QueryExchangeRatesResponse struct {
	// exchange_rates defines a list of the exchange rate for all whitelisted denoms.
	DenomOracleExchangeRatePairs DenomOracleExchangeRatePairs `protobuf:"bytes,1,rep,name=denom_oracle_exchange_rate_pairs,json=denomOracleExchangeRatePairs,proto3,castrepeated=DenomOracleExchangeRatePairs" json:"denom_oracle_exchange_rate_pairs"`
}

func (m *QueryExchangeRatesResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryExchangeRatesResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryExchangeRatesResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryExchangeRatesResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryExchangeRatesResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryExchangeRatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryExchangeRatesResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryExchangeRatesResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryExchangeRatesResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryExchangeRatesResponse proto.InternalMessageInfo

func (m *QueryExchangeRatesResponse) GetDenomOracleExchangeRatePairs() DenomOracleExchangeRatePairs {
	_ = "STUB: not implemented"
	return *new(DenomOracleExchangeRatePairs)
}

// QueryActivesRequest is the request type for the Query/Actives RPC method.
type QueryActivesRequest struct {
}

func (m *QueryActivesRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryActivesRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryActivesRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryActivesRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryActivesRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryActivesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryActivesRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryActivesRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryActivesRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryActivesRequest proto.InternalMessageInfo

// QueryActivesResponse is response type for the
// Query/Actives RPC method.
type QueryActivesResponse struct {
	// actives defines a list of the denomination which oracle prices aggreed upon.
	Actives []string `protobuf:"bytes,1,rep,name=actives,proto3" json:"actives,omitempty"`
}

func (m *QueryActivesResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryActivesResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryActivesResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryActivesResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryActivesResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryActivesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryActivesResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryActivesResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryActivesResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryActivesResponse proto.InternalMessageInfo

func (m *QueryActivesResponse) GetActives() []string { _ = "STUB: not implemented"; return nil }

// QueryVoteTargetsRequest is the request type for the Query/VoteTargets RPC method.
type QueryVoteTargetsRequest struct {
}

func (m *QueryVoteTargetsRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryVoteTargetsRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryVoteTargetsRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryVoteTargetsRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryVoteTargetsRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryVoteTargetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryVoteTargetsRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryVoteTargetsRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryVoteTargetsRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryVoteTargetsRequest proto.InternalMessageInfo

// QueryVoteTargetsResponse is response type for the
// Query/VoteTargets RPC method.
type QueryVoteTargetsResponse struct {
	// vote_targets defines a list of the denomination in which everyone
	// should vote in the current vote period.
	VoteTargets []string `protobuf:"bytes,1,rep,name=vote_targets,json=voteTargets,proto3" json:"vote_targets,omitempty"`
}

func (m *QueryVoteTargetsResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryVoteTargetsResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryVoteTargetsResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryVoteTargetsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryVoteTargetsResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryVoteTargetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryVoteTargetsResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryVoteTargetsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryVoteTargetsResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryVoteTargetsResponse proto.InternalMessageInfo

func (m *QueryVoteTargetsResponse) GetVoteTargets() []string { _ = "STUB: not implemented"; return nil }

// request type for price snapshot history RPC method
type QueryPriceSnapshotHistoryRequest struct {
}

func (m *QueryPriceSnapshotHistoryRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryPriceSnapshotHistoryRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryPriceSnapshotHistoryRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryPriceSnapshotHistoryRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPriceSnapshotHistoryRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPriceSnapshotHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPriceSnapshotHistoryRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryPriceSnapshotHistoryRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryPriceSnapshotHistoryRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryPriceSnapshotHistoryRequest proto.InternalMessageInfo

type QueryPriceSnapshotHistoryResponse struct {
	PriceSnapshots PriceSnapshots `protobuf:"bytes,1,rep,name=price_snapshots,json=priceSnapshots,proto3,castrepeated=PriceSnapshots" json:"price_snapshots"`
}

func (m *QueryPriceSnapshotHistoryResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryPriceSnapshotHistoryResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryPriceSnapshotHistoryResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryPriceSnapshotHistoryResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPriceSnapshotHistoryResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPriceSnapshotHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPriceSnapshotHistoryResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryPriceSnapshotHistoryResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryPriceSnapshotHistoryResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryPriceSnapshotHistoryResponse proto.InternalMessageInfo

func (m *QueryPriceSnapshotHistoryResponse) GetPriceSnapshots() PriceSnapshots {
	_ = "STUB: not implemented"
	return *new(PriceSnapshots)
}

// request type for twap RPC method
type QueryTwapsRequest struct {
	LookbackSeconds uint64 `protobuf:"varint,1,opt,name=lookback_seconds,json=lookbackSeconds,proto3" json:"lookback_seconds,omitempty"`
}

func (m *QueryTwapsRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *QueryTwapsRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*QueryTwapsRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*QueryTwapsRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *QueryTwapsRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryTwapsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryTwapsRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryTwapsRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryTwapsRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryTwapsRequest proto.InternalMessageInfo

func (m *QueryTwapsRequest) GetLookbackSeconds() uint64 { _ = "STUB: not implemented"; return 0 }

type QueryTwapsResponse struct {
	OracleTwaps OracleTwaps `protobuf:"bytes,1,rep,name=oracle_twaps,json=oracleTwaps,proto3,castrepeated=OracleTwaps" json:"oracle_twaps"`
}

func (m *QueryTwapsResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (m *QueryTwapsResponse) String() string            { _ = "STUB: not implemented"; return "" }
func (*QueryTwapsResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*QueryTwapsResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *QueryTwapsResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryTwapsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryTwapsResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryTwapsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryTwapsResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryTwapsResponse proto.InternalMessageInfo

func (m *QueryTwapsResponse) GetOracleTwaps() OracleTwaps {
	_ = "STUB: not implemented"
	return *new(OracleTwaps)
}

// QueryFeederDelegationRequest is the request type for the Query/FeederDelegation RPC method.
type QueryFeederDelegationRequest struct {
	// validator defines the validator address to query for.
	ValidatorAddr string `protobuf:"bytes,1,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
}

func (m *QueryFeederDelegationRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryFeederDelegationRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryFeederDelegationRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryFeederDelegationRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryFeederDelegationRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryFeederDelegationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryFeederDelegationRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryFeederDelegationRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryFeederDelegationRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryFeederDelegationRequest proto.InternalMessageInfo

// QueryFeederDelegationResponse is response type for the
// Query/FeederDelegation RPC method.
type QueryFeederDelegationResponse struct {
	// feeder_addr defines the feeder delegation of a validator
	FeederAddr string `protobuf:"bytes,1,opt,name=feeder_addr,json=feederAddr,proto3" json:"feeder_addr,omitempty"`
}

func (m *QueryFeederDelegationResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryFeederDelegationResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryFeederDelegationResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryFeederDelegationResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryFeederDelegationResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryFeederDelegationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryFeederDelegationResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryFeederDelegationResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryFeederDelegationResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryFeederDelegationResponse proto.InternalMessageInfo

func (m *QueryFeederDelegationResponse) GetFeederAddr() string {
	_ = "STUB: not implemented"
	return ""
}

// QueryVotePenaltyCounterRequest is the request type for the Query/MissCounter RPC method.
type QueryVotePenaltyCounterRequest struct {
	// validator defines the validator address to query for.
	ValidatorAddr string `protobuf:"bytes,1,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
}

func (m *QueryVotePenaltyCounterRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryVotePenaltyCounterRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryVotePenaltyCounterRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryVotePenaltyCounterRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryVotePenaltyCounterRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryVotePenaltyCounterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryVotePenaltyCounterRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryVotePenaltyCounterRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryVotePenaltyCounterRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryVotePenaltyCounterRequest proto.InternalMessageInfo

// QueryVotePenaltyCounterResponse is response type for the
// Query/VotePenaltyCounter RPC method.
type QueryVotePenaltyCounterResponse struct {
	VotePenaltyCounter *VotePenaltyCounter `protobuf:"bytes,1,opt,name=vote_penalty_counter,json=votePenaltyCounter,proto3" json:"vote_penalty_counter,omitempty"`
}

func (m *QueryVotePenaltyCounterResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryVotePenaltyCounterResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryVotePenaltyCounterResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryVotePenaltyCounterResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryVotePenaltyCounterResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryVotePenaltyCounterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryVotePenaltyCounterResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryVotePenaltyCounterResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryVotePenaltyCounterResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryVotePenaltyCounterResponse proto.InternalMessageInfo

func (m *QueryVotePenaltyCounterResponse) GetVotePenaltyCounter() *VotePenaltyCounter {
	_ = "STUB: not implemented"
	return nil
}

// QuerySlashWindow is the request type for the
// Query/SlashWindow RPC method.
type QuerySlashWindowRequest struct {
}

func (m *QuerySlashWindowRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QuerySlashWindowRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QuerySlashWindowRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QuerySlashWindowRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QuerySlashWindowRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QuerySlashWindowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QuerySlashWindowRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QuerySlashWindowRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QuerySlashWindowRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QuerySlashWindowRequest proto.InternalMessageInfo

// QuerySlashWindowResponse is response type for the
// Query/SlashWindow RPC method.
type QuerySlashWindowResponse struct {
	// window_progress defines the number of voting periods
	// since the last slashing event would have taken place.
	WindowProgress uint64 `protobuf:"varint,1,opt,name=window_progress,json=windowProgress,proto3" json:"window_progress,omitempty"`
}

func (m *QuerySlashWindowResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QuerySlashWindowResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QuerySlashWindowResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QuerySlashWindowResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QuerySlashWindowResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QuerySlashWindowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QuerySlashWindowResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QuerySlashWindowResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QuerySlashWindowResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QuerySlashWindowResponse proto.InternalMessageInfo

func (m *QuerySlashWindowResponse) GetWindowProgress() uint64 { _ = "STUB: not implemented"; return 0 }

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *QueryParamsRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*QueryParamsRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*QueryParamsRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryParamsRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryParamsRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryParamsRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params defines the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryParamsResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryParamsResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryParamsResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryParamsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryParamsResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params { _ = "STUB: not implemented"; return *new(Params) }

func init() {
	proto.RegisterType((*QueryExchangeRateRequest)(nil), "seiprotocol.seichain.oracle.QueryExchangeRateRequest")
	proto.RegisterType((*QueryExchangeRateResponse)(nil), "seiprotocol.seichain.oracle.QueryExchangeRateResponse")
	proto.RegisterType((*QueryExchangeRatesRequest)(nil), "seiprotocol.seichain.oracle.QueryExchangeRatesRequest")
	proto.RegisterType((*DenomOracleExchangeRatePair)(nil), "seiprotocol.seichain.oracle.DenomOracleExchangeRatePair")
	proto.RegisterType((*QueryExchangeRatesResponse)(nil), "seiprotocol.seichain.oracle.QueryExchangeRatesResponse")
	proto.RegisterType((*QueryActivesRequest)(nil), "seiprotocol.seichain.oracle.QueryActivesRequest")
	proto.RegisterType((*QueryActivesResponse)(nil), "seiprotocol.seichain.oracle.QueryActivesResponse")
	proto.RegisterType((*QueryVoteTargetsRequest)(nil), "seiprotocol.seichain.oracle.QueryVoteTargetsRequest")
	proto.RegisterType((*QueryVoteTargetsResponse)(nil), "seiprotocol.seichain.oracle.QueryVoteTargetsResponse")
	proto.RegisterType((*QueryPriceSnapshotHistoryRequest)(nil), "seiprotocol.seichain.oracle.QueryPriceSnapshotHistoryRequest")
	proto.RegisterType((*QueryPriceSnapshotHistoryResponse)(nil), "seiprotocol.seichain.oracle.QueryPriceSnapshotHistoryResponse")
	proto.RegisterType((*QueryTwapsRequest)(nil), "seiprotocol.seichain.oracle.QueryTwapsRequest")
	proto.RegisterType((*QueryTwapsResponse)(nil), "seiprotocol.seichain.oracle.QueryTwapsResponse")
	proto.RegisterType((*QueryFeederDelegationRequest)(nil), "seiprotocol.seichain.oracle.QueryFeederDelegationRequest")
	proto.RegisterType((*QueryFeederDelegationResponse)(nil), "seiprotocol.seichain.oracle.QueryFeederDelegationResponse")
	proto.RegisterType((*QueryVotePenaltyCounterRequest)(nil), "seiprotocol.seichain.oracle.QueryVotePenaltyCounterRequest")
	proto.RegisterType((*QueryVotePenaltyCounterResponse)(nil), "seiprotocol.seichain.oracle.QueryVotePenaltyCounterResponse")
	proto.RegisterType((*QuerySlashWindowRequest)(nil), "seiprotocol.seichain.oracle.QuerySlashWindowRequest")
	proto.RegisterType((*QuerySlashWindowResponse)(nil), "seiprotocol.seichain.oracle.QuerySlashWindowResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "seiprotocol.seichain.oracle.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "seiprotocol.seichain.oracle.QueryParamsResponse")
}

func init() { proto.RegisterFile("oracle/query.proto", fileDescriptor_562b782cb9ac197e) }

var fileDescriptor_562b782cb9ac197e = []byte{
	// 1104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xf6, 0x94, 0x26, 0xa5, 0xcf, 0x69, 0x52, 0x26, 0x06, 0xd2, 0x4d, 0xb0, 0xd3, 0x85, 0x2a,
	0x05, 0x14, 0x6f, 0x48, 0x93, 0x02, 0x69, 0x12, 0x35, 0x3f, 0xa8, 0x80, 0x4b, 0x12, 0xa7, 0xa2,
	0x88, 0xcb, 0x6a, 0x62, 0x0f, 0xeb, 0x55, 0x9c, 0x9d, 0xed, 0xce, 0x26, 0x69, 0x14, 0xe5, 0x82,
	0x7a, 0xe0, 0x18, 0x89, 0x1b, 0xe2, 0xd0, 0x0b, 0x1c, 0xb8, 0xc0, 0x89, 0x23, 0x07, 0x24, 0xa4,
	0x1e, 0x2b, 0xc1, 0x01, 0x09, 0x09, 0x50, 0xc2, 0xa1, 0x7f, 0x06, 0xf2, 0xec, 0x5b, 0x67, 0xb7,
	0x59, 0xaf, 0xd7, 0xa1, 0xa7, 0xf5, 0xbc, 0x37, 0xef, 0x9b, 0xef, 0x1b, 0xbf, 0x79, 0x1f, 0x50,
	0xe1, 0xb1, 0x6a, 0x83, 0x1b, 0xf7, 0xb7, 0xb9, 0xb7, 0x57, 0x76, 0x3d, 0xe1, 0x0b, 0x3a, 0x2c,
	0xb9, 0xad, 0x7e, 0x55, 0x45, 0xa3, 0x2c, 0xb9, 0x5d, 0xad, 0x33, 0xdb, 0x29, 0x07, 0x1b, 0xb5,
	0x82, 0x25, 0x2c, 0xa1, 0xb2, 0x46, 0xf3, 0x57, 0x50, 0xa2, 0x8d, 0x58, 0x42, 0x58, 0x0d, 0x6e,
	0x30, 0xd7, 0x36, 0x98, 0xe3, 0x08, 0x9f, 0xf9, 0xb6, 0x70, 0x24, 0x66, 0x07, 0xf1, 0x90, 0xe0,
	0x13, 0x04, 0xf5, 0x19, 0x18, 0x5a, 0x6b, 0x1e, 0xfa, 0xc1, 0x83, 0x6a, 0x9d, 0x39, 0x16, 0xaf,
	0x30, 0x9f, 0x57, 0xf8, 0xfd, 0x6d, 0x2e, 0x7d, 0x5a, 0x80, 0x9e, 0x1a, 0x77, 0xc4, 0xd6, 0x10,
	0x19, 0x25, 0xd7, 0x2f, 0x56, 0x82, 0xc5, 0xcc, 0x8b, 0x5f, 0x3e, 0x2a, 0xe5, 0x9e, 0x3e, 0x2a,
	0xe5, 0xf4, 0x87, 0x04, 0xae, 0x24, 0x14, 0x4b, 0x57, 0x38, 0x92, 0x53, 0x0b, 0x0a, 0xc1, 0x49,
	0x26, 0xc7, 0xb4, 0xe9, 0x31, 0x9f, 0x2b, 0xb0, 0xfc, 0xa4, 0x51, 0x4e, 0x91, 0x57, 0x5e, 0x51,
	0x9f, 0x28, 0xec, 0xe2, 0xf9, 0xc7, 0x7f, 0x95, 0x72, 0x15, 0xbc, 0xa8, 0x68, 0x46, 0x1f, 0x4e,
	0x60, 0x21, 0x51, 0x83, 0xfe, 0x0d, 0x81, 0xe1, 0xe5, 0x26, 0xef, 0xd3, 0x90, 0xab, 0xcc, 0xf6,
	0x92, 0x35, 0xb6, 0xe5, 0x7e, 0xee, 0x79, 0x73, 0xff, 0x95, 0x80, 0x96, 0x44, 0x1e, 0xef, 0xf0,
	0x3b, 0x02, 0xa3, 0x8a, 0x91, 0x99, 0x44, 0xc7, 0x74, 0x99, 0xed, 0xc9, 0x21, 0x32, 0xfa, 0xc2,
	0xf5, 0xfc, 0xe4, 0x7b, 0xa9, 0xa4, 0x52, 0xae, 0x60, 0xf1, 0x8d, 0x26, 0xbb, 0xef, 0xff, 0x2e,
	0x8d, 0xa4, 0x6c, 0x92, 0x95, 0x91, 0x5a, 0x4a, 0x56, 0x7f, 0x19, 0x06, 0x95, 0x8c, 0x85, 0xaa,
	0x6f, 0xef, 0x9c, 0xdc, 0xfe, 0x04, 0x14, 0xe2, 0x61, 0xd4, 0x35, 0x04, 0x17, 0x58, 0x10, 0x52,
	0xec, 0x2f, 0x56, 0xc2, 0xa5, 0x7e, 0x05, 0x5e, 0x55, 0x15, 0x9f, 0x08, 0x9f, 0xdf, 0x65, 0x9e,
	0xc5, 0xfd, 0x16, 0xd8, 0x1c, 0xb6, 0x6a, 0x2c, 0x85, 0x80, 0x57, 0xa1, 0x6f, 0x47, 0xf8, 0xdc,
	0xf4, 0x83, 0x38, 0xa2, 0xe6, 0x77, 0x4e, 0xb6, 0xea, 0x3a, 0x8c, 0xaa, 0xf2, 0x55, 0xcf, 0xae,
	0xf2, 0x75, 0x87, 0xb9, 0xb2, 0x2e, 0xfc, 0x0f, 0x6d, 0xe9, 0x0b, 0x6f, 0x2f, 0x3c, 0xe2, 0x90,
	0xc0, 0xd5, 0x94, 0x4d, 0x78, 0xd8, 0x26, 0x0c, 0xb8, 0xcd, 0xbc, 0x29, 0x71, 0x43, 0xf8, 0x1f,
	0xbc, 0x95, 0xfa, 0x1f, 0xc4, 0x30, 0x17, 0x5f, 0xc1, 0x5b, 0xef, 0x8f, 0x85, 0x65, 0xa5, 0xdf,
	0x8d, 0xad, 0xf5, 0x79, 0x78, 0x49, 0x31, 0xba, 0xbb, 0xcb, 0xdc, 0xf0, 0x2a, 0xe8, 0x9b, 0x70,
	0xb9, 0x21, 0xc4, 0xe6, 0x06, 0xab, 0x6e, 0x9a, 0x92, 0x57, 0x85, 0x53, 0x93, 0xaa, 0x81, 0xcf,
	0x57, 0x06, 0xc2, 0xf8, 0x7a, 0x10, 0xd6, 0xb7, 0x81, 0x46, 0xeb, 0x51, 0x82, 0x09, 0x7d, 0xd8,
	0x51, 0x7e, 0x33, 0x8e, 0xfc, 0xc7, 0x32, 0x34, 0x76, 0x13, 0x67, 0x71, 0x10, 0xc9, 0xe7, 0x4f,
	0x62, 0xb2, 0x92, 0x17, 0x27, 0x0b, 0x7d, 0x05, 0x46, 0xd4, 0xb1, 0x77, 0x38, 0xaf, 0x71, 0x6f,
	0x99, 0x37, 0xb8, 0xa5, 0x86, 0x51, 0xa8, 0xe0, 0x1a, 0xf4, 0xef, 0xb0, 0x86, 0x5d, 0x63, 0xbe,
	0xf0, 0x4c, 0x56, 0xab, 0x79, 0xf8, 0x00, 0x2f, 0xb5, 0xa2, 0x0b, 0xb5, 0x9a, 0x17, 0x19, 0x36,
	0xb7, 0xe1, 0xb5, 0x36, 0x80, 0x28, 0xa9, 0x04, 0xf9, 0xcf, 0x55, 0x2e, 0x0a, 0x07, 0x41, 0xa8,
	0x89, 0xa5, 0xaf, 0x41, 0xb1, 0xd5, 0x3f, 0xab, 0xdc, 0x61, 0x0d, 0x7f, 0x6f, 0x49, 0x6c, 0x3b,
	0x3e, 0xf7, 0xce, 0x4c, 0xea, 0x21, 0x81, 0x52, 0x5b, 0x4c, 0xe4, 0xc5, 0xa0, 0xa0, 0x5a, 0xd3,
	0x0d, 0xd2, 0x66, 0x35, 0xc8, 0x67, 0x9a, 0x83, 0x09, 0xb0, 0x74, 0xe7, 0x54, 0xac, 0xf5, 0x68,
	0xd6, 0x1b, 0x4c, 0xd6, 0xef, 0xd9, 0x4e, 0x4d, 0xec, 0x86, 0x1d, 0xbd, 0x84, 0x8f, 0x26, 0x96,
	0x42, 0x66, 0x63, 0x30, 0xb0, 0xab, 0x22, 0xa6, 0xeb, 0x09, 0xcb, 0xe3, 0x32, 0x6c, 0xa2, 0xfe,
	0x20, 0xbc, 0x8a, 0x51, 0xbd, 0x80, 0x3d, 0xb4, 0xca, 0x3c, 0xb6, 0xd5, 0x7a, 0x8f, 0x9f, 0xe2,
	0x9b, 0x0f, 0xa3, 0x88, 0xba, 0x00, 0xbd, 0xae, 0x8a, 0xa0, 0xc2, 0xd7, 0xd3, 0x1f, 0x85, 0xda,
	0x8a, 0x13, 0x12, 0x0b, 0x27, 0x0f, 0x07, 0xa0, 0x47, 0x41, 0xd3, 0x5f, 0x08, 0xf4, 0x45, 0xa7,
	0x0d, 0x9d, 0x4e, 0x45, 0x6b, 0x67, 0x65, 0xda, 0xcd, 0x6e, 0xcb, 0x02, 0x31, 0xfa, 0xd2, 0x17,
	0xbf, 0xfd, 0xfb, 0xd5, 0xb9, 0x39, 0x7a, 0xcb, 0x90, 0xdc, 0x1e, 0x0f, 0x01, 0xd4, 0x42, 0x21,
	0xa0, 0x99, 0x1a, 0x6a, 0x38, 0x4a, 0x63, 0x5f, 0x7d, 0x0f, 0x8c, 0xd8, 0x98, 0xa6, 0x3f, 0x13,
	0xb8, 0x14, 0x9b, 0xef, 0xb4, 0x4b, 0x3a, 0xe1, 0x95, 0x6b, 0xef, 0x76, 0x5d, 0x87, 0x3a, 0x66,
	0x95, 0x8e, 0x9b, 0x74, 0x2a, 0x9b, 0x8e, 0x18, 0x7f, 0x49, 0xbf, 0x25, 0x70, 0x01, 0x47, 0x38,
	0x9d, 0xe8, 0x4c, 0x21, 0x6e, 0x02, 0xda, 0x3b, 0x5d, 0x54, 0x20, 0xdd, 0x69, 0x45, 0xd7, 0xa0,
	0xe3, 0xd9, 0xe8, 0xa2, 0x79, 0xd0, 0x9f, 0x08, 0xe4, 0x23, 0xee, 0x40, 0xa7, 0x3a, 0x9f, 0x7c,
	0xda, 0x67, 0xb4, 0xe9, 0x2e, 0xab, 0x90, 0xf3, 0x8c, 0xe2, 0x3c, 0x45, 0x27, 0xb3, 0x71, 0x8e,
	0xda, 0x15, 0xfd, 0x93, 0x40, 0x21, 0xc9, 0x72, 0xe8, 0x5c, 0x67, 0x2e, 0x29, 0x7e, 0xa6, 0xcd,
	0x9f, 0xb5, 0x1c, 0x35, 0x2d, 0x2b, 0x4d, 0xf3, 0x74, 0x36, 0x9b, 0xa6, 0xb8, 0x2b, 0x9a, 0x75,
	0x14, 0xf1, 0x23, 0x81, 0x1e, 0xe5, 0x0a, 0xb4, 0xdc, 0x99, 0x4f, 0xd4, 0xe7, 0x34, 0x23, 0xf3,
	0x7e, 0x24, 0x7c, 0x47, 0x11, 0xbe, 0x4d, 0xe7, 0xb3, 0x11, 0x56, 0xe6, 0x67, 0xec, 0x3f, 0xeb,
	0xa5, 0x07, 0xf4, 0x77, 0x02, 0x97, 0x9f, 0x75, 0x1a, 0xfa, 0x7e, 0x67, 0x36, 0x6d, 0xec, 0x4e,
	0x9b, 0x39, 0x4b, 0x29, 0x6a, 0xfa, 0x48, 0x69, 0x5a, 0xa2, 0x0b, 0x1d, 0x34, 0xb5, 0x4c, 0x4a,
	0x1a, 0xfb, 0x71, 0x1b, 0x3b, 0x30, 0x02, 0x1b, 0xa4, 0x4f, 0x09, 0xd0, 0xd3, 0x9e, 0x42, 0x6f,
	0x65, 0xeb, 0xf8, 0x44, 0xd3, 0xd4, 0x66, 0xcf, 0x56, 0x8c, 0xe2, 0xee, 0x29, 0x71, 0x6b, 0x74,
	0xe5, 0x7f, 0x88, 0x4b, 0xb2, 0x57, 0xfa, 0x03, 0x81, 0x7c, 0xc4, 0xf4, 0xb2, 0xcc, 0x82, 0xd3,
	0xf6, 0x99, 0x65, 0x16, 0x24, 0x38, 0xab, 0x7e, 0x43, 0xa9, 0x1a, 0xa7, 0x6f, 0x77, 0x50, 0x25,
	0x9b, 0xb5, 0x66, 0xe0, 0xb6, 0xf4, 0x6b, 0x02, 0xbd, 0x81, 0x1d, 0xd2, 0x0c, 0x7d, 0x1f, 0xf3,
	0x62, 0x6d, 0x22, 0x7b, 0x01, 0x52, 0x1c, 0x57, 0x14, 0xc7, 0xe8, 0xb5, 0x0e, 0x14, 0x03, 0x4b,
	0x5e, 0xfc, 0xf8, 0xf1, 0x51, 0x91, 0x3c, 0x39, 0x2a, 0x92, 0x7f, 0x8e, 0x8a, 0xe4, 0xf0, 0xb8,
	0x98, 0x7b, 0x72, 0x5c, 0xcc, 0xfd, 0x71, 0x5c, 0xcc, 0x7d, 0x36, 0x61, 0xd9, 0x7e, 0x7d, 0x7b,
	0xa3, 0x5c, 0x15, 0x5b, 0xed, 0xa0, 0x1e, 0x84, 0x60, 0xfe, 0x9e, 0xcb, 0xe5, 0x46, 0xaf, 0xda,
	0x72, 0xe3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x58, 0x07, 0x8e, 0x14, 0xf6, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// ExchangeRate returns exchange rate of a denom
	ExchangeRate(ctx context.Context, in *QueryExchangeRateRequest, opts ...grpc.CallOption) (*QueryExchangeRateResponse, error)
	// ExchangeRates returns exchange rates of all denoms
	ExchangeRates(ctx context.Context, in *QueryExchangeRatesRequest, opts ...grpc.CallOption) (*QueryExchangeRatesResponse, error)
	// Actives returns all active denoms
	Actives(ctx context.Context, in *QueryActivesRequest, opts ...grpc.CallOption) (*QueryActivesResponse, error)
	// VoteTargets returns all vote target denoms
	VoteTargets(ctx context.Context, in *QueryVoteTargetsRequest, opts ...grpc.CallOption) (*QueryVoteTargetsResponse, error)
	// PriceSnapshotHistory returns the history of price snapshots for all assets
	PriceSnapshotHistory(ctx context.Context, in *QueryPriceSnapshotHistoryRequest, opts ...grpc.CallOption) (*QueryPriceSnapshotHistoryResponse, error)
	Twaps(ctx context.Context, in *QueryTwapsRequest, opts ...grpc.CallOption) (*QueryTwapsResponse, error)
	// FeederDelegation returns feeder delegation of a validator
	FeederDelegation(ctx context.Context, in *QueryFeederDelegationRequest, opts ...grpc.CallOption) (*QueryFeederDelegationResponse, error)
	// MissCounter returns oracle miss counter of a validator
	VotePenaltyCounter(ctx context.Context, in *QueryVotePenaltyCounterRequest, opts ...grpc.CallOption) (*QueryVotePenaltyCounterResponse, error)
	// SlashWindow returns slash window information
	SlashWindow(ctx context.Context, in *QuerySlashWindowRequest, opts ...grpc.CallOption) (*QuerySlashWindowResponse, error)
	// Params queries all parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	_ = "STUB: not implemented"
	return *new(QueryClient)
}

func (c *queryClient) ExchangeRate(ctx context.Context, in *QueryExchangeRateRequest, opts ...grpc.CallOption) (*QueryExchangeRateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) ExchangeRates(ctx context.Context, in *QueryExchangeRatesRequest, opts ...grpc.CallOption) (*QueryExchangeRatesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) Actives(ctx context.Context, in *QueryActivesRequest, opts ...grpc.CallOption) (*QueryActivesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) VoteTargets(ctx context.Context, in *QueryVoteTargetsRequest, opts ...grpc.CallOption) (*QueryVoteTargetsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) PriceSnapshotHistory(ctx context.Context, in *QueryPriceSnapshotHistoryRequest, opts ...grpc.CallOption) (*QueryPriceSnapshotHistoryResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) Twaps(ctx context.Context, in *QueryTwapsRequest, opts ...grpc.CallOption) (*QueryTwapsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) FeederDelegation(ctx context.Context, in *QueryFeederDelegationRequest, opts ...grpc.CallOption) (*QueryFeederDelegationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) VotePenaltyCounter(ctx context.Context, in *QueryVotePenaltyCounterRequest, opts ...grpc.CallOption) (*QueryVotePenaltyCounterResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) SlashWindow(ctx context.Context, in *QuerySlashWindowRequest, opts ...grpc.CallOption) (*QuerySlashWindowResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// ExchangeRate returns exchange rate of a denom
	ExchangeRate(context.Context, *QueryExchangeRateRequest) (*QueryExchangeRateResponse, error)
	// ExchangeRates returns exchange rates of all denoms
	ExchangeRates(context.Context, *QueryExchangeRatesRequest) (*QueryExchangeRatesResponse, error)
	// Actives returns all active denoms
	Actives(context.Context, *QueryActivesRequest) (*QueryActivesResponse, error)
	// VoteTargets returns all vote target denoms
	VoteTargets(context.Context, *QueryVoteTargetsRequest) (*QueryVoteTargetsResponse, error)
	// PriceSnapshotHistory returns the history of price snapshots for all assets
	PriceSnapshotHistory(context.Context, *QueryPriceSnapshotHistoryRequest) (*QueryPriceSnapshotHistoryResponse, error)
	Twaps(context.Context, *QueryTwapsRequest) (*QueryTwapsResponse, error)
	// FeederDelegation returns feeder delegation of a validator
	FeederDelegation(context.Context, *QueryFeederDelegationRequest) (*QueryFeederDelegationResponse, error)
	// MissCounter returns oracle miss counter of a validator
	VotePenaltyCounter(context.Context, *QueryVotePenaltyCounterRequest) (*QueryVotePenaltyCounterResponse, error)
	// SlashWindow returns slash window information
	SlashWindow(context.Context, *QuerySlashWindowRequest) (*QuerySlashWindowResponse, error)
	// Params queries all parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ExchangeRate(ctx context.Context, req *QueryExchangeRateRequest) (*QueryExchangeRateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) ExchangeRates(ctx context.Context, req *QueryExchangeRatesRequest) (*QueryExchangeRatesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) Actives(ctx context.Context, req *QueryActivesRequest) (*QueryActivesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) VoteTargets(ctx context.Context, req *QueryVoteTargetsRequest) (*QueryVoteTargetsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) PriceSnapshotHistory(ctx context.Context, req *QueryPriceSnapshotHistoryRequest) (*QueryPriceSnapshotHistoryResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) Twaps(ctx context.Context, req *QueryTwapsRequest) (*QueryTwapsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) FeederDelegation(ctx context.Context, req *QueryFeederDelegationRequest) (*QueryFeederDelegationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) VotePenaltyCounter(ctx context.Context, req *QueryVotePenaltyCounterRequest) (*QueryVotePenaltyCounterResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) SlashWindow(ctx context.Context, req *QuerySlashWindowRequest) (*QuerySlashWindowResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) { _ = "STUB: not implemented"; return }

func _Query_ExchangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_ExchangeRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_Actives_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_VoteTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_PriceSnapshotHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_Twaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_FeederDelegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_VotePenaltyCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_SlashWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seiprotocol.seichain.oracle.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExchangeRate",
			Handler:    _Query_ExchangeRate_Handler,
		},
		{
			MethodName: "ExchangeRates",
			Handler:    _Query_ExchangeRates_Handler,
		},
		{
			MethodName: "Actives",
			Handler:    _Query_Actives_Handler,
		},
		{
			MethodName: "VoteTargets",
			Handler:    _Query_VoteTargets_Handler,
		},
		{
			MethodName: "PriceSnapshotHistory",
			Handler:    _Query_PriceSnapshotHistory_Handler,
		},
		{
			MethodName: "Twaps",
			Handler:    _Query_Twaps_Handler,
		},
		{
			MethodName: "FeederDelegation",
			Handler:    _Query_FeederDelegation_Handler,
		},
		{
			MethodName: "VotePenaltyCounter",
			Handler:    _Query_VotePenaltyCounter_Handler,
		},
		{
			MethodName: "SlashWindow",
			Handler:    _Query_SlashWindow_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oracle/query.proto",
}

func (m *QueryExchangeRateRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryExchangeRateRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryExchangeRateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryExchangeRateResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryExchangeRateResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryExchangeRateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryExchangeRatesRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryExchangeRatesRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryExchangeRatesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DenomOracleExchangeRatePair) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DenomOracleExchangeRatePair) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DenomOracleExchangeRatePair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryExchangeRatesResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryExchangeRatesResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryExchangeRatesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryActivesRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryActivesRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryActivesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryActivesResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryActivesResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryActivesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryVoteTargetsRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryVoteTargetsRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryVoteTargetsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryVoteTargetsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryVoteTargetsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryVoteTargetsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPriceSnapshotHistoryRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPriceSnapshotHistoryRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPriceSnapshotHistoryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPriceSnapshotHistoryResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPriceSnapshotHistoryResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPriceSnapshotHistoryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryTwapsRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryTwapsRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryTwapsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryTwapsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryTwapsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryTwapsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryFeederDelegationRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryFeederDelegationRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryFeederDelegationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryFeederDelegationResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryFeederDelegationResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryFeederDelegationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryVotePenaltyCounterRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryVotePenaltyCounterRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryVotePenaltyCounterRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryVotePenaltyCounterResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryVotePenaltyCounterResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryVotePenaltyCounterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QuerySlashWindowRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QuerySlashWindowRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QuerySlashWindowRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QuerySlashWindowResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QuerySlashWindowResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QuerySlashWindowResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *QueryExchangeRateRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryExchangeRateResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryExchangeRatesRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DenomOracleExchangeRatePair) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryExchangeRatesResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryActivesRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryActivesResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryVoteTargetsRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryVoteTargetsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryPriceSnapshotHistoryRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryPriceSnapshotHistoryResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryTwapsRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryTwapsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryFeederDelegationRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryFeederDelegationResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryVotePenaltyCounterRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryVotePenaltyCounterResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QuerySlashWindowRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QuerySlashWindowResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryParamsRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryParamsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovQuery(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozQuery(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryExchangeRateRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryExchangeRateResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryExchangeRatesRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *DenomOracleExchangeRatePair) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryExchangeRatesResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryActivesRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryActivesResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryVoteTargetsRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryVoteTargetsResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPriceSnapshotHistoryRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPriceSnapshotHistoryResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryTwapsRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryTwapsResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryFeederDelegationRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryFeederDelegationResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryVotePenaltyCounterRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryVotePenaltyCounterResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QuerySlashWindowRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QuerySlashWindowResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipQuery(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
