// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: protoutils/testonly.proto

package pb

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestonlyMsg struct {
	state                protoimpl.MessageState    `protogen:"open.v1"`
	StringValue          string                    `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	RepeatedValue        []string                  `protobuf:"bytes,2,rep,name=repeated_value,json=repeatedValue,proto3" json:"repeated_value,omitempty"`
	MapValue             map[string]string         `protobuf:"bytes,3,rep,name=map_value,json=mapValue,proto3" json:"map_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RepeatedMessageValue []*TestonlyChild          `protobuf:"bytes,4,rep,name=repeated_message_value,json=repeatedMessageValue,proto3" json:"repeated_message_value,omitempty"`
	MapMessageValue      map[string]*TestonlyChild `protobuf:"bytes,5,rep,name=map_message_value,json=mapMessageValue,proto3" json:"map_message_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TestonlyMsg) Reset() { _ = "STUB: not implemented"; return }

func (x *TestonlyMsg) String() string { _ = "STUB: not implemented"; return "" }

func (*TestonlyMsg) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *TestonlyMsg) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use TestonlyMsg.ProtoReflect.Descriptor instead.
func (*TestonlyMsg) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *TestonlyMsg) GetStringValue() string { _ = "STUB: not implemented"; return "" }

func (x *TestonlyMsg) GetRepeatedValue() []string { _ = "STUB: not implemented"; return nil }

func (x *TestonlyMsg) GetMapValue() map[string]string { _ = "STUB: not implemented"; return nil }

func (x *TestonlyMsg) GetRepeatedMessageValue() []*TestonlyChild {
	_ = "STUB: not implemented"
	return nil
}

func (x *TestonlyMsg) GetMapMessageValue() map[string]*TestonlyChild {
	_ = "STUB: not implemented"
	return nil
}

type TestonlyChild struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestonlyChild) Reset() { _ = "STUB: not implemented"; return }

func (x *TestonlyChild) String() string { _ = "STUB: not implemented"; return "" }

func (*TestonlyChild) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *TestonlyChild) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use TestonlyChild.ProtoReflect.Descriptor instead.
func (*TestonlyChild) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *TestonlyChild) GetValue() string { _ = "STUB: not implemented"; return "" }

var File_protoutils_testonly_proto protoreflect.FileDescriptor

const file_protoutils_testonly_proto_rawDesc = "" +
	"\n" +
	"\x19protoutils/testonly.proto\x12\n" +
	"protoutils\"\xe2\x03\n" +
	"\vTestonlyMsg\x12!\n" +
	"\fstring_value\x18\x01 \x01(\tR\vstringValue\x12%\n" +
	"\x0erepeated_value\x18\x02 \x03(\tR\rrepeatedValue\x12B\n" +
	"\tmap_value\x18\x03 \x03(\v2%.protoutils.TestonlyMsg.MapValueEntryR\bmapValue\x12O\n" +
	"\x16repeated_message_value\x18\x04 \x03(\v2\x19.protoutils.TestonlyChildR\x14repeatedMessageValue\x12X\n" +
	"\x11map_message_value\x18\x05 \x03(\v2,.protoutils.TestonlyMsg.MapMessageValueEntryR\x0fmapMessageValue\x1a;\n" +
	"\rMapValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a]\n" +
	"\x14MapMessageValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.protoutils.TestonlyChildR\x05value:\x028\x01\"%\n" +
	"\rTestonlyChild\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueBIZGgithub.com/sei-protocol/sei-chain/sei-tendermint/internal/protoutils/pbb\x06proto3"

var (
	file_protoutils_testonly_proto_rawDescOnce sync.Once
	file_protoutils_testonly_proto_rawDescData []byte
)

func file_protoutils_testonly_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_protoutils_testonly_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protoutils_testonly_proto_goTypes = []any{
	(*TestonlyMsg)(nil),   // 0: protoutils.TestonlyMsg
	(*TestonlyChild)(nil), // 1: protoutils.TestonlyChild
	nil,                   // 2: protoutils.TestonlyMsg.MapValueEntry
	nil,                   // 3: protoutils.TestonlyMsg.MapMessageValueEntry
}
var file_protoutils_testonly_proto_depIdxs = []int32{
	2, // 0: protoutils.TestonlyMsg.map_value:type_name -> protoutils.TestonlyMsg.MapValueEntry
	1, // 1: protoutils.TestonlyMsg.repeated_message_value:type_name -> protoutils.TestonlyChild
	3, // 2: protoutils.TestonlyMsg.map_message_value:type_name -> protoutils.TestonlyMsg.MapMessageValueEntry
	1, // 3: protoutils.TestonlyMsg.MapMessageValueEntry.value:type_name -> protoutils.TestonlyChild
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init()                                { file_protoutils_testonly_proto_init() }
func file_protoutils_testonly_proto_init() { _ = "STUB: not implemented"; return }
