// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/base/store/v1beta1/commit_info.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CommitInfo defines commit information used by the multi-store when committing
// a version/height.
type CommitInfo struct {
	Version    int64       `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	StoreInfos []StoreInfo `protobuf:"bytes,2,rep,name=store_infos,json=storeInfos,proto3" json:"store_infos"`
}

func (m *CommitInfo) Reset()                    { _ = "STUB: not implemented"; return }
func (m *CommitInfo) String() string            { _ = "STUB: not implemented"; return "" }
func (*CommitInfo) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*CommitInfo) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *CommitInfo) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CommitInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CommitInfo) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *CommitInfo) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *CommitInfo) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_CommitInfo proto.InternalMessageInfo

func (m *CommitInfo) GetVersion() int64 { _ = "STUB: not implemented"; return 0 }

func (m *CommitInfo) GetStoreInfos() []StoreInfo { _ = "STUB: not implemented"; return nil }

// StoreInfo defines store-specific commit information. It contains a reference
// between a store name and the commit ID.
type StoreInfo struct {
	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CommitId CommitID `protobuf:"bytes,2,opt,name=commit_id,json=commitId,proto3" json:"commit_id"`
}

func (m *StoreInfo) Reset()                    { _ = "STUB: not implemented"; return }
func (m *StoreInfo) String() string            { _ = "STUB: not implemented"; return "" }
func (*StoreInfo) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*StoreInfo) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *StoreInfo) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *StoreInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StoreInfo) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *StoreInfo) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *StoreInfo) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_StoreInfo proto.InternalMessageInfo

func (m *StoreInfo) GetName() string { _ = "STUB: not implemented"; return "" }

func (m *StoreInfo) GetCommitId() CommitID { _ = "STUB: not implemented"; return *new(CommitID) }

// CommitID defines the committment information when a specific store is
// committed.
type CommitID struct {
	Version int64  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Hash    []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *CommitID) Reset()                    { _ = "STUB: not implemented"; return }
func (*CommitID) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*CommitID) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *CommitID) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CommitID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CommitID) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *CommitID) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *CommitID) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_CommitID proto.InternalMessageInfo

func (m *CommitID) GetVersion() int64 { _ = "STUB: not implemented"; return 0 }

func (m *CommitID) GetHash() []byte { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*CommitInfo)(nil), "cosmos.base.store.v1beta1.CommitInfo")
	proto.RegisterType((*StoreInfo)(nil), "cosmos.base.store.v1beta1.StoreInfo")
	proto.RegisterType((*CommitID)(nil), "cosmos.base.store.v1beta1.CommitID")
}

func init() {
	proto.RegisterFile("cosmos/base/store/v1beta1/commit_info.proto", fileDescriptor_83f4097f6265b52f)
}

var fileDescriptor_83f4097f6265b52f = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xb1, 0x4e, 0xfb, 0x30,
	0x10, 0xc6, 0x93, 0x36, 0xfa, 0xff, 0x5b, 0x97, 0xc9, 0x62, 0x08, 0x0c, 0x6e, 0x55, 0x18, 0x2a,
	0x21, 0x6c, 0xb5, 0x2c, 0x88, 0x81, 0xa1, 0x20, 0xa4, 0x8a, 0x2d, 0x6c, 0x2c, 0x28, 0x49, 0xdd,
	0xc4, 0x12, 0xc9, 0x55, 0x3d, 0x53, 0x89, 0xb7, 0x60, 0x64, 0xe4, 0x71, 0x3a, 0x76, 0x64, 0x42,
	0xa8, 0x7d, 0x11, 0x94, 0x73, 0xc3, 0x46, 0xb7, 0xef, 0x7c, 0xdf, 0xdd, 0x4f, 0x9f, 0x8f, 0x9d,
	0xa5, 0x80, 0x05, 0xa0, 0x4a, 0x62, 0xd4, 0x0a, 0x2d, 0x2c, 0xb4, 0x5a, 0x0e, 0x13, 0x6d, 0xe3,
	0xa1, 0x4a, 0xa1, 0x28, 0x8c, 0x7d, 0x32, 0xe5, 0x0c, 0xe4, 0x7c, 0x01, 0x16, 0xf8, 0x91, 0x33,
	0xcb, 0xca, 0x2c, 0xc9, 0x2c, 0x77, 0xe6, 0xe3, 0xc3, 0x0c, 0x32, 0x20, 0x97, 0xaa, 0x94, 0x1b,
	0xe8, 0x23, 0x63, 0x37, 0xb4, 0x65, 0x52, 0xce, 0x80, 0x87, 0xec, 0xff, 0x52, 0x2f, 0xd0, 0x40,
	0x19, 0xfa, 0x3d, 0x7f, 0xd0, 0x8c, 0xea, 0x92, 0xdf, 0xb3, 0x0e, 0xad, 0x23, 0x18, 0x86, 0x8d,
	0x5e, 0x73, 0xd0, 0x19, 0x9d, 0xca, 0x3f, 0x71, 0xf2, 0xa1, 0xaa, 0xaa, 0xa5, 0xe3, 0x60, 0xf5,
	0xd5, 0xf5, 0x22, 0x86, 0xf5, 0x03, 0xf6, 0x33, 0xd6, 0xfe, 0x6d, 0x73, 0xce, 0x82, 0x32, 0x2e,
	0x34, 0x01, 0xdb, 0x11, 0x69, 0x7e, 0xc7, 0xda, 0x75, 0xb6, 0x69, 0xd8, 0xe8, 0xf9, 0x83, 0xce,
	0xe8, 0x64, 0x0f, 0x6b, 0x97, 0xe0, 0x76, 0x87, 0x6a, 0xb9, 0xd9, 0xc9, 0xb4, 0x7f, 0xcd, 0x5a,
	0x75, 0x6f, 0x4f, 0x36, 0xce, 0x82, 0x3c, 0xc6, 0x9c, 0x40, 0x07, 0x11, 0xe9, 0xab, 0xe0, 0xfd,
	0xa3, 0xeb, 0x8d, 0xa3, 0xd5, 0x46, 0xf8, 0xeb, 0x8d, 0xf0, 0xbf, 0x37, 0xc2, 0x7f, 0xdb, 0x0a,
	0x6f, 0xbd, 0x15, 0xde, 0xe7, 0x56, 0x78, 0x8f, 0x97, 0x99, 0xb1, 0xf9, 0x4b, 0x22, 0x53, 0x28,
	0x14, 0x6a, 0x73, 0x4e, 0xbf, 0x99, 0xc2, 0x33, 0x15, 0x69, 0x1e, 0x9b, 0xd2, 0x29, 0x77, 0x3b,
	0x77, 0x36, 0xfb, 0x3a, 0xd7, 0x98, 0xfc, 0x23, 0xeb, 0xc5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa1, 0x53, 0x7e, 0x02, 0xd8, 0x01, 0x00, 0x00,
}

func (m *CommitInfo) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *CommitInfo) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *CommitInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StoreInfo) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *StoreInfo) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *StoreInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CommitID) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *CommitID) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *CommitID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintCommitInfo(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *CommitInfo) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StoreInfo) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CommitID) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovCommitInfo(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozCommitInfo(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CommitInfo) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *StoreInfo) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CommitID) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipCommitInfo(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthCommitInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCommitInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCommitInfo = fmt.Errorf("proto: unexpected end of group")
)
