// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/privval/types.proto

package privval

import (
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	crypto "github.com/sei-protocol/sei-chain/sei-tendermint/proto/tendermint/crypto"
	types "github.com/sei-protocol/sei-chain/sei-tendermint/proto/tendermint/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Errors int32

const (
	Errors_ERRORS_UNKNOWN             Errors = 0
	Errors_ERRORS_UNEXPECTED_RESPONSE Errors = 1
	Errors_ERRORS_NO_CONNECTION       Errors = 2
	Errors_ERRORS_CONNECTION_TIMEOUT  Errors = 3
	Errors_ERRORS_READ_TIMEOUT        Errors = 4
	Errors_ERRORS_WRITE_TIMEOUT       Errors = 5
)

var Errors_name = map[int32]string{
	0: "ERRORS_UNKNOWN",
	1: "ERRORS_UNEXPECTED_RESPONSE",
	2: "ERRORS_NO_CONNECTION",
	3: "ERRORS_CONNECTION_TIMEOUT",
	4: "ERRORS_READ_TIMEOUT",
	5: "ERRORS_WRITE_TIMEOUT",
}

var Errors_value = map[string]int32{
	"ERRORS_UNKNOWN":             0,
	"ERRORS_UNEXPECTED_RESPONSE": 1,
	"ERRORS_NO_CONNECTION":       2,
	"ERRORS_CONNECTION_TIMEOUT":  3,
	"ERRORS_READ_TIMEOUT":        4,
	"ERRORS_WRITE_TIMEOUT":       5,
}

func (x Errors) String() string { _ = "STUB: not implemented"; return "" }

func (Errors) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type RemoteSignerError struct {
	Code        int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *RemoteSignerError) Reset()                    { _ = "STUB: not implemented"; return }
func (m *RemoteSignerError) String() string            { _ = "STUB: not implemented"; return "" }
func (*RemoteSignerError) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RemoteSignerError) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RemoteSignerError) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RemoteSignerError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RemoteSignerError) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RemoteSignerError) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RemoteSignerError) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RemoteSignerError proto.InternalMessageInfo

func (m *RemoteSignerError) GetCode() int32 { _ = "STUB: not implemented"; return 0 }

func (m *RemoteSignerError) GetDescription() string { _ = "STUB: not implemented"; return "" }

// PubKeyRequest requests the consensus public key from the remote signer.
type PubKeyRequest struct {
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
}

func (m *PubKeyRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PubKeyRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*PubKeyRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PubKeyRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PubKeyRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PubKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PubKeyRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PubKeyRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PubKeyRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PubKeyRequest proto.InternalMessageInfo

func (m *PubKeyRequest) GetChainId() string { _ = "STUB: not implemented"; return "" }

// PubKeyResponse is a response message containing the public key.
type PubKeyResponse struct {
	PubKey crypto.PublicKey   `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key"`
	Error  *RemoteSignerError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *PubKeyResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PubKeyResponse) String() string            { _ = "STUB: not implemented"; return "" }
func (*PubKeyResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PubKeyResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PubKeyResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PubKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PubKeyResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PubKeyResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PubKeyResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PubKeyResponse proto.InternalMessageInfo

func (m *PubKeyResponse) GetPubKey() crypto.PublicKey {
	_ = "STUB: not implemented"
	return *new(crypto.PublicKey)
}

func (m *PubKeyResponse) GetError() *RemoteSignerError { _ = "STUB: not implemented"; return nil }

// SignVoteRequest is a request to sign a vote
type SignVoteRequest struct {
	Vote    *types.Vote `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote,omitempty"`
	ChainId string      `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
}

func (m *SignVoteRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SignVoteRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*SignVoteRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SignVoteRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SignVoteRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignVoteRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SignVoteRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SignVoteRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SignVoteRequest proto.InternalMessageInfo

func (m *SignVoteRequest) GetVote() *types.Vote { _ = "STUB: not implemented"; return nil }

func (m *SignVoteRequest) GetChainId() string { _ = "STUB: not implemented"; return "" }

// SignedVoteResponse is a response containing a signed vote or an error
type SignedVoteResponse struct {
	Vote  types.Vote         `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote"`
	Error *RemoteSignerError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *SignedVoteResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SignedVoteResponse) String() string            { _ = "STUB: not implemented"; return "" }
func (*SignedVoteResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SignedVoteResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SignedVoteResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignedVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignedVoteResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SignedVoteResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SignedVoteResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SignedVoteResponse proto.InternalMessageInfo

func (m *SignedVoteResponse) GetVote() types.Vote {
	_ = "STUB: not implemented"
	return *new(types.Vote)
}

func (m *SignedVoteResponse) GetError() *RemoteSignerError { _ = "STUB: not implemented"; return nil }

// SignProposalRequest is a request to sign a proposal
type SignProposalRequest struct {
	Proposal *types.Proposal `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	ChainId  string          `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
}

func (m *SignProposalRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *SignProposalRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*SignProposalRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*SignProposalRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignProposalRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignProposalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignProposalRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SignProposalRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SignProposalRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SignProposalRequest proto.InternalMessageInfo

func (m *SignProposalRequest) GetProposal() *types.Proposal { _ = "STUB: not implemented"; return nil }

func (m *SignProposalRequest) GetChainId() string { _ = "STUB: not implemented"; return "" }

// SignedProposalResponse is response containing a signed proposal or an error
type SignedProposalResponse struct {
	Proposal types.Proposal     `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal"`
	Error    *RemoteSignerError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *SignedProposalResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *SignedProposalResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*SignedProposalResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*SignedProposalResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignedProposalResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *SignedProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignedProposalResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SignedProposalResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SignedProposalResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SignedProposalResponse proto.InternalMessageInfo

func (m *SignedProposalResponse) GetProposal() types.Proposal {
	_ = "STUB: not implemented"
	return *new(types.Proposal)
}

func (m *SignedProposalResponse) GetError() *RemoteSignerError {
	_ = "STUB: not implemented"
	return nil
}

// PingRequest is a request to confirm that the connection is alive.
type PingRequest struct {
}

func (m *PingRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PingRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*PingRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PingRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PingRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PingRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PingRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PingRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

// PingResponse is a response to confirm that the connection is alive.
type PingResponse struct {
}

func (m *PingResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PingResponse) String() string            { _ = "STUB: not implemented"; return "" }
func (*PingResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PingResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PingResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PingResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PingResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PingResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

type Message struct {
	// Types that are valid to be assigned to Sum:
	//	*Message_PubKeyRequest
	//	*Message_PubKeyResponse
	//	*Message_SignVoteRequest
	//	*Message_SignedVoteResponse
	//	*Message_SignProposalRequest
	//	*Message_SignedProposalResponse
	//	*Message_PingRequest
	//	*Message_PingResponse
	Sum isMessage_Sum `protobuf_oneof:"sum"`
}

func (m *Message) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Message) String() string            { _ = "STUB: not implemented"; return "" }
func (*Message) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Message) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Message) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Message) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Message) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Message) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Sum interface {
	isMessage_Sum()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Message_PubKeyRequest struct {
	PubKeyRequest *PubKeyRequest `protobuf:"bytes,1,opt,name=pub_key_request,json=pubKeyRequest,proto3,oneof" json:"pub_key_request,omitempty"`
}
type Message_PubKeyResponse struct {
	PubKeyResponse *PubKeyResponse `protobuf:"bytes,2,opt,name=pub_key_response,json=pubKeyResponse,proto3,oneof" json:"pub_key_response,omitempty"`
}
type Message_SignVoteRequest struct {
	SignVoteRequest *SignVoteRequest `protobuf:"bytes,3,opt,name=sign_vote_request,json=signVoteRequest,proto3,oneof" json:"sign_vote_request,omitempty"`
}
type Message_SignedVoteResponse struct {
	SignedVoteResponse *SignedVoteResponse `protobuf:"bytes,4,opt,name=signed_vote_response,json=signedVoteResponse,proto3,oneof" json:"signed_vote_response,omitempty"`
}
type Message_SignProposalRequest struct {
	SignProposalRequest *SignProposalRequest `protobuf:"bytes,5,opt,name=sign_proposal_request,json=signProposalRequest,proto3,oneof" json:"sign_proposal_request,omitempty"`
}
type Message_SignedProposalResponse struct {
	SignedProposalResponse *SignedProposalResponse `protobuf:"bytes,6,opt,name=signed_proposal_response,json=signedProposalResponse,proto3,oneof" json:"signed_proposal_response,omitempty"`
}
type Message_PingRequest struct {
	PingRequest *PingRequest `protobuf:"bytes,7,opt,name=ping_request,json=pingRequest,proto3,oneof" json:"ping_request,omitempty"`
}
type Message_PingResponse struct {
	PingResponse *PingResponse `protobuf:"bytes,8,opt,name=ping_response,json=pingResponse,proto3,oneof" json:"ping_response,omitempty"`
}

func (*Message_PubKeyRequest) isMessage_Sum()          { _ = "STUB: not implemented"; return }
func (*Message_PubKeyResponse) isMessage_Sum()         { _ = "STUB: not implemented"; return }
func (*Message_SignVoteRequest) isMessage_Sum()        { _ = "STUB: not implemented"; return }
func (*Message_SignedVoteResponse) isMessage_Sum()     { _ = "STUB: not implemented"; return }
func (*Message_SignProposalRequest) isMessage_Sum()    { _ = "STUB: not implemented"; return }
func (*Message_SignedProposalResponse) isMessage_Sum() { _ = "STUB: not implemented"; return }
func (*Message_PingRequest) isMessage_Sum()            { _ = "STUB: not implemented"; return }
func (*Message_PingResponse) isMessage_Sum()           { _ = "STUB: not implemented"; return }

func (m *Message) GetSum() isMessage_Sum { _ = "STUB: not implemented"; return *new(isMessage_Sum) }

func (m *Message) GetPubKeyRequest() *PubKeyRequest { _ = "STUB: not implemented"; return nil }

func (m *Message) GetPubKeyResponse() *PubKeyResponse { _ = "STUB: not implemented"; return nil }

func (m *Message) GetSignVoteRequest() *SignVoteRequest { _ = "STUB: not implemented"; return nil }

func (m *Message) GetSignedVoteResponse() *SignedVoteResponse {
	_ = "STUB: not implemented"
	return nil
}

func (m *Message) GetSignProposalRequest() *SignProposalRequest {
	_ = "STUB: not implemented"
	return nil
}

func (m *Message) GetSignedProposalResponse() *SignedProposalResponse {
	_ = "STUB: not implemented"
	return nil
}

func (m *Message) GetPingRequest() *PingRequest { _ = "STUB: not implemented"; return nil }

func (m *Message) GetPingResponse() *PingResponse { _ = "STUB: not implemented"; return nil }

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

// AuthSigMessage is duplicated from p2p prior to the P2P refactor.
// It is used for the SecretConnection until we migrate privval to gRPC.
// https://github.com/tendermint/tendermint/issues/4698
type AuthSigMessage struct {
	PubKey crypto.PublicKey `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key"`
	Sig    []byte           `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (m *AuthSigMessage) Reset()                    { _ = "STUB: not implemented"; return }
func (m *AuthSigMessage) String() string            { _ = "STUB: not implemented"; return "" }
func (*AuthSigMessage) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*AuthSigMessage) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *AuthSigMessage) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AuthSigMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AuthSigMessage) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *AuthSigMessage) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *AuthSigMessage) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_AuthSigMessage proto.InternalMessageInfo

func (m *AuthSigMessage) GetPubKey() crypto.PublicKey {
	_ = "STUB: not implemented"
	return *new(crypto.PublicKey)
}

func (m *AuthSigMessage) GetSig() []byte { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterEnum("tendermint.privval.Errors", Errors_name, Errors_value)
	proto.RegisterType((*RemoteSignerError)(nil), "tendermint.privval.RemoteSignerError")
	proto.RegisterType((*PubKeyRequest)(nil), "tendermint.privval.PubKeyRequest")
	proto.RegisterType((*PubKeyResponse)(nil), "tendermint.privval.PubKeyResponse")
	proto.RegisterType((*SignVoteRequest)(nil), "tendermint.privval.SignVoteRequest")
	proto.RegisterType((*SignedVoteResponse)(nil), "tendermint.privval.SignedVoteResponse")
	proto.RegisterType((*SignProposalRequest)(nil), "tendermint.privval.SignProposalRequest")
	proto.RegisterType((*SignedProposalResponse)(nil), "tendermint.privval.SignedProposalResponse")
	proto.RegisterType((*PingRequest)(nil), "tendermint.privval.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "tendermint.privval.PingResponse")
	proto.RegisterType((*Message)(nil), "tendermint.privval.Message")
	proto.RegisterType((*AuthSigMessage)(nil), "tendermint.privval.AuthSigMessage")
}

func init() { proto.RegisterFile("tendermint/privval/types.proto", fileDescriptor_cb4e437a5328cf9c) }

var fileDescriptor_cb4e437a5328cf9c = []byte{
	// 786 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcb, 0x6e, 0xf3, 0x44,
	0x14, 0xb6, 0x9b, 0x5b, 0xff, 0x93, 0x4b, 0xf3, 0x4f, 0x4b, 0x49, 0xa3, 0xe2, 0x06, 0x23, 0xa0,
	0x8a, 0x44, 0x82, 0x8a, 0xc4, 0xa6, 0x6c, 0x7a, 0xb1, 0x48, 0x14, 0xd5, 0x09, 0x93, 0x94, 0x56,
	0x95, 0x90, 0x95, 0x38, 0x83, 0x63, 0x35, 0xf1, 0x18, 0x8f, 0x53, 0x29, 0x6b, 0x76, 0xac, 0x90,
	0x78, 0x09, 0xd6, 0x3c, 0x45, 0x97, 0x5d, 0xb2, 0x42, 0xa8, 0x7d, 0x11, 0x94, 0xf1, 0xc4, 0x71,
	0x6e, 0x15, 0xbf, 0xba, 0x9b, 0x39, 0xe7, 0xf8, 0xbb, 0x78, 0x3e, 0x7b, 0x40, 0xf1, 0x89, 0xd3,
	0x27, 0xde, 0xc8, 0x76, 0xfc, 0xaa, 0xeb, 0xd9, 0x0f, 0x0f, 0xdd, 0x61, 0xd5, 0x9f, 0xb8, 0x84,
	0x55, 0x5c, 0x8f, 0xfa, 0x14, 0xa1, 0x79, 0xbf, 0x22, 0xfa, 0xc5, 0x3d, 0x8b, 0x5a, 0x94, 0xb7,
	0xab, 0xd3, 0x55, 0x30, 0x59, 0x3c, 0x8c, 0x20, 0x99, 0xde, 0xc4, 0xf5, 0x69, 0xf5, 0x9e, 0x4c,
	0xd8, 0x9a, 0x2e, 0xc7, 0x8f, 0xb2, 0xa8, 0x75, 0x78, 0x8f, 0xc9, 0x88, 0xfa, 0xa4, 0x6d, 0x5b,
	0x0e, 0xf1, 0x34, 0xcf, 0xa3, 0x1e, 0x42, 0x10, 0x37, 0x69, 0x9f, 0x14, 0xe4, 0x92, 0x7c, 0x9c,
	0xc0, 0x7c, 0x8d, 0x4a, 0x90, 0xee, 0x13, 0x66, 0x7a, 0xb6, 0xeb, 0xdb, 0xd4, 0x29, 0x6c, 0x95,
	0xe4, 0xe3, 0x77, 0x38, 0x5a, 0x52, 0xcb, 0x90, 0x6d, 0x8d, 0x7b, 0x0d, 0x32, 0xc1, 0xe4, 0x97,
	0x31, 0x61, 0x3e, 0x3a, 0x80, 0x6d, 0x73, 0xd0, 0xb5, 0x1d, 0xc3, 0xee, 0x73, 0xa8, 0x77, 0x38,
	0xc5, 0xf7, 0xf5, 0xbe, 0xfa, 0x9b, 0x0c, 0xb9, 0xd9, 0x30, 0x73, 0xa9, 0xc3, 0x08, 0x3a, 0x85,
	0x94, 0x3b, 0xee, 0x19, 0xf7, 0x64, 0xc2, 0x87, 0xd3, 0x27, 0x87, 0x95, 0xc8, 0x1b, 0x08, 0x7c,
	0x55, 0x5a, 0xe3, 0xde, 0xd0, 0x36, 0x1b, 0x64, 0x72, 0x1e, 0x7f, 0xfc, 0xe7, 0x48, 0xc2, 0x49,
	0x97, 0x83, 0xa0, 0x53, 0x48, 0x90, 0xa9, 0x74, 0xae, 0x2b, 0x7d, 0xf2, 0x79, 0x65, 0xf5, 0xe5,
	0x55, 0x56, 0x7c, 0xe2, 0xe0, 0x19, 0xf5, 0x16, 0x76, 0xa6, 0xd5, 0x1f, 0xa9, 0x4f, 0x66, 0xd2,
	0xcb, 0x10, 0x7f, 0xa0, 0x3e, 0x11, 0x4a, 0xf6, 0xa3, 0x70, 0xc1, 0xdb, 0xe3, 0xc3, 0x7c, 0x66,
	0xc1, 0xe6, 0xd6, 0xa2, 0xcd, 0x5f, 0x65, 0x40, 0x9c, 0xb0, 0x1f, 0x80, 0x0b, 0xab, 0x5f, 0xff,
	0x1f, 0x74, 0xe1, 0x30, 0xe0, 0x78, 0x93, 0xbf, 0x01, 0xec, 0x4e, 0xab, 0x2d, 0x8f, 0xba, 0x94,
	0x75, 0x87, 0x33, 0x8f, 0xdf, 0xc2, 0xb6, 0x2b, 0x4a, 0x42, 0x49, 0x71, 0x55, 0x49, 0xf8, 0x50,
	0x38, 0xfb, 0x9a, 0xdf, 0x3f, 0x64, 0xd8, 0x0f, 0xfc, 0xce, 0xc9, 0x84, 0xe7, 0xef, 0x3e, 0x84,
	0x4d, 0x78, 0x9f, 0x73, 0xbe, 0xc9, 0x7f, 0x16, 0xd2, 0x2d, 0xdb, 0xb1, 0x84, 0x6f, 0x35, 0x07,
	0x99, 0x60, 0x1b, 0x28, 0x53, 0xff, 0x4a, 0x40, 0xea, 0x8a, 0x30, 0xd6, 0xb5, 0x08, 0x6a, 0xc0,
	0x8e, 0x08, 0xa1, 0xe1, 0x05, 0xe3, 0x42, 0xec, 0xa7, 0xeb, 0x18, 0x17, 0xe2, 0x5e, 0x93, 0x70,
	0xd6, 0x5d, 0xc8, 0xbf, 0x0e, 0xf9, 0x39, 0x58, 0x40, 0x26, 0xf4, 0xab, 0xaf, 0xa1, 0x05, 0x93,
	0x35, 0x09, 0xe7, 0xdc, 0xc5, 0x2f, 0xe4, 0x07, 0x78, 0xcf, 0x6c, 0xcb, 0x31, 0xa6, 0x89, 0x08,
	0xe5, 0xc5, 0x38, 0xe0, 0x67, 0xeb, 0x00, 0x97, 0x42, 0x5d, 0x93, 0xf0, 0x0e, 0x5b, 0xca, 0xf9,
	0x1d, 0xec, 0x31, 0x7e, 0x5e, 0x33, 0x50, 0x21, 0x33, 0xce, 0x51, 0xbf, 0xd8, 0x84, 0xba, 0x98,
	0xe7, 0x9a, 0x84, 0x11, 0x5b, 0x4d, 0xf9, 0x4f, 0xf0, 0x11, 0x97, 0x3b, 0x3b, 0xc4, 0x50, 0x72,
	0x82, 0x83, 0x7f, 0xb9, 0x09, 0x7c, 0x29, 0xa7, 0x35, 0x09, 0xef, 0xb2, 0x35, 0xf1, 0xfd, 0x19,
	0x0a, 0x42, 0x7a, 0x84, 0x40, 0xc8, 0x4f, 0x72, 0x86, 0xf2, 0x66, 0xf9, 0xcb, 0xf1, 0xac, 0x49,
	0x78, 0x9f, 0xad, 0x0f, 0xee, 0x25, 0x64, 0x5c, 0xdb, 0xb1, 0x42, 0xf5, 0x29, 0x8e, 0x7d, 0xb4,
	0xf6, 0x04, 0xe7, 0x29, 0xab, 0x49, 0x38, 0xed, 0xce, 0xb7, 0xe8, 0x7b, 0xc8, 0x0a, 0x14, 0x21,
	0x71, 0x9b, 0xc3, 0x94, 0x36, 0xc3, 0x84, 0xc2, 0x32, 0x6e, 0x64, 0x7f, 0x9e, 0x80, 0x18, 0x1b,
	0x8f, 0x54, 0x03, 0x72, 0x67, 0x63, 0x7f, 0xd0, 0xb6, 0xad, 0x59, 0x74, 0xdf, 0xf4, 0xff, 0xcc,
	0x43, 0x8c, 0xd9, 0x16, 0x4f, 0x67, 0x06, 0x4f, 0x97, 0xe5, 0x3f, 0x65, 0x48, 0xf2, 0xaf, 0x88,
	0x21, 0x04, 0x39, 0x0d, 0xe3, 0x26, 0x6e, 0x1b, 0xd7, 0x7a, 0x43, 0x6f, 0xde, 0xe8, 0x79, 0x09,
	0x29, 0x50, 0x0c, 0x6b, 0xda, 0x6d, 0x4b, 0xbb, 0xe8, 0x68, 0x97, 0x06, 0xd6, 0xda, 0xad, 0xa6,
	0xde, 0xd6, 0xf2, 0x32, 0x2a, 0xc0, 0x9e, 0xe8, 0xeb, 0x4d, 0xe3, 0xa2, 0xa9, 0xeb, 0xda, 0x45,
	0xa7, 0xde, 0xd4, 0xf3, 0x5b, 0xe8, 0x13, 0x38, 0x10, 0x9d, 0x79, 0xd9, 0xe8, 0xd4, 0xaf, 0xb4,
	0xe6, 0x75, 0x27, 0x1f, 0x43, 0x1f, 0xc3, 0xae, 0x68, 0x63, 0xed, 0xec, 0x32, 0x6c, 0xc4, 0x23,
	0x88, 0x37, 0xb8, 0xde, 0xd1, 0xc2, 0x4e, 0xe2, 0xdc, 0x7c, 0x7c, 0x56, 0xe4, 0xa7, 0x67, 0x45,
	0xfe, 0xf7, 0x59, 0x91, 0x7f, 0x7f, 0x51, 0xa4, 0xa7, 0x17, 0x45, 0xfa, 0xfb, 0x45, 0x91, 0xee,
	0xea, 0x96, 0xed, 0x0f, 0xc6, 0xbd, 0x8a, 0x49, 0x47, 0x55, 0x46, 0xec, 0xaf, 0xf8, 0x9d, 0x67,
	0xd2, 0x21, 0xdf, 0xf0, 0x9f, 0x16, 0x5f, 0x2d, 0xdc, 0xc4, 0xd3, 0xcb, 0x75, 0xf5, 0x6a, 0xee,
	0x25, 0x79, 0xe7, 0x9b, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x98, 0x0a, 0xcc, 0xb7, 0x07,
	0x00, 0x00,
}

func (m *RemoteSignerError) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RemoteSignerError) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RemoteSignerError) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PubKeyRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PubKeyRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PubKeyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PubKeyResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PubKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PubKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignVoteRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignVoteRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignVoteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignedVoteResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignedVoteResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignedVoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignProposalRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignProposalRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignProposalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignedProposalResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignedProposalResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignedProposalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PingRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PingRequest) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *PingRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PingResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PingResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Message) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PubKeyRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PubKeyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PubKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PubKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignVoteRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignVoteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignedVoteResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignedVoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignProposalRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignProposalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignedProposalResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_SignedProposalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PingRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PingRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PingResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message_PingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AuthSigMessage) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AuthSigMessage) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AuthSigMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *RemoteSignerError) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PubKeyRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PubKeyResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SignVoteRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SignedVoteResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SignProposalRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SignedProposalResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PingRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PingResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_PubKeyRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_PubKeyResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_SignVoteRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_SignedVoteResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_SignProposalRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_SignedProposalResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_PingRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message_PingResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AuthSigMessage) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozTypes(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RemoteSignerError) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PubKeyRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PubKeyResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignVoteRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignedVoteResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignProposalRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignedProposalResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PingRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PingResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Message) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AuthSigMessage) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipTypes(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
