// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: p2p/giga/api.proto

package pb

import (
	sync "sync"

	pb "github.com/sei-protocol/sei-chain/sei-tendermint/internal/autobahn/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LaneReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LaneProposal  *pb.SignedMsg          `protobuf:"bytes,1,opt,name=lane_proposal,json=laneProposal,proto3" json:"lane_proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaneReq) Reset() { _ = "STUB: not implemented"; return }

func (x *LaneReq) String() string { _ = "STUB: not implemented"; return "" }

func (*LaneReq) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *LaneReq) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use LaneReq.ProtoReflect.Descriptor instead.
func (*LaneReq) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *LaneReq) GetLaneProposal() *pb.SignedMsg { _ = "STUB: not implemented"; return nil }

type LaneResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LaneVote      *pb.SignedMsg          `protobuf:"bytes,1,opt,name=lane_vote,json=laneVote,proto3" json:"lane_vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaneResp) Reset() { _ = "STUB: not implemented"; return }

func (x *LaneResp) String() string { _ = "STUB: not implemented"; return "" }

func (*LaneResp) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *LaneResp) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use LaneResp.ProtoReflect.Descriptor instead.
func (*LaneResp) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *LaneResp) GetLaneVote() *pb.SignedMsg { _ = "STUB: not implemented"; return nil }

type LaneQCsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaneQCsResp) Reset() { _ = "STUB: not implemented"; return }

func (x *LaneQCsResp) String() string { _ = "STUB: not implemented"; return "" }

func (*LaneQCsResp) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *LaneQCsResp) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use LaneQCsResp.ProtoReflect.Descriptor instead.
func (*LaneQCsResp) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type ConsensusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusResp) Reset() { _ = "STUB: not implemented"; return }

func (x *ConsensusResp) String() string { _ = "STUB: not implemented"; return "" }

func (*ConsensusResp) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ConsensusResp) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ConsensusResp.ProtoReflect.Descriptor instead.
func (*ConsensusResp) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() { _ = "STUB: not implemented"; return }

func (x *PingReq) String() string { _ = "STUB: not implemented"; return "" }

func (*PingReq) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PingReq) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() { _ = "STUB: not implemented"; return }

func (x *PingResp) String() string { _ = "STUB: not implemented"; return "" }

func (*PingResp) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PingResp) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type LaneVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LaneVote      *pb.SignedMsg          `protobuf:"bytes,1,opt,name=lane_vote,json=laneVote,proto3" json:"lane_vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaneVote) Reset() { _ = "STUB: not implemented"; return }

func (x *LaneVote) String() string { _ = "STUB: not implemented"; return "" }

func (*LaneVote) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *LaneVote) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use LaneVote.ProtoReflect.Descriptor instead.
func (*LaneVote) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *LaneVote) GetLaneVote() *pb.SignedMsg { _ = "STUB: not implemented"; return nil }

type LaneProposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LaneProposal  *pb.SignedMsg          `protobuf:"bytes,1,opt,name=lane_proposal,json=laneProposal,proto3" json:"lane_proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaneProposal) Reset() { _ = "STUB: not implemented"; return }

func (x *LaneProposal) String() string { _ = "STUB: not implemented"; return "" }

func (*LaneProposal) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *LaneProposal) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use LaneProposal.ProtoReflect.Descriptor instead.
func (*LaneProposal) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *LaneProposal) GetLaneProposal() *pb.SignedMsg { _ = "STUB: not implemented"; return nil }

type AppVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppVote       *pb.SignedMsg          `protobuf:"bytes,1,opt,name=app_vote,json=appVote,proto3" json:"app_vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppVote) Reset() { _ = "STUB: not implemented"; return }

func (x *AppVote) String() string { _ = "STUB: not implemented"; return "" }

func (*AppVote) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *AppVote) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use AppVote.ProtoReflect.Descriptor instead.
func (*AppVote) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *AppVote) GetAppVote() *pb.SignedMsg { _ = "STUB: not implemented"; return nil }

type StreamLaneProposalsReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FirstBlockNumber uint64                 `protobuf:"varint,1,opt,name=first_block_number,json=firstBlockNumber,proto3" json:"first_block_number,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamLaneProposalsReq) Reset() { _ = "STUB: not implemented"; return }

func (x *StreamLaneProposalsReq) String() string { _ = "STUB: not implemented"; return "" }

func (*StreamLaneProposalsReq) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StreamLaneProposalsReq) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StreamLaneProposalsReq.ProtoReflect.Descriptor instead.
func (*StreamLaneProposalsReq) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *StreamLaneProposalsReq) GetFirstBlockNumber() uint64 { _ = "STUB: not implemented"; return 0 }

type StreamAppQCsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAppQCsReq) Reset() { _ = "STUB: not implemented"; return }

func (x *StreamAppQCsReq) String() string { _ = "STUB: not implemented"; return "" }

func (*StreamAppQCsReq) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StreamAppQCsReq) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StreamAppQCsReq.ProtoReflect.Descriptor instead.
func (*StreamAppQCsReq) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type StreamAppQCsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppQc         *pb.AppQC              `protobuf:"bytes,1,opt,name=app_qc,json=appQc,proto3" json:"app_qc,omitempty"`
	CommitQc      *pb.CommitQC           `protobuf:"bytes,2,opt,name=commit_qc,json=commitQc,proto3" json:"commit_qc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAppQCsResp) Reset() { _ = "STUB: not implemented"; return }

func (x *StreamAppQCsResp) String() string { _ = "STUB: not implemented"; return "" }

func (*StreamAppQCsResp) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StreamAppQCsResp) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StreamAppQCsResp.ProtoReflect.Descriptor instead.
func (*StreamAppQCsResp) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *StreamAppQCsResp) GetAppQc() *pb.AppQC { _ = "STUB: not implemented"; return nil }

func (x *StreamAppQCsResp) GetCommitQc() *pb.CommitQC { _ = "STUB: not implemented"; return nil }

type StreamCommitQCsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCommitQCsReq) Reset() { _ = "STUB: not implemented"; return }

func (x *StreamCommitQCsReq) String() string { _ = "STUB: not implemented"; return "" }

func (*StreamCommitQCsReq) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StreamCommitQCsReq) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StreamCommitQCsReq.ProtoReflect.Descriptor instead.
func (*StreamCommitQCsReq) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type StreamLaneVotesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLaneVotesReq) Reset() { _ = "STUB: not implemented"; return }

func (x *StreamLaneVotesReq) String() string { _ = "STUB: not implemented"; return "" }

func (*StreamLaneVotesReq) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StreamLaneVotesReq) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StreamLaneVotesReq.ProtoReflect.Descriptor instead.
func (*StreamLaneVotesReq) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type StreamAppVotesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAppVotesReq) Reset() { _ = "STUB: not implemented"; return }

func (x *StreamAppVotesReq) String() string { _ = "STUB: not implemented"; return "" }

func (*StreamAppVotesReq) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StreamAppVotesReq) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StreamAppVotesReq.ProtoReflect.Descriptor instead.
func (*StreamAppVotesReq) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type GetBlockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalNumber  uint64                 `protobuf:"varint,1,opt,name=global_number,json=globalNumber,proto3" json:"global_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockReq) Reset() { _ = "STUB: not implemented"; return }

func (x *GetBlockReq) String() string { _ = "STUB: not implemented"; return "" }

func (*GetBlockReq) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *GetBlockReq) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use GetBlockReq.ProtoReflect.Descriptor instead.
func (*GetBlockReq) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *GetBlockReq) GetGlobalNumber() uint64 { _ = "STUB: not implemented"; return 0 }

type GetBlockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *pb.Block              `protobuf:"bytes,1,opt,name=block,proto3,oneof" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockResp) Reset() { _ = "STUB: not implemented"; return }

func (x *GetBlockResp) String() string { _ = "STUB: not implemented"; return "" }

func (*GetBlockResp) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *GetBlockResp) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use GetBlockResp.ProtoReflect.Descriptor instead.
func (*GetBlockResp) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *GetBlockResp) GetBlock() *pb.Block { _ = "STUB: not implemented"; return nil }

type StreamFullCommitQCsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextBlock     uint64                 `protobuf:"varint,1,opt,name=next_block,json=nextBlock,proto3" json:"next_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFullCommitQCsReq) Reset() { _ = "STUB: not implemented"; return }

func (x *StreamFullCommitQCsReq) String() string { _ = "STUB: not implemented"; return "" }

func (*StreamFullCommitQCsReq) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StreamFullCommitQCsReq) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StreamFullCommitQCsReq.ProtoReflect.Descriptor instead.
func (*StreamFullCommitQCsReq) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *StreamFullCommitQCsReq) GetNextBlock() uint64 { _ = "STUB: not implemented"; return 0 }

var File_p2p_giga_api_proto protoreflect.FileDescriptor

const file_p2p_giga_api_proto_rawDesc = "" +
	"\n" +
	"\x12p2p/giga/api.proto\x12\bp2p.giga\x1a\x17autobahn/autobahn.proto\"C\n" +
	"\aLaneReq\x128\n" +
	"\rlane_proposal\x18\x01 \x01(\v2\x13.autobahn.SignedMsgR\flaneProposal\"<\n" +
	"\bLaneResp\x120\n" +
	"\tlane_vote\x18\x01 \x01(\v2\x13.autobahn.SignedMsgR\blaneVote\"\r\n" +
	"\vLaneQCsResp\"\x0f\n" +
	"\rConsensusResp\"\t\n" +
	"\aPingReq\"\n" +
	"\n" +
	"\bPingResp\"<\n" +
	"\bLaneVote\x120\n" +
	"\tlane_vote\x18\x01 \x01(\v2\x13.autobahn.SignedMsgR\blaneVote\"H\n" +
	"\fLaneProposal\x128\n" +
	"\rlane_proposal\x18\x01 \x01(\v2\x13.autobahn.SignedMsgR\flaneProposal\"9\n" +
	"\aAppVote\x12.\n" +
	"\bapp_vote\x18\x01 \x01(\v2\x13.autobahn.SignedMsgR\aappVote\"F\n" +
	"\x16StreamLaneProposalsReq\x12,\n" +
	"\x12first_block_number\x18\x01 \x01(\x04R\x10firstBlockNumber\"\x11\n" +
	"\x0fStreamAppQCsReq\"k\n" +
	"\x10StreamAppQCsResp\x12&\n" +
	"\x06app_qc\x18\x01 \x01(\v2\x0f.autobahn.AppQCR\x05appQc\x12/\n" +
	"\tcommit_qc\x18\x02 \x01(\v2\x12.autobahn.CommitQCR\bcommitQc\"\x14\n" +
	"\x12StreamCommitQCsReq\"\x14\n" +
	"\x12StreamLaneVotesReq\"\x13\n" +
	"\x11StreamAppVotesReq\"2\n" +
	"\vGetBlockReq\x12#\n" +
	"\rglobal_number\x18\x01 \x01(\x04R\fglobalNumber\"D\n" +
	"\fGetBlockResp\x12*\n" +
	"\x05block\x18\x01 \x01(\v2\x0f.autobahn.BlockH\x00R\x05block\x88\x01\x01B\b\n" +
	"\x06_block\"7\n" +
	"\x16StreamFullCommitQCsReq\x12\x1d\n" +
	"\n" +
	"next_block\x18\x01 \x01(\x04R\tnextBlockBGZEgithub.com/sei-protocol/sei-chain/sei-tendermint/internal/p2p/giga/pbb\x06proto3"

var (
	file_p2p_giga_api_proto_rawDescOnce sync.Once
	file_p2p_giga_api_proto_rawDescData []byte
)

func file_p2p_giga_api_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_p2p_giga_api_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_p2p_giga_api_proto_goTypes = []any{
	(*LaneReq)(nil),                // 0: p2p.giga.LaneReq
	(*LaneResp)(nil),               // 1: p2p.giga.LaneResp
	(*LaneQCsResp)(nil),            // 2: p2p.giga.LaneQCsResp
	(*ConsensusResp)(nil),          // 3: p2p.giga.ConsensusResp
	(*PingReq)(nil),                // 4: p2p.giga.PingReq
	(*PingResp)(nil),               // 5: p2p.giga.PingResp
	(*LaneVote)(nil),               // 6: p2p.giga.LaneVote
	(*LaneProposal)(nil),           // 7: p2p.giga.LaneProposal
	(*AppVote)(nil),                // 8: p2p.giga.AppVote
	(*StreamLaneProposalsReq)(nil), // 9: p2p.giga.StreamLaneProposalsReq
	(*StreamAppQCsReq)(nil),        // 10: p2p.giga.StreamAppQCsReq
	(*StreamAppQCsResp)(nil),       // 11: p2p.giga.StreamAppQCsResp
	(*StreamCommitQCsReq)(nil),     // 12: p2p.giga.StreamCommitQCsReq
	(*StreamLaneVotesReq)(nil),     // 13: p2p.giga.StreamLaneVotesReq
	(*StreamAppVotesReq)(nil),      // 14: p2p.giga.StreamAppVotesReq
	(*GetBlockReq)(nil),            // 15: p2p.giga.GetBlockReq
	(*GetBlockResp)(nil),           // 16: p2p.giga.GetBlockResp
	(*StreamFullCommitQCsReq)(nil), // 17: p2p.giga.StreamFullCommitQCsReq
	(*pb.SignedMsg)(nil),           // 18: autobahn.SignedMsg
	(*pb.AppQC)(nil),               // 19: autobahn.AppQC
	(*pb.CommitQC)(nil),            // 20: autobahn.CommitQC
	(*pb.Block)(nil),               // 21: autobahn.Block
}
var file_p2p_giga_api_proto_depIdxs = []int32{
	18, // 0: p2p.giga.LaneReq.lane_proposal:type_name -> autobahn.SignedMsg
	18, // 1: p2p.giga.LaneResp.lane_vote:type_name -> autobahn.SignedMsg
	18, // 2: p2p.giga.LaneVote.lane_vote:type_name -> autobahn.SignedMsg
	18, // 3: p2p.giga.LaneProposal.lane_proposal:type_name -> autobahn.SignedMsg
	18, // 4: p2p.giga.AppVote.app_vote:type_name -> autobahn.SignedMsg
	19, // 5: p2p.giga.StreamAppQCsResp.app_qc:type_name -> autobahn.AppQC
	20, // 6: p2p.giga.StreamAppQCsResp.commit_qc:type_name -> autobahn.CommitQC
	21, // 7: p2p.giga.GetBlockResp.block:type_name -> autobahn.Block
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init()                         { file_p2p_giga_api_proto_init() }
func file_p2p_giga_api_proto_init() { _ = "STUB: not implemented"; return }
