// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sei/admin/v0/admin.proto

package types

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SetLogLevelRequest struct {
	// pattern is a logger name, glob, or "*" for all loggers.
	Pattern string `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	// level is the desired log level (debug, info, warn, error).
	Level string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
}

func (m *SetLogLevelRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SetLogLevelRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*SetLogLevelRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SetLogLevelRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SetLogLevelRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SetLogLevelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SetLogLevelRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SetLogLevelRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SetLogLevelRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SetLogLevelRequest proto.InternalMessageInfo

func (m *SetLogLevelRequest) GetPattern() string { _ = "STUB: not implemented"; return "" }

func (m *SetLogLevelRequest) GetLevel() string { _ = "STUB: not implemented"; return "" }

type SetLogLevelResponse struct {
	Pattern  string `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Level    string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Affected int32  `protobuf:"varint,3,opt,name=affected,proto3" json:"affected,omitempty"`
}

func (m *SetLogLevelResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *SetLogLevelResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*SetLogLevelResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*SetLogLevelResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SetLogLevelResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SetLogLevelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SetLogLevelResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SetLogLevelResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SetLogLevelResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SetLogLevelResponse proto.InternalMessageInfo

func (m *SetLogLevelResponse) GetPattern() string { _ = "STUB: not implemented"; return "" }

func (m *SetLogLevelResponse) GetLevel() string { _ = "STUB: not implemented"; return "" }

func (m *SetLogLevelResponse) GetAffected() int32 { _ = "STUB: not implemented"; return 0 }

type GetLogLevelRequest struct {
	// logger is the exact logger name.
	Logger string `protobuf:"bytes,1,opt,name=logger,proto3" json:"logger,omitempty"`
}

func (m *GetLogLevelRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *GetLogLevelRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*GetLogLevelRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*GetLogLevelRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *GetLogLevelRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *GetLogLevelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GetLogLevelRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *GetLogLevelRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *GetLogLevelRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_GetLogLevelRequest proto.InternalMessageInfo

func (m *GetLogLevelRequest) GetLogger() string { _ = "STUB: not implemented"; return "" }

type GetLogLevelResponse struct {
	Logger string `protobuf:"bytes,1,opt,name=logger,proto3" json:"logger,omitempty"`
	Level  string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
}

func (m *GetLogLevelResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *GetLogLevelResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*GetLogLevelResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*GetLogLevelResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GetLogLevelResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *GetLogLevelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GetLogLevelResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *GetLogLevelResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *GetLogLevelResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_GetLogLevelResponse proto.InternalMessageInfo

func (m *GetLogLevelResponse) GetLogger() string { _ = "STUB: not implemented"; return "" }

func (m *GetLogLevelResponse) GetLevel() string { _ = "STUB: not implemented"; return "" }

type ListLoggersRequest struct {
	// prefix filters loggers by name prefix (optional).
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (m *ListLoggersRequest) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ListLoggersRequest) String() string            { _ = "STUB: not implemented"; return "" }
func (*ListLoggersRequest) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ListLoggersRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ListLoggersRequest) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ListLoggersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ListLoggersRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ListLoggersRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ListLoggersRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ListLoggersRequest proto.InternalMessageInfo

func (m *ListLoggersRequest) GetPrefix() string { _ = "STUB: not implemented"; return "" }

type ListLoggersResponse struct {
	Loggers []LoggerInfo `protobuf:"bytes,1,rep,name=loggers,proto3" json:"loggers"`
}

func (m *ListLoggersResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *ListLoggersResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*ListLoggersResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*ListLoggersResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ListLoggersResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ListLoggersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ListLoggersResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ListLoggersResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ListLoggersResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ListLoggersResponse proto.InternalMessageInfo

func (m *ListLoggersResponse) GetLoggers() []LoggerInfo { _ = "STUB: not implemented"; return nil }

type LoggerInfo struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Level string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
}

func (m *LoggerInfo) Reset()                    { _ = "STUB: not implemented"; return }
func (m *LoggerInfo) String() string            { _ = "STUB: not implemented"; return "" }
func (*LoggerInfo) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*LoggerInfo) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *LoggerInfo) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *LoggerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *LoggerInfo) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *LoggerInfo) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *LoggerInfo) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_LoggerInfo proto.InternalMessageInfo

func (m *LoggerInfo) GetName() string { _ = "STUB: not implemented"; return "" }

func (m *LoggerInfo) GetLevel() string { _ = "STUB: not implemented"; return "" }

func init() {
	proto.RegisterType((*SetLogLevelRequest)(nil), "seiprotocol.seichain.admin.v0.SetLogLevelRequest")
	proto.RegisterType((*SetLogLevelResponse)(nil), "seiprotocol.seichain.admin.v0.SetLogLevelResponse")
	proto.RegisterType((*GetLogLevelRequest)(nil), "seiprotocol.seichain.admin.v0.GetLogLevelRequest")
	proto.RegisterType((*GetLogLevelResponse)(nil), "seiprotocol.seichain.admin.v0.GetLogLevelResponse")
	proto.RegisterType((*ListLoggersRequest)(nil), "seiprotocol.seichain.admin.v0.ListLoggersRequest")
	proto.RegisterType((*ListLoggersResponse)(nil), "seiprotocol.seichain.admin.v0.ListLoggersResponse")
	proto.RegisterType((*LoggerInfo)(nil), "seiprotocol.seichain.admin.v0.LoggerInfo")
}

func init() { proto.RegisterFile("sei/admin/v0/admin.proto", fileDescriptor_d831d27bce99c92f) }

var fileDescriptor_d831d27bce99c92f = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0xcf, 0xd2, 0x40,
	0x10, 0xc6, 0xdb, 0xf7, 0x0f, 0xe8, 0xe0, 0x69, 0x21, 0xa6, 0x21, 0xb1, 0x92, 0x3d, 0x61, 0x02,
	0x2d, 0x62, 0xe2, 0x5d, 0x34, 0x69, 0x48, 0x38, 0x95, 0x9b, 0x27, 0x4b, 0x99, 0x96, 0x4d, 0x4a,
	0xb7, 0x76, 0x97, 0x46, 0xbf, 0x85, 0x1f, 0x8b, 0x23, 0x47, 0x4f, 0xc6, 0xc0, 0x77, 0xf0, 0x6c,
	0xda, 0x6d, 0x15, 0x02, 0xbc, 0xa4, 0xb7, 0x79, 0xba, 0x33, 0xcf, 0x6f, 0xb6, 0x4f, 0x0b, 0x86,
	0x40, 0x66, 0x7b, 0xcb, 0x35, 0x8b, 0xed, 0x6c, 0xa4, 0x0a, 0x2b, 0x49, 0xb9, 0xe4, 0xe4, 0x95,
	0x40, 0x56, 0x54, 0x3e, 0x8f, 0x2c, 0x81, 0xcc, 0x5f, 0x79, 0x2c, 0xb6, 0x54, 0x47, 0x36, 0xea,
	0x76, 0x42, 0x1e, 0xf2, 0xe2, 0xdc, 0xce, 0x2b, 0x35, 0x44, 0x3f, 0x01, 0x99, 0xa3, 0x9c, 0xf1,
	0x70, 0x86, 0x19, 0x46, 0x2e, 0x7e, 0xdd, 0xa0, 0x90, 0xc4, 0x80, 0x66, 0xe2, 0x49, 0x89, 0x69,
	0x6c, 0xe8, 0x3d, 0xbd, 0xff, 0xdc, 0xad, 0x24, 0xe9, 0xc0, 0x63, 0x94, 0x77, 0x1a, 0x77, 0xc5,
	0x73, 0x25, 0xa8, 0x07, 0xed, 0x13, 0x17, 0x91, 0xf0, 0x58, 0x60, 0x5d, 0x1b, 0xd2, 0x85, 0x67,
	0x5e, 0x10, 0xa0, 0x2f, 0x71, 0x69, 0xdc, 0xf7, 0xf4, 0xfe, 0xa3, 0xfb, 0x4f, 0xd3, 0x01, 0x10,
	0xe7, 0x7c, 0xd1, 0x97, 0xd0, 0x88, 0x78, 0x18, 0x62, 0x5a, 0x02, 0x4a, 0x45, 0x3f, 0x42, 0xdb,
	0xb9, 0xb0, 0xd0, 0x95, 0xf6, 0x2b, 0xb7, 0x1a, 0x00, 0x99, 0x31, 0x91, 0xbb, 0x84, 0x98, 0x8a,
	0x23, 0x64, 0x92, 0x62, 0xc0, 0xbe, 0x55, 0x1e, 0x4a, 0xd1, 0x2f, 0xd0, 0x3e, 0xe9, 0x2e, 0x91,
	0x53, 0x68, 0x2a, 0x88, 0x30, 0xf4, 0xde, 0x7d, 0xbf, 0x35, 0x7e, 0x63, 0x3d, 0x99, 0x93, 0xa5,
	0x0c, 0xa6, 0x71, 0xc0, 0x27, 0x0f, 0xdb, 0x5f, 0xaf, 0x35, 0xb7, 0x9a, 0xa7, 0xef, 0x01, 0xfe,
	0x1f, 0x12, 0x02, 0x0f, 0xb1, 0xb7, 0xc6, 0x72, 0x8b, 0xa2, 0xbe, 0x7c, 0x8f, 0xf1, 0x9f, 0x3b,
	0x78, 0xf1, 0x21, 0xb7, 0x9f, 0x63, 0x9a, 0x31, 0x1f, 0x49, 0x06, 0xad, 0xa3, 0xb8, 0xc8, 0xdb,
	0x1b, 0x1b, 0x9d, 0x7f, 0x20, 0xdd, 0x71, 0x9d, 0x11, 0xf5, 0x26, 0xa8, 0x96, 0x73, 0x9d, 0x1a,
	0x5c, 0xa7, 0x3e, 0xd7, 0xb9, 0xc6, 0x3d, 0x8a, 0xe6, 0x26, 0xf7, 0x3c, 0xf4, 0x9b, 0xdc, 0x0b,
	0xc9, 0x53, 0x6d, 0xe2, 0x6c, 0xf7, 0xa6, 0xbe, 0xdb, 0x9b, 0xfa, 0xef, 0xbd, 0xa9, 0xff, 0x38,
	0x98, 0xda, 0xee, 0x60, 0x6a, 0x3f, 0x0f, 0xa6, 0xf6, 0x79, 0x18, 0x32, 0xb9, 0xda, 0x2c, 0x2c,
	0x9f, 0xaf, 0x6d, 0x81, 0x6c, 0x58, 0x59, 0x17, 0xa2, 0xf0, 0x2e, 0xff, 0x71, 0xf9, 0x3d, 0x41,
	0xb1, 0x68, 0x14, 0xe7, 0xef, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x02, 0x27, 0xb5, 0x0d, 0xfd,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminServiceClient interface {
	// SetLogLevel changes the log level for loggers matching a pattern.
	SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*SetLogLevelResponse, error)
	// GetLogLevel returns the current log level for a specific logger.
	GetLogLevel(ctx context.Context, in *GetLogLevelRequest, opts ...grpc.CallOption) (*GetLogLevelResponse, error)
	// ListLoggers returns all registered loggers and their current levels.
	ListLoggers(ctx context.Context, in *ListLoggersRequest, opts ...grpc.CallOption) (*ListLoggersResponse, error)
}

type adminServiceClient struct {
	cc grpc1.ClientConn
}

func NewAdminServiceClient(cc grpc1.ClientConn) AdminServiceClient {
	_ = "STUB: not implemented"
	return *new(AdminServiceClient)
}

func (c *adminServiceClient) SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*SetLogLevelResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *adminServiceClient) GetLogLevel(ctx context.Context, in *GetLogLevelRequest, opts ...grpc.CallOption) (*GetLogLevelResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *adminServiceClient) ListLoggers(ctx context.Context, in *ListLoggersRequest, opts ...grpc.CallOption) (*ListLoggersResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AdminServiceServer is the server API for AdminService service.
type AdminServiceServer interface {
	// SetLogLevel changes the log level for loggers matching a pattern.
	SetLogLevel(context.Context, *SetLogLevelRequest) (*SetLogLevelResponse, error)
	// GetLogLevel returns the current log level for a specific logger.
	GetLogLevel(context.Context, *GetLogLevelRequest) (*GetLogLevelResponse, error)
	// ListLoggers returns all registered loggers and their current levels.
	ListLoggers(context.Context, *ListLoggersRequest) (*ListLoggersResponse, error)
}

// UnimplementedAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (*UnimplementedAdminServiceServer) SetLogLevel(ctx context.Context, req *SetLogLevelRequest) (*SetLogLevelResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedAdminServiceServer) GetLogLevel(ctx context.Context, req *GetLogLevelRequest) (*GetLogLevelResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedAdminServiceServer) ListLoggers(ctx context.Context, req *ListLoggersRequest) (*ListLoggersResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func RegisterAdminServiceServer(s grpc1.Server, srv AdminServiceServer) {
	_ = "STUB: not implemented"
	return
}

func _AdminService_SetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AdminService_GetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AdminService_ListLoggers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var _AdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seiprotocol.seichain.admin.v0.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetLogLevel",
			Handler:    _AdminService_SetLogLevel_Handler,
		},
		{
			MethodName: "GetLogLevel",
			Handler:    _AdminService_GetLogLevel_Handler,
		},
		{
			MethodName: "ListLoggers",
			Handler:    _AdminService_ListLoggers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sei/admin/v0/admin.proto",
}

func (m *SetLogLevelRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SetLogLevelRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SetLogLevelRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SetLogLevelResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SetLogLevelResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SetLogLevelResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GetLogLevelRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GetLogLevelRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GetLogLevelRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GetLogLevelResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GetLogLevelResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GetLogLevelResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ListLoggersRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ListLoggersRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ListLoggersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ListLoggersResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ListLoggersResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ListLoggersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *LoggerInfo) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *LoggerInfo) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *LoggerInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintAdmin(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *SetLogLevelRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SetLogLevelResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *GetLogLevelRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *GetLogLevelResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ListLoggersRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ListLoggersResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *LoggerInfo) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovAdmin(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozAdmin(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SetLogLevelRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SetLogLevelResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *GetLogLevelRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *GetLogLevelResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ListLoggersRequest) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ListLoggersResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *LoggerInfo) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipAdmin(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthAdmin        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAdmin          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAdmin = fmt.Errorf("proto: unexpected end of group")
)
