// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/distribution/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_sei_protocol_sei_chain_sei_cosmos_types "github.com/sei-protocol/sei-chain/sei-cosmos/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DelegatorWithdrawInfo is the address for where distributions rewards are
// withdrawn to by default this struct is only used at genesis to feed in
// default withdraw addresses.
type DelegatorWithdrawInfo struct {
	// delegator_address is the address of the delegator.
	DelegatorAddress string `protobuf:"bytes,1,opt,name=delegator_address,json=delegatorAddress,proto3" json:"delegator_address,omitempty" yaml:"delegator_address"`
	// withdraw_address is the address to withdraw the delegation rewards to.
	WithdrawAddress string `protobuf:"bytes,2,opt,name=withdraw_address,json=withdrawAddress,proto3" json:"withdraw_address,omitempty" yaml:"withdraw_address"`
}

func (m *DelegatorWithdrawInfo) Reset()         { _ = "STUB: not implemented"; return }
func (m *DelegatorWithdrawInfo) String() string { _ = "STUB: not implemented"; return "" }
func (*DelegatorWithdrawInfo) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*DelegatorWithdrawInfo) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DelegatorWithdrawInfo) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *DelegatorWithdrawInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DelegatorWithdrawInfo) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *DelegatorWithdrawInfo) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *DelegatorWithdrawInfo) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_DelegatorWithdrawInfo proto.InternalMessageInfo

// ValidatorOutstandingRewardsRecord is used for import/export via genesis json.
type ValidatorOutstandingRewardsRecord struct {
	// validator_address is the address of the validator.
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty" yaml:"validator_address"`
	// outstanding_rewards represents the oustanding rewards of a validator.
	OutstandingRewards github_com_sei_protocol_sei_chain_sei_cosmos_types.DecCoins `protobuf:"bytes,2,rep,name=outstanding_rewards,json=outstandingRewards,proto3,castrepeated=github.com/sei-protocol/sei-chain/sei-cosmos/types.DecCoins" json:"outstanding_rewards" yaml:"outstanding_rewards"`
}

func (m *ValidatorOutstandingRewardsRecord) Reset()         { _ = "STUB: not implemented"; return }
func (m *ValidatorOutstandingRewardsRecord) String() string { _ = "STUB: not implemented"; return "" }
func (*ValidatorOutstandingRewardsRecord) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*ValidatorOutstandingRewardsRecord) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorOutstandingRewardsRecord) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ValidatorOutstandingRewardsRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorOutstandingRewardsRecord) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *ValidatorOutstandingRewardsRecord) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ValidatorOutstandingRewardsRecord) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ValidatorOutstandingRewardsRecord proto.InternalMessageInfo

// ValidatorAccumulatedCommissionRecord is used for import / export via genesis
// json.
type ValidatorAccumulatedCommissionRecord struct {
	// validator_address is the address of the validator.
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty" yaml:"validator_address"`
	// accumulated is the accumulated commission of a validator.
	Accumulated ValidatorAccumulatedCommission `protobuf:"bytes,2,opt,name=accumulated,proto3" json:"accumulated" yaml:"accumulated"`
}

func (m *ValidatorAccumulatedCommissionRecord) Reset() { _ = "STUB: not implemented"; return }
func (m *ValidatorAccumulatedCommissionRecord) String() string {
	_ = "STUB: not implemented"
	return ""
}
func (*ValidatorAccumulatedCommissionRecord) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*ValidatorAccumulatedCommissionRecord) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorAccumulatedCommissionRecord) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ValidatorAccumulatedCommissionRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorAccumulatedCommissionRecord) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *ValidatorAccumulatedCommissionRecord) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ValidatorAccumulatedCommissionRecord) XXX_DiscardUnknown() {
	_ = "STUB: not implemented"
	return
}

var xxx_messageInfo_ValidatorAccumulatedCommissionRecord proto.InternalMessageInfo

// ValidatorHistoricalRewardsRecord is used for import / export via genesis
// json.
type ValidatorHistoricalRewardsRecord struct {
	// validator_address is the address of the validator.
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty" yaml:"validator_address"`
	// period defines the period the historical rewards apply to.
	Period uint64 `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`
	// rewards defines the historical rewards of a validator.
	Rewards ValidatorHistoricalRewards `protobuf:"bytes,3,opt,name=rewards,proto3" json:"rewards" yaml:"rewards"`
}

func (m *ValidatorHistoricalRewardsRecord) Reset()         { _ = "STUB: not implemented"; return }
func (m *ValidatorHistoricalRewardsRecord) String() string { _ = "STUB: not implemented"; return "" }
func (*ValidatorHistoricalRewardsRecord) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*ValidatorHistoricalRewardsRecord) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorHistoricalRewardsRecord) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ValidatorHistoricalRewardsRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorHistoricalRewardsRecord) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *ValidatorHistoricalRewardsRecord) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ValidatorHistoricalRewardsRecord) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ValidatorHistoricalRewardsRecord proto.InternalMessageInfo

// ValidatorCurrentRewardsRecord is used for import / export via genesis json.
type ValidatorCurrentRewardsRecord struct {
	// validator_address is the address of the validator.
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty" yaml:"validator_address"`
	// rewards defines the current rewards of a validator.
	Rewards ValidatorCurrentRewards `protobuf:"bytes,2,opt,name=rewards,proto3" json:"rewards" yaml:"rewards"`
}

func (m *ValidatorCurrentRewardsRecord) Reset()         { _ = "STUB: not implemented"; return }
func (m *ValidatorCurrentRewardsRecord) String() string { _ = "STUB: not implemented"; return "" }
func (*ValidatorCurrentRewardsRecord) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*ValidatorCurrentRewardsRecord) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorCurrentRewardsRecord) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ValidatorCurrentRewardsRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorCurrentRewardsRecord) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *ValidatorCurrentRewardsRecord) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ValidatorCurrentRewardsRecord) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ValidatorCurrentRewardsRecord proto.InternalMessageInfo

// DelegatorStartingInfoRecord used for import / export via genesis json.
type DelegatorStartingInfoRecord struct {
	// delegator_address is the address of the delegator.
	DelegatorAddress string `protobuf:"bytes,1,opt,name=delegator_address,json=delegatorAddress,proto3" json:"delegator_address,omitempty" yaml:"delegator_address"`
	// validator_address is the address of the validator.
	ValidatorAddress string `protobuf:"bytes,2,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty" yaml:"validator_address"`
	// starting_info defines the starting info of a delegator.
	StartingInfo DelegatorStartingInfo `protobuf:"bytes,3,opt,name=starting_info,json=startingInfo,proto3" json:"starting_info" yaml:"starting_info"`
}

func (m *DelegatorStartingInfoRecord) Reset()         { _ = "STUB: not implemented"; return }
func (m *DelegatorStartingInfoRecord) String() string { _ = "STUB: not implemented"; return "" }
func (*DelegatorStartingInfoRecord) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*DelegatorStartingInfoRecord) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DelegatorStartingInfoRecord) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *DelegatorStartingInfoRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DelegatorStartingInfoRecord) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *DelegatorStartingInfoRecord) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *DelegatorStartingInfoRecord) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_DelegatorStartingInfoRecord proto.InternalMessageInfo

// ValidatorSlashEventRecord is used for import / export via genesis json.
type ValidatorSlashEventRecord struct {
	// validator_address is the address of the validator.
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty" yaml:"validator_address"`
	// height defines the block height at which the slash event occured.
	Height uint64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	// period is the period of the slash event.
	Period uint64 `protobuf:"varint,3,opt,name=period,proto3" json:"period,omitempty"`
	// validator_slash_event describes the slash event.
	ValidatorSlashEvent ValidatorSlashEvent `protobuf:"bytes,4,opt,name=validator_slash_event,json=validatorSlashEvent,proto3" json:"validator_slash_event" yaml:"event"`
}

func (m *ValidatorSlashEventRecord) Reset()         { _ = "STUB: not implemented"; return }
func (m *ValidatorSlashEventRecord) String() string { _ = "STUB: not implemented"; return "" }
func (*ValidatorSlashEventRecord) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*ValidatorSlashEventRecord) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorSlashEventRecord) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ValidatorSlashEventRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorSlashEventRecord) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ValidatorSlashEventRecord) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ValidatorSlashEventRecord) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ValidatorSlashEventRecord proto.InternalMessageInfo

// GenesisState defines the distribution module's genesis state.
type GenesisState struct {
	// params defines all the paramaters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params" yaml:"params"`
	// fee_pool defines the fee pool at genesis.
	FeePool FeePool `protobuf:"bytes,2,opt,name=fee_pool,json=feePool,proto3" json:"fee_pool" yaml:"fee_pool"`
	// fee_pool defines the delegator withdraw infos at genesis.
	DelegatorWithdrawInfos []DelegatorWithdrawInfo `protobuf:"bytes,3,rep,name=delegator_withdraw_infos,json=delegatorWithdrawInfos,proto3" json:"delegator_withdraw_infos" yaml:"delegator_withdraw_infos"`
	// fee_pool defines the previous proposer at genesis.
	PreviousProposer string `protobuf:"bytes,4,opt,name=previous_proposer,json=previousProposer,proto3" json:"previous_proposer,omitempty" yaml:"previous_proposer"`
	// fee_pool defines the outstanding rewards of all validators at genesis.
	OutstandingRewards []ValidatorOutstandingRewardsRecord `protobuf:"bytes,5,rep,name=outstanding_rewards,json=outstandingRewards,proto3" json:"outstanding_rewards" yaml:"outstanding_rewards"`
	// fee_pool defines the accumulated commisions of all validators at genesis.
	ValidatorAccumulatedCommissions []ValidatorAccumulatedCommissionRecord `protobuf:"bytes,6,rep,name=validator_accumulated_commissions,json=validatorAccumulatedCommissions,proto3" json:"validator_accumulated_commissions" yaml:"validator_accumulated_commissions"`
	// fee_pool defines the historical rewards of all validators at genesis.
	ValidatorHistoricalRewards []ValidatorHistoricalRewardsRecord `protobuf:"bytes,7,rep,name=validator_historical_rewards,json=validatorHistoricalRewards,proto3" json:"validator_historical_rewards" yaml:"validator_historical_rewards"`
	// fee_pool defines the current rewards of all validators at genesis.
	ValidatorCurrentRewards []ValidatorCurrentRewardsRecord `protobuf:"bytes,8,rep,name=validator_current_rewards,json=validatorCurrentRewards,proto3" json:"validator_current_rewards" yaml:"validator_current_rewards"`
	// fee_pool defines the delegator starting infos at genesis.
	DelegatorStartingInfos []DelegatorStartingInfoRecord `protobuf:"bytes,9,rep,name=delegator_starting_infos,json=delegatorStartingInfos,proto3" json:"delegator_starting_infos" yaml:"delegator_starting_infos"`
	// fee_pool defines the validator slash events at genesis.
	ValidatorSlashEvents []ValidatorSlashEventRecord `protobuf:"bytes,10,rep,name=validator_slash_events,json=validatorSlashEvents,proto3" json:"validator_slash_events" yaml:"validator_slash_events"`
}

func (m *GenesisState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *GenesisState) String() string            { _ = "STUB: not implemented"; return "" }
func (*GenesisState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*GenesisState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *GenesisState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GenesisState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *GenesisState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *GenesisState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DelegatorWithdrawInfo)(nil), "cosmos.distribution.v1beta1.DelegatorWithdrawInfo")
	proto.RegisterType((*ValidatorOutstandingRewardsRecord)(nil), "cosmos.distribution.v1beta1.ValidatorOutstandingRewardsRecord")
	proto.RegisterType((*ValidatorAccumulatedCommissionRecord)(nil), "cosmos.distribution.v1beta1.ValidatorAccumulatedCommissionRecord")
	proto.RegisterType((*ValidatorHistoricalRewardsRecord)(nil), "cosmos.distribution.v1beta1.ValidatorHistoricalRewardsRecord")
	proto.RegisterType((*ValidatorCurrentRewardsRecord)(nil), "cosmos.distribution.v1beta1.ValidatorCurrentRewardsRecord")
	proto.RegisterType((*DelegatorStartingInfoRecord)(nil), "cosmos.distribution.v1beta1.DelegatorStartingInfoRecord")
	proto.RegisterType((*ValidatorSlashEventRecord)(nil), "cosmos.distribution.v1beta1.ValidatorSlashEventRecord")
	proto.RegisterType((*GenesisState)(nil), "cosmos.distribution.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("cosmos/distribution/v1beta1/genesis.proto", fileDescriptor_76eed0f9489db580)
}

var fileDescriptor_76eed0f9489db580 = []byte{
	// 1034 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xf6, 0x3a, 0x25, 0x49, 0xc7, 0x29, 0x0d, 0xdb, 0xfc, 0x70, 0x9d, 0xd4, 0x4e, 0xa7, 0x45,
	0x04, 0x21, 0xd6, 0x6d, 0x40, 0x80, 0x52, 0x81, 0x94, 0x4d, 0x29, 0xf4, 0x44, 0x34, 0x91, 0x00,
	0x71, 0xb1, 0xc6, 0xbb, 0x63, 0x7b, 0xa4, 0xf5, 0x8e, 0xb5, 0x33, 0x76, 0x08, 0xff, 0x00, 0x1c,
	0x91, 0x10, 0x27, 0x38, 0xe4, 0x88, 0x80, 0x03, 0x87, 0xde, 0xb9, 0xf6, 0xd8, 0x23, 0x07, 0x14,
	0x50, 0x72, 0xe1, 0x9c, 0x03, 0x07, 0x4e, 0x68, 0x67, 0x66, 0x7f, 0xd9, 0x6b, 0xe3, 0x84, 0xe6,
	0xb6, 0x3b, 0x7e, 0xf3, 0x7d, 0xdf, 0xfb, 0xe6, 0xbd, 0x79, 0x6b, 0xf0, 0xaa, 0xc3, 0x78, 0x97,
	0xf1, 0xba, 0x4b, 0xb9, 0x08, 0x68, 0xb3, 0x2f, 0x28, 0xf3, 0xeb, 0x83, 0xfb, 0x4d, 0x22, 0xf0,
	0xfd, 0x7a, 0x9b, 0xf8, 0x84, 0x53, 0x6e, 0xf5, 0x02, 0x26, 0x98, 0xb9, 0xa6, 0x42, 0xad, 0x74,
	0xa8, 0xa5, 0x43, 0x2b, 0x55, 0x8d, 0xd3, 0xc4, 0x9c, 0xc4, 0xfb, 0x1d, 0x46, 0x7d, 0xb5, 0xb9,
	0x62, 0x4d, 0xe2, 0xc9, 0x20, 0xaa, 0xf8, 0xa5, 0x36, 0x6b, 0x33, 0xf9, 0x58, 0x0f, 0x9f, 0xd4,
	0x2a, 0x7c, 0x62, 0x80, 0xe5, 0x87, 0xc4, 0x23, 0x6d, 0x2c, 0x58, 0xf0, 0x09, 0x15, 0x1d, 0x37,
	0xc0, 0x07, 0x8f, 0xfd, 0x16, 0x33, 0x1f, 0x83, 0x97, 0xdc, 0xe8, 0x87, 0x06, 0x76, 0xdd, 0x80,
	0x70, 0x5e, 0x36, 0x36, 0x8c, 0xcd, 0xab, 0xf6, 0xfa, 0xd9, 0x71, 0xad, 0x7c, 0x88, 0xbb, 0xde,
	0x36, 0x1c, 0x09, 0x81, 0x68, 0x31, 0x5e, 0xdb, 0x51, 0x4b, 0xe6, 0x23, 0xb0, 0x78, 0xa0, 0xa1,
	0x63, 0xa4, 0xa2, 0x44, 0x5a, 0x3b, 0x3b, 0xae, 0xad, 0x2a, 0xa4, 0xe1, 0x08, 0x88, 0xae, 0x47,
	0x4b, 0x1a, 0x67, 0x7b, 0xfe, 0xab, 0xa3, 0x5a, 0xe1, 0xaf, 0xa3, 0x5a, 0x01, 0xfe, 0x54, 0x04,
	0xb7, 0x3f, 0xc6, 0x1e, 0x75, 0x43, 0x9a, 0x8f, 0xfa, 0x82, 0x0b, 0xec, 0xbb, 0xd4, 0x6f, 0x23,
	0x72, 0x80, 0x03, 0x97, 0x23, 0xe2, 0xb0, 0xc0, 0x0d, 0x53, 0x18, 0x44, 0x41, 0xe3, 0x53, 0x18,
	0x09, 0x81, 0x68, 0x31, 0x5e, 0x8b, 0x52, 0xf8, 0xc5, 0x00, 0x37, 0x58, 0xc2, 0xd3, 0x08, 0x14,
	0x51, 0xb9, 0xb8, 0x31, 0xb3, 0x59, 0xda, 0x5a, 0xd7, 0x87, 0x61, 0x85, 0x87, 0x15, 0x9d, 0xa0,
	0xf5, 0x90, 0x38, 0xbb, 0x8c, 0xfa, 0x36, 0x7e, 0x7a, 0x5c, 0x2b, 0x9c, 0x1d, 0xd7, 0x2a, 0x8a,
	0x2f, 0x07, 0x06, 0xfe, 0xf8, 0x47, 0xed, 0x41, 0x9b, 0x8a, 0x4e, 0xbf, 0x69, 0x39, 0xac, 0x5b,
	0xe7, 0x84, 0xbe, 0x2e, 0xcf, 0xc7, 0x61, 0x9e, 0x7c, 0x71, 0x3a, 0x98, 0xfa, 0xea, 0x49, 0x9d,
	0xba, 0x38, 0xec, 0x11, 0x1e, 0x31, 0x70, 0x64, 0xb2, 0x11, 0x0f, 0x52, 0x6e, 0xfd, 0x6d, 0x80,
	0xbb, 0xb1, 0x5b, 0x3b, 0x8e, 0xd3, 0xef, 0xf6, 0x3d, 0x2c, 0x88, 0xbb, 0xcb, 0xba, 0x5d, 0xca,
	0x39, 0x65, 0xfe, 0xf3, 0x37, 0xec, 0x10, 0x94, 0x70, 0xc2, 0x24, 0x8f, 0xbb, 0xb4, 0xf5, 0xc0,
	0x9a, 0x50, 0xf1, 0xd6, 0x64, 0x89, 0x76, 0x45, 0xdb, 0x68, 0x2a, 0x15, 0x29, 0x74, 0x88, 0xd2,
	0x5c, 0xa9, 0xc4, 0xff, 0x31, 0xc0, 0x46, 0x8c, 0xfa, 0x21, 0xe5, 0x82, 0x05, 0xd4, 0xc1, 0xde,
	0xa5, 0x55, 0xc9, 0x0a, 0x98, 0xed, 0x91, 0x80, 0x32, 0x95, 0xef, 0x15, 0xa4, 0xdf, 0x4c, 0x0a,
	0xe6, 0xa2, 0x82, 0x99, 0x91, 0x46, 0xbc, 0x3d, 0x9d, 0x11, 0x23, 0x92, 0xed, 0x15, 0x6d, 0xc2,
	0x8b, 0x4a, 0x55, 0x54, 0x3f, 0x28, 0xc2, 0x4f, 0x25, 0xff, 0xbb, 0x01, 0x6e, 0xc5, 0x48, 0xbb,
	0xfd, 0x20, 0x20, 0xbe, 0xb8, 0xb4, 0xcc, 0x5b, 0x49, 0x86, 0xea, 0xa8, 0xdf, 0x9c, 0x2e, 0xc3,
	0xac, 0xae, 0xf3, 0xa4, 0xf7, 0xa4, 0x08, 0xd6, 0xe2, 0x9b, 0x6b, 0x5f, 0xe0, 0x40, 0x50, 0xbf,
	0x1d, 0xde, 0x5c, 0x49, 0x72, 0xcf, 0xeb, 0xfe, 0xca, 0xf5, 0xa9, 0x78, 0x21, 0x9f, 0xfa, 0xe0,
	0x1a, 0xd7, 0x5a, 0x1b, 0xd4, 0x6f, 0x31, 0x5d, 0x0f, 0x5b, 0x13, 0xdd, 0xca, 0x4d, 0xd3, 0x5e,
	0xd7, 0x5e, 0x2d, 0x29, 0xfa, 0x0c, 0x2c, 0x44, 0x0b, 0x3c, 0x15, 0x9b, 0xb2, 0xed, 0xfb, 0x22,
	0xb8, 0x19, 0xbb, 0xbf, 0xef, 0x61, 0xde, 0x79, 0x7f, 0x20, 0x0f, 0xe0, 0x12, 0x7a, 0xa1, 0x43,
	0x68, 0xbb, 0x23, 0xa2, 0x5e, 0x50, 0x6f, 0xa9, 0x1e, 0x99, 0xc9, 0xf4, 0xc8, 0x17, 0x60, 0x39,
	0xc1, 0xe5, 0xa1, 0xb0, 0x06, 0x09, 0x95, 0x95, 0xaf, 0x48, 0x87, 0xee, 0x4d, 0x57, 0x4f, 0x49,
	0x46, 0xf6, 0x92, 0xf6, 0x67, 0x41, 0x89, 0x96, 0x60, 0x10, 0xdd, 0x18, 0x8c, 0x86, 0xa6, 0xec,
	0xf9, 0xb2, 0x04, 0x16, 0x3e, 0x50, 0x43, 0x7a, 0x5f, 0x60, 0x41, 0x4c, 0x04, 0x66, 0x7b, 0x38,
	0xc0, 0x5d, 0x65, 0x43, 0x69, 0xeb, 0xce, 0x44, 0x1d, 0x7b, 0x32, 0xd4, 0x5e, 0xd6, 0xd4, 0xd7,
	0x14, 0xb5, 0x02, 0x80, 0x48, 0x23, 0x99, 0x9f, 0x82, 0xf9, 0x16, 0x21, 0x8d, 0x1e, 0x63, 0x9e,
	0xee, 0x96, 0xbb, 0x13, 0x51, 0x1f, 0x11, 0xb2, 0xc7, 0x98, 0x67, 0xaf, 0x6a, 0xd8, 0xeb, 0x0a,
	0x36, 0xc2, 0x80, 0x68, 0xae, 0xa5, 0x22, 0xcc, 0x6f, 0x0d, 0x50, 0x4e, 0x4a, 0x3a, 0x1e, 0xa9,
	0x61, 0x49, 0x84, 0x57, 0xcf, 0xcc, 0xf4, 0xa5, 0x96, 0xfe, 0x16, 0xb0, 0x5f, 0xd1, 0xc4, 0xb5,
	0xe1, 0xa6, 0xc9, 0x32, 0x40, 0xb4, 0xe2, 0xe6, 0xed, 0x97, 0x1d, 0xd4, 0x0b, 0xc8, 0x80, 0xb2,
	0x3e, 0x6f, 0xf4, 0x02, 0xd6, 0x63, 0x9c, 0x04, 0xf2, 0x60, 0x33, 0x75, 0x35, 0x12, 0x02, 0xd1,
	0x62, 0xb4, 0xb6, 0xa7, 0x97, 0xcc, 0x6f, 0xc6, 0x4c, 0xe2, 0x17, 0x64, 0x76, 0xef, 0x4d, 0x57,
	0x26, 0xe3, 0x3e, 0x19, 0x6c, 0xf8, 0xdf, 0xb3, 0x3a, 0x6f, 0xd8, 0x9a, 0xbf, 0x1a, 0xe0, 0x76,
	0xaa, 0x2d, 0x92, 0x69, 0xd4, 0x70, 0xe2, 0x09, 0xc6, 0xcb, 0xb3, 0x52, 0xe3, 0xce, 0xff, 0x98,
	0x82, 0x5a, 0xe6, 0x3d, 0x2d, 0x73, 0x73, 0xa4, 0x21, 0xf3, 0x99, 0x21, 0xaa, 0x0d, 0x26, 0xe2,
	0x72, 0xf3, 0x67, 0x03, 0xac, 0x27, 0x38, 0x9d, 0x78, 0xf2, 0xc4, 0x06, 0xcf, 0x49, 0xf1, 0xef,
	0x5e, 0x70, 0x72, 0x69, 0xe1, 0xaf, 0x69, 0xe1, 0x77, 0x86, 0x85, 0x8f, 0x12, 0x42, 0x54, 0x19,
	0x8c, 0x85, 0x33, 0x8f, 0x0c, 0x70, 0x33, 0xd9, 0xed, 0xa8, 0x31, 0x12, 0x6b, 0x9d, 0x97, 0x5a,
	0xb7, 0x2f, 0x32, 0x83, 0xb4, 0xd0, 0x4d, 0x2d, 0x74, 0x63, 0x58, 0xe8, 0x10, 0x15, 0x44, 0xab,
	0x83, 0x7c, 0x20, 0xf3, 0xbb, 0x4c, 0x33, 0x66, 0xee, 0x67, 0x5e, 0xbe, 0x2a, 0x15, 0xbe, 0x73,
	0xfe, 0x7b, 0x5f, 0xeb, 0x1b, 0xdb, 0x92, 0x59, 0x9e, 0x74, 0x4b, 0xa6, 0x51, 0x78, 0xd8, 0x47,
	0x2b, 0xb9, 0x17, 0x2e, 0x2f, 0x03, 0xa9, 0xed, 0xad, 0xf3, 0xde, 0xb8, 0x5a, 0xd9, 0xcb, 0x5a,
	0xd9, 0xad, 0x61, 0xe7, 0xd2, 0x1c, 0x10, 0x2d, 0xe5, 0x5c, 0xc4, 0xa9, 0xf9, 0x6e, 0x37, 0x7e,
	0x38, 0xa9, 0x1a, 0x4f, 0x4f, 0xaa, 0xc6, 0xb3, 0x93, 0xaa, 0xf1, 0xe7, 0x49, 0xd5, 0xf8, 0xfa,
	0xb4, 0x5a, 0x78, 0x76, 0x5a, 0x2d, 0xfc, 0x76, 0x5a, 0x2d, 0x7c, 0xb6, 0x73, 0xae, 0xaf, 0xe5,
	0xcf, 0xb3, 0xff, 0x92, 0xe4, 0xc7, 0x73, 0x73, 0x56, 0xee, 0x79, 0xe3, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x8d, 0x9b, 0xc1, 0x7a, 0xb1, 0x0d, 0x00, 0x00,
}

func (m *DelegatorWithdrawInfo) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DelegatorWithdrawInfo) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DelegatorWithdrawInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ValidatorOutstandingRewardsRecord) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorOutstandingRewardsRecord) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ValidatorOutstandingRewardsRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ValidatorAccumulatedCommissionRecord) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorAccumulatedCommissionRecord) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ValidatorAccumulatedCommissionRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ValidatorHistoricalRewardsRecord) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorHistoricalRewardsRecord) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ValidatorHistoricalRewardsRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ValidatorCurrentRewardsRecord) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorCurrentRewardsRecord) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ValidatorCurrentRewardsRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DelegatorStartingInfoRecord) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DelegatorStartingInfoRecord) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *DelegatorStartingInfoRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ValidatorSlashEventRecord) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ValidatorSlashEventRecord) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ValidatorSlashEventRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *DelegatorWithdrawInfo) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ValidatorOutstandingRewardsRecord) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ValidatorAccumulatedCommissionRecord) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ValidatorHistoricalRewardsRecord) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ValidatorCurrentRewardsRecord) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DelegatorStartingInfoRecord) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ValidatorSlashEventRecord) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *GenesisState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovGenesis(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozGenesis(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DelegatorWithdrawInfo) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ValidatorOutstandingRewardsRecord) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ValidatorAccumulatedCommissionRecord) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ValidatorHistoricalRewardsRecord) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ValidatorCurrentRewardsRecord) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *DelegatorStartingInfoRecord) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ValidatorSlashEventRecord) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *GenesisState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipGenesis(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
